// This file is autogenerated by ra-metapac-gen: do not edit by hand.
#[path = "../../peripherals/agt_16bits.rs"]
pub mod agt;
#[path = "../../peripherals/gpt_v1.rs"]
pub mod gpt;
#[path = "../../peripherals/icu_rka8d2.rs"]
pub mod icu;
#[path = "../../peripherals/mstp_v2.rs"]
pub mod mstp;
#[path = "../../peripherals/pfs_v1.rs"]
pub mod pfs;
#[path = "../../peripherals/port_v1.rs"]
pub mod port;
#[path = "../../peripherals/sysc_v6.rs"]
pub mod sysc;

pub const AGT0: agt::Agt = unsafe { agt::Agt::from_ptr(0x40221000usize as _) };
pub const AGT1: agt::Agt = unsafe { agt::Agt::from_ptr(0x40221100usize as _) };
pub const GPT0: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40322000usize as _) };
pub const GPT1: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40322100usize as _) };
pub const GPT2: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40322200usize as _) };
pub const GPT3: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40322300usize as _) };
pub const GPT4: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40322400usize as _) };
pub const GPT5: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40322500usize as _) };
pub const GPT6: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40322600usize as _) };
pub const GPT7: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40322700usize as _) };
pub const GPT8: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40322800usize as _) };
pub const GPT9: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40322900usize as _) };
pub const GPT10: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40322a00usize as _) };
pub const GPT11: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40322b00usize as _) };
pub const GPT12: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40322c00usize as _) };
pub const GPT13: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40322d00usize as _) };
pub const ICU: icu::Icu = unsafe { icu::Icu::from_ptr(0x40006000usize as _) };
pub const ICU: icu::Icu = unsafe { icu::Icu::from_ptr(0x40006000usize as _) };
pub const MSTP: mstp::Mstp = unsafe { mstp::Mstp::from_ptr(0x40203000usize as _) };
pub const PFS: pfs::Pfs = unsafe { pfs::Pfs::from_ptr(0x40400800usize as _) };
pub const PORT0: port::PortExtended = unsafe { port::PortExtended::from_ptr(0x40400000usize as _) };
pub const PORT1: port::PortExtended = unsafe { port::PortExtended::from_ptr(0x40400020usize as _) };
pub const PORT2: port::PortExtended = unsafe { port::PortExtended::from_ptr(0x40400040usize as _) };
pub const PORT3: port::PortExtended = unsafe { port::PortExtended::from_ptr(0x40400060usize as _) };
pub const PORT4: port::PortExtended = unsafe { port::PortExtended::from_ptr(0x40400080usize as _) };
pub const PORT5: port::PortExtended = unsafe { port::PortExtended::from_ptr(0x404000a0usize as _) };
pub const PORT6: port::PortExtended = unsafe { port::PortExtended::from_ptr(0x404000c0usize as _) };
pub const PORT7: port::PortExtended = unsafe { port::PortExtended::from_ptr(0x404000e0usize as _) };
pub const PORT8: port::PortExtended = unsafe { port::PortExtended::from_ptr(0x40400100usize as _) };
pub const PORT9: port::PortExtended = unsafe { port::PortExtended::from_ptr(0x40400120usize as _) };
pub const SYSC: sysc::Sysc = unsafe { sysc::Sysc::from_ptr(0x4001e000usize as _) };

#[macro_export]
macro_rules! foreach_event {
    ($($m:tt)*) => {
        $($m)*! {
            (Acmphs0Int, 198, ()),
            (Acmphs1Int, 199, ()),
            (Acmphs2Int, 200, ()),
            (Acmphs3Int, 201, ()),
            (AdcAdi0, 845, ()),
            (AdcAdi1, 846, ()),
            (AdcAdi2, 847, ()),
            (AdcAdi3, 848, ()),
            (AdcAdi4, 849, ()),
            (AdcAdi5, 850, ()),
            (AdcAdi6, 851, ()),
            (AdcAdi7, 852, ()),
            (AdcAdi8, 853, ()),
            (AdcCalend0, 870, ()),
            (AdcCalend1, 878, ()),
            (AdcCalreq0, 869, ()),
            (AdcCalreq1, 877, ()),
            (AdcCcmpm0, 865, ()),
            (AdcCcmpm1, 873, ()),
            (AdcCcmpum0, 866, ()),
            (AdcCcmpum1, 874, ()),
            (AdcCmpi0, 863, ()),
            (AdcCmpi1, 864, ()),
            (AdcCmpi2, 871, ()),
            (AdcCmpi3, 872, ()),
            (AdcErr0, 867, ()),
            (AdcErr1, 875, ()),
            (AdcFifoovf, 844, ()),
            (AdcFiforeq0, 854, ()),
            (AdcFiforeq1, 855, ()),
            (AdcFiforeq2, 856, ()),
            (AdcFiforeq3, 857, ()),
            (AdcFiforeq4, 858, ()),
            (AdcFiforeq5, 859, ()),
            (AdcFiforeq6, 860, ()),
            (AdcFiforeq7, 861, ()),
            (AdcFiforeq8, 862, ()),
            (AdcLimclpi, 843, ()),
            (AdcResovf0, 868, ()),
            (AdcResovf1, 876, ()),
            (Agt0CompareA, 135, ()),
            (Agt0CompareB, 136, ()),
            (Agt0Int, 134, ()),
            (Agt1CompareA, 138, ()),
            (Agt1CompareB, 139, ()),
            (Agt1Int, 137, ()),
            (BusErr, 99, ()),
            (CacFrequencyError, 212, ()),
            (CacMeasurementEnd, 213, ()),
            (CacOverflow, 214, ()),
            (Can0CfDmareq, 815, ()),
            (Can0Cherr, 813, ()),
            (Can0Comfrx, 814, ()),
            (Can0Dmareq0, 804, ()),
            (Can0Dmareq1, 805, ()),
            (Can0MramEri, 824, ()),
            (Can0Rxmb, 816, ()),
            (Can0Tx, 812, ()),
            (Can1CfDmareq, 820, ()),
            (Can1Cherr, 818, ()),
            (Can1Comfrx, 819, ()),
            (Can1Dmareq0, 808, ()),
            (Can1Dmareq1, 809, ()),
            (Can1MramEri, 825, ()),
            (Can1Rxmb, 821, ()),
            (Can1Tx, 817, ()),
            (CanGlerr, 803, ()),
            (CanRxf, 802, ()),
            (CeuCeui, 919, ()),
            (CgcMoscStop, 118, ()),
            (CgcSoscStop, 119, ()),
            (CmErr, 100, ()),
            (Cpu0Lockup, 97, ()),
            (Cpu1Lockup, 98, ()),
            (DbgCtiirq0, 88, ()),
            (DbgCtiirq1, 89, ()),
            (DbgJbrxi, 90, ()),
            (Dma1Transerr, 87, ()),
            (Dmac0Int, 64, ()),
            (Dmac10Int, 72, ()),
            (Dmac11Int, 73, ()),
            (Dmac12Int, 74, ()),
            (Dmac13Int, 75, ()),
            (Dmac14Int, 76, ()),
            (Dmac15Int, 77, ()),
            (Dmac16Int, 78, ()),
            (Dmac17Int, 79, ()),
            (Dmac1Int, 65, ()),
            (Dmac2Int, 66, ()),
            (Dmac3Int, 67, ()),
            (Dmac4Int, 68, ()),
            (Dmac5Int, 69, ()),
            (Dmac6Int, 70, ()),
            (Dmac7Int, 71, ()),
            (DmaTranserr, 86, ()),
            (DocInt, 879, ()),
            (DrwInt, 901, ()),
            (Dtc1End, 85, ()),
            (DtcEnd, 82, ()),
            (ElcSoftwareEvent0, 204, ()),
            (ElcSoftwareEvent1, 205, ()),
            (ElcSoftwareEvent2, 206, ()),
            (ElcSoftwareEvent3, 207, ()),
            (EtherCaei, 667, ()),
            (EtherCami, 675, ()),
            (EtherEaei0, 669, ()),
            (EtherEaei1, 670, ()),
            (EtherEasi0, 676, ()),
            (EtherEasi1, 677, ()),
            (EtherFwei, 666, ()),
            (EtherFwsi, 673, ()),
            (EtherGwdi0, 678, ()),
            (EtherGwdi1, 679, ()),
            (EtherGwdi2, 680, ()),
            (EtherGwdi3, 681, ()),
            (EtherGwdi4, 682, ()),
            (EtherGwdi5, 683, ()),
            (EtherGwdi6, 684, ()),
            (EtherGwdi7, 685, ()),
            (EtherGwei, 668, ()),
            (EtherMdio0, 688, ()),
            (EtherMdio1, 689, ()),
            (EtherPtpsi0, 671, ()),
            (EtherPtpsi1, 672, ()),
            (EtherRmpi0, 690, ()),
            (EtherRmpi1, 691, ()),
            (EtherSwsi, 674, ()),
            (EtherTsdi0, 686, ()),
            (EtherTsdi1, 687, ()),
            (FpuExc, 101, ()),
            (GlcdcLineDetect, 898, ()),
            (GlcdcUnderflow1, 899, ()),
            (GlcdcUnderflow2, 900, ()),
            (Gpt0CaptureCompareA, 385, ()),
            (Gpt0CaptureCompareB, 386, ()),
            (Gpt0CompareC, 387, ()),
            (Gpt0CompareD, 388, ()),
            (Gpt0CompareE, 389, ()),
            (Gpt0CompareF, 390, ()),
            (Gpt0CounterOverflow, 391, ()),
            (Gpt0CounterUnderflow, 392, ()),
            (Gpt0Pc, 393, ()),
            (Gpt10CaptureCompareA, 475, ()),
            (Gpt10CaptureCompareB, 476, ()),
            (Gpt10CompareC, 477, ()),
            (Gpt10CompareD, 478, ()),
            (Gpt10CompareE, 479, ()),
            (Gpt10CompareF, 480, ()),
            (Gpt10CounterOverflow, 481, ()),
            (Gpt10CounterUnderflow, 482, ()),
            (Gpt10Pc, 483, ()),
            (Gpt11CaptureCompareA, 484, ()),
            (Gpt11CaptureCompareB, 485, ()),
            (Gpt11CompareC, 486, ()),
            (Gpt11CompareD, 487, ()),
            (Gpt11CompareE, 488, ()),
            (Gpt11CompareF, 489, ()),
            (Gpt11CounterOverflow, 490, ()),
            (Gpt11CounterUnderflow, 491, ()),
            (Gpt11Pc, 492, ()),
            (Gpt12CaptureCompareA, 493, ()),
            (Gpt12CaptureCompareB, 494, ()),
            (Gpt12CompareC, 495, ()),
            (Gpt12CompareD, 496, ()),
            (Gpt12CompareE, 497, ()),
            (Gpt12CompareF, 498, ()),
            (Gpt12CounterOverflow, 499, ()),
            (Gpt12CounterUnderflow, 500, ()),
            (Gpt12Pc, 501, ()),
            (Gpt13CaptureCompareA, 502, ()),
            (Gpt13CaptureCompareB, 503, ()),
            (Gpt13CompareC, 504, ()),
            (Gpt13CompareD, 505, ()),
            (Gpt13CompareE, 506, ()),
            (Gpt13CompareF, 507, ()),
            (Gpt13CounterOverflow, 508, ()),
            (Gpt13CounterUnderflow, 509, ()),
            (Gpt13Pc, 510, ()),
            (Gpt1CaptureCompareA, 394, ()),
            (Gpt1CaptureCompareB, 395, ()),
            (Gpt1CompareC, 396, ()),
            (Gpt1CompareD, 397, ()),
            (Gpt1CompareE, 398, ()),
            (Gpt1CompareF, 399, ()),
            (Gpt1CounterOverflow, 400, ()),
            (Gpt1CounterUnderflow, 401, ()),
            (Gpt1Pc, 402, ()),
            (Gpt2CaptureCompareA, 403, ()),
            (Gpt2CaptureCompareB, 404, ()),
            (Gpt2CompareC, 405, ()),
            (Gpt2CompareD, 406, ()),
            (Gpt2CompareE, 407, ()),
            (Gpt2CompareF, 408, ()),
            (Gpt2CounterOverflow, 409, ()),
            (Gpt2CounterUnderflow, 410, ()),
            (Gpt2Pc, 411, ()),
            (Gpt3CaptureCompareA, 412, ()),
            (Gpt3CaptureCompareB, 413, ()),
            (Gpt3CompareC, 414, ()),
            (Gpt3CompareD, 415, ()),
            (Gpt3CompareE, 416, ()),
            (Gpt3CompareF, 417, ()),
            (Gpt3CounterOverflow, 418, ()),
            (Gpt3CounterUnderflow, 419, ()),
            (Gpt3Pc, 420, ()),
            (Gpt4CaptureCompareA, 421, ()),
            (Gpt4CaptureCompareB, 422, ()),
            (Gpt4CompareC, 423, ()),
            (Gpt4CompareD, 424, ()),
            (Gpt4CompareE, 425, ()),
            (Gpt4CompareF, 426, ()),
            (Gpt4CounterOverflow, 427, ()),
            (Gpt4CounterUnderflow, 428, ()),
            (Gpt5CaptureCompareA, 430, ()),
            (Gpt5CaptureCompareB, 431, ()),
            (Gpt5CompareC, 432, ()),
            (Gpt5CompareD, 433, ()),
            (Gpt5CompareE, 434, ()),
            (Gpt5CompareF, 435, ()),
            (Gpt5CounterOverflow, 436, ()),
            (Gpt5CounterUnderflow, 437, ()),
            (Gpt6CaptureCompareA, 439, ()),
            (Gpt6CaptureCompareB, 440, ()),
            (Gpt6CompareC, 441, ()),
            (Gpt6CompareD, 442, ()),
            (Gpt6CompareE, 443, ()),
            (Gpt6CompareF, 444, ()),
            (Gpt6CounterOverflow, 445, ()),
            (Gpt6CounterUnderflow, 446, ()),
            (Gpt7CaptureCompareA, 448, ()),
            (Gpt7CaptureCompareB, 449, ()),
            (Gpt7CompareC, 450, ()),
            (Gpt7CompareD, 451, ()),
            (Gpt7CompareE, 452, ()),
            (Gpt7CompareF, 453, ()),
            (Gpt7CounterOverflow, 454, ()),
            (Gpt7CounterUnderflow, 455, ()),
            (Gpt8CaptureCompareA, 457, ()),
            (Gpt8CaptureCompareB, 458, ()),
            (Gpt8CompareC, 459, ()),
            (Gpt8CompareD, 460, ()),
            (Gpt8CompareE, 461, ()),
            (Gpt8CompareF, 462, ()),
            (Gpt8CounterOverflow, 463, ()),
            (Gpt8CounterUnderflow, 464, ()),
            (Gpt9CaptureCompareA, 466, ()),
            (Gpt9CaptureCompareB, 467, ()),
            (Gpt9CompareC, 468, ()),
            (Gpt9CompareD, 469, ()),
            (Gpt9CompareE, 470, ()),
            (Gpt9CompareF, 471, ()),
            (Gpt9CounterOverflow, 472, ()),
            (Gpt9CounterUnderflow, 473, ()),
            (Gptp0Match, 696, ()),
            (Gptp1Match, 697, ()),
            (GptpPtpout0, 692, ()),
            (GptpPtpout1, 693, ()),
            (GptpPtpout2, 694, ()),
            (GptpPtpout3, 695, ()),
            (I3c0Amev, 841, ()),
            (I3c0Command, 827, ()),
            (I3c0Eei, 837, ()),
            (I3c0Hcmd, 833, ()),
            (I3c0Hresp, 832, ()),
            (I3c0Hrx, 834, ()),
            (I3c0Htx, 835, ()),
            (I3c0Ibi, 828, ()),
            (I3c0Mrefcpt, 840, ()),
            (I3c0Mrefovf, 839, ()),
            (I3c0RcvStatus, 831, ()),
            (I3c0Response, 826, ()),
            (I3c0Rx, 829, ()),
            (I3c0Stev, 838, ()),
            (I3c0Tend, 836, ()),
            (I3c0Tx, 830, ()),
            (I3c0Wu, 842, ()),
            (IcuIrq0, 1, ()),
            (IcuIrq1, 2, ()),
            (IcuIrq10, 11, ()),
            (IcuIrq11, 12, ()),
            (IcuIrq12, 13, ()),
            (IcuIrq13, 14, ()),
            (IcuIrq14, 15, ()),
            (IcuIrq15, 16, ()),
            (IcuIrq16, 17, ()),
            (IcuIrq17, 18, ()),
            (IcuIrq18, 19, ()),
            (IcuIrq19, 20, ()),
            (IcuIrq2, 3, ()),
            (IcuIrq20, 21, ()),
            (IcuIrq21, 22, ()),
            (IcuIrq22, 23, ()),
            (IcuIrq23, 24, ()),
            (IcuIrq24, 25, ()),
            (IcuIrq25, 26, ()),
            (IcuIrq26, 27, ()),
            (IcuIrq27, 28, ()),
            (IcuIrq28, 29, ()),
            (IcuIrq29, 30, ()),
            (IcuIrq3, 4, ()),
            (IcuIrq30, 31, ()),
            (IcuIrq31, 32, ()),
            (IcuIrq4, 5, ()),
            (IcuIrq5, 6, ()),
            (IcuIrq6, 7, ()),
            (IcuIrq7, 8, ()),
            (IcuIrq8, 9, ()),
            (IcuIrq9, 10, ()),
            (Iic0Eri, 159, ()),
            (Iic0Rxi, 156, ()),
            (Iic0Tei, 158, ()),
            (Iic0Txi, 157, ()),
            (Iic0Wui, 160, ()),
            (Iic1Eri, 164, ()),
            (Iic1Rxi, 161, ()),
            (Iic1Tei, 163, ()),
            (Iic1Txi, 162, ()),
            (Iic2Eri, 169, ()),
            (Iic2Rxi, 166, ()),
            (Iic2Tei, 168, ()),
            (Iic2Txi, 167, ()),
            (Iicb0Eri, 837, ()),
            (Iicb0Rxi, 829, ()),
            (Iicb0Tei, 836, ()),
            (Iicb0Txi, 830, ()),
            (IoportEvent1, 208, ()),
            (IoportEvent2, 209, ()),
            (IoportEvent3, 210, ()),
            (IoportEvent4, 211, ()),
            (IpcIrq0, 91, ()),
            (IpcIrq1, 92, ()),
            (IwdtUnderflow, 146, ()),
            (Lm0Err, 95, ()),
            (Lm1Err, 96, ()),
            (LvdLvd1, 112, ()),
            (LvdLvd2, 113, ()),
            (MipicsiDl, 912, ()),
            (MipicsiGst, 915, ()),
            (MipicsiPm, 914, ()),
            (MipicsiRx, 911, ()),
            (MipicsiVc, 913, ()),
            (MipidsiFerr, 908, ()),
            (MipidsiPpi, 909, ()),
            (MipidsiRcv, 907, ()),
            (MipidsiSeq0, 904, ()),
            (MipidsiSeq1, 905, ()),
            (MipidsiVin1, 906, ()),
            (MramEndofpe, 109, ()),
            (MramMrcpr, 107, ()),
            (MramMrcrd, 104, ()),
            (MramMrepr, 108, ()),
            (MramMrerd, 105, ()),
            (NpuIrq, 103, ()),
            (OpsUvwEdge, 384, ()),
            (PdmDat0, 191, ()),
            (PdmDat1, 192, ()),
            (PdmDat2, 193, ()),
            (PdmErr0, 195, ()),
            (PdmErr1, 196, ()),
            (PdmErr2, 197, ()),
            (PdmSdet, 194, ()),
            (Poeg0Event, 215, ()),
            (Poeg1Event, 216, ()),
            (Poeg2Event, 217, ()),
            (Poeg3Event, 218, ()),
            (RsipTadi, 881, ()),
            (RtcAlarm, 149, ()),
            (RtcCarry, 151, ()),
            (RtcPeriod, 150, ()),
            (Sci0Aed, 712, ()),
            (Sci0Am, 714, ()),
            (Sci0Bfd, 713, ()),
            (Sci0Eri, 711, ()),
            (Sci0Rxi, 708, ()),
            (Sci0Tei, 710, ()),
            (Sci0Txi, 709, ()),
            (Sci10Aed, 782, ()),
            (Sci10Am, 784, ()),
            (Sci10Bfd, 783, ()),
            (Sci10Eri, 781, ()),
            (Sci10Rxi, 778, ()),
            (Sci10Tei, 780, ()),
            (Sci10Txi, 779, ()),
            (Sci11Aed, 789, ()),
            (Sci11Am, 791, ()),
            (Sci11Bfd, 790, ()),
            (Sci11Eri, 788, ()),
            (Sci11Rxi, 785, ()),
            (Sci11Tei, 787, ()),
            (Sci11Txi, 786, ()),
            (Sci1Aed, 719, ()),
            (Sci1Am, 721, ()),
            (Sci1Bfd, 720, ()),
            (Sci1Eri, 718, ()),
            (Sci1Rxi, 715, ()),
            (Sci1Tei, 717, ()),
            (Sci1Txi, 716, ()),
            (Sci2Aed, 726, ()),
            (Sci2Am, 728, ()),
            (Sci2Bfd, 727, ()),
            (Sci2Eri, 725, ()),
            (Sci2Rxi, 722, ()),
            (Sci2Tei, 724, ()),
            (Sci2Txi, 723, ()),
            (Sci3Aed, 733, ()),
            (Sci3Am, 735, ()),
            (Sci3Bfd, 734, ()),
            (Sci3Eri, 732, ()),
            (Sci3Rxi, 729, ()),
            (Sci3Tei, 731, ()),
            (Sci3Txi, 730, ()),
            (Sci4Aed, 740, ()),
            (Sci4Am, 742, ()),
            (Sci4Bfd, 741, ()),
            (Sci4Eri, 739, ()),
            (Sci4Rxi, 736, ()),
            (Sci4Tei, 738, ()),
            (Sci4Txi, 737, ()),
            (Sci5Aed, 747, ()),
            (Sci5Am, 749, ()),
            (Sci5Bfd, 748, ()),
            (Sci5Eri, 746, ()),
            (Sci5Rxi, 743, ()),
            (Sci5Tei, 745, ()),
            (Sci5Txi, 744, ()),
            (Sci6Aed, 754, ()),
            (Sci6Am, 756, ()),
            (Sci6Bfd, 755, ()),
            (Sci6Eri, 753, ()),
            (Sci6Rxi, 750, ()),
            (Sci6Tei, 752, ()),
            (Sci6Txi, 751, ()),
            (Sci7Aed, 761, ()),
            (Sci7Am, 763, ()),
            (Sci7Bfd, 762, ()),
            (Sci7Eri, 760, ()),
            (Sci7Rxi, 757, ()),
            (Sci7Tei, 759, ()),
            (Sci7Txi, 758, ()),
            (Sci8Aed, 768, ()),
            (Sci8Am, 770, ()),
            (Sci8Bfd, 769, ()),
            (Sci8Eri, 767, ()),
            (Sci8Rxi, 764, ()),
            (Sci8Tei, 766, ()),
            (Sci8Txi, 765, ()),
            (Sci9Aed, 775, ()),
            (Sci9Am, 777, ()),
            (Sci9Bfd, 776, ()),
            (Sci9Eri, 774, ()),
            (Sci9Rxi, 771, ()),
            (Sci9Tei, 773, ()),
            (Sci9Txi, 772, ()),
            (Sdhimmc0Accs, 171, ()),
            (Sdhimmc0Card, 173, ()),
            (Sdhimmc0DmaReq, 174, ()),
            (Sdhimmc0Sdio, 172, ()),
            (Sdhimmc1Accs, 175, ()),
            (Sdhimmc1Card, 177, ()),
            (Sdhimmc1DmaReq, 178, ()),
            (Sdhimmc1Sdio, 176, ()),
            (Spi0Eri, 795, ()),
            (Spi0Idle, 794, ()),
            (Spi0Rxi, 792, ()),
            (Spi0Tei, 796, ()),
            (Spi0Txi, 793, ()),
            (Spi1Eri, 800, ()),
            (Spi1Idle, 799, ()),
            (Spi1Rxi, 797, ()),
            (Spi1Tei, 801, ()),
            (Spi1Txi, 798, ()),
            (Ssi0Int, 182, ()),
            (Ssi0Rxi, 180, ()),
            (Ssi0Txi, 179, ()),
            (Ssi1Int, 186, ()),
            (Ssi1Rxi, 185, ()),
            (Ssi1Txi, 185, ()),
            (Ulpt0CompareA, 129, ()),
            (Ulpt0CompareB, 130, ()),
            (Ulpt0Int, 128, ()),
            (Ulpt1CompareA, 132, ()),
            (Ulpt1CompareB, 133, ()),
            (Ulpt1Int, 131, ()),
            (UsbfsFifo0, 152, ()),
            (UsbfsFifo1, 153, ()),
            (UsbfsInt, 154, ()),
            (UsbfsResume, 155, ()),
            (UsbhsFifo0, 705, ()),
            (UsbhsFifo1, 706, ()),
            (UsbhsUsbIntResume, 707, ()),
            (VbattTadi, 117, ()),
            (VinErr, 918, ()),
            (VinIrq, 917, ()),
            (Wdt0Underflow, 147, ()),
            (Wdt1Underflow, 148, ()),
            (Xspi1Cmp, 190, ()),
            (Xspi1Err, 189, ()),
            (XspiCmp, 188, ()),
            (XspiErr, 187, ()),
        }
    };
}
#[macro_export]
macro_rules! foreach_peripheral {
    ($m:path) => {
        $m! {
            AGT0 = 0,
            AGT1 = 1,
            GPT0 = 2,
            GPT1 = 3,
            GPT2 = 4,
            GPT3 = 5,
            GPT4 = 6,
            GPT5 = 7,
            GPT6 = 8,
            GPT7 = 9,
            GPT8 = 10,
            GPT9 = 11,
            GPT10 = 12,
            GPT11 = 13,
            GPT12 = 14,
            GPT13 = 15,
            ICU = 16,
            ICU = 17,
            MSTP = 18,
            PFS = 19,
            PORT0 = 20,
            PORT1 = 21,
            PORT2 = 22,
            PORT3 = 23,
            PORT4 = 24,
            PORT5 = 25,
            PORT6 = 26,
            PORT7 = 27,
            PORT8 = 28,
            PORT9 = 29,
            SYSC = 30,
        }
    };
}
#[macro_export]
macro_rules! foreach_pin {
    ($m:path) => {
        $m! {
            (P000, 0, 0),
            (P001, 0, 1),
            (P002, 0, 2),
            (P003, 0, 3),
            (P004, 0, 4),
            (P005, 0, 5),
            (P006, 0, 6),
            (P007, 0, 7),
            (P008, 0, 8),
            (P009, 0, 9),
            (P010, 0, 10),
            (P011, 0, 11),
            (P012, 0, 12),
            (P013, 0, 13),
            (P014, 0, 14),
            (P015, 0, 15),
            (P100, 1, 0),
            (P101, 1, 1),
            (P102, 1, 2),
            (P103, 1, 3),
            (P104, 1, 4),
            (P105, 1, 5),
            (P106, 1, 6),
            (P107, 1, 7),
            (P108, 1, 8),
            (P109, 1, 9),
            (P110, 1, 10),
            (P111, 1, 11),
            (P112, 1, 12),
            (P113, 1, 13),
            (P114, 1, 14),
            (P115, 1, 15),
            (P200, 2, 0),
            (P201, 2, 1),
            (P202, 2, 2),
            (P203, 2, 3),
            (P204, 2, 4),
            (P205, 2, 5),
            (P206, 2, 6),
            (P207, 2, 7),
            (P208, 2, 8),
            (P209, 2, 9),
            (P210, 2, 10),
            (P211, 2, 11),
            (P212, 2, 12),
            (P213, 2, 13),
            (P214, 2, 14),
            (P215, 2, 15),
            (P300, 3, 0),
            (P301, 3, 1),
            (P302, 3, 2),
            (P303, 3, 3),
            (P304, 3, 4),
            (P305, 3, 5),
            (P306, 3, 6),
            (P307, 3, 7),
            (P308, 3, 8),
            (P309, 3, 9),
            (P310, 3, 10),
            (P311, 3, 11),
            (P312, 3, 12),
            (P313, 3, 13),
            (P314, 3, 14),
            (P315, 3, 15),
            (P400, 4, 0),
            (P401, 4, 1),
            (P402, 4, 2),
            (P403, 4, 3),
            (P404, 4, 4),
            (P405, 4, 5),
            (P406, 4, 6),
            (P407, 4, 7),
            (P408, 4, 8),
            (P409, 4, 9),
            (P410, 4, 10),
            (P411, 4, 11),
            (P412, 4, 12),
            (P413, 4, 13),
            (P414, 4, 14),
            (P415, 4, 15),
            (P500, 5, 0),
            (P501, 5, 1),
            (P502, 5, 2),
            (P503, 5, 3),
            (P504, 5, 4),
            (P505, 5, 5),
            (P506, 5, 6),
            (P507, 5, 7),
            (P508, 5, 8),
            (P509, 5, 9),
            (P510, 5, 10),
            (P511, 5, 11),
            (P512, 5, 12),
            (P513, 5, 13),
            (P514, 5, 14),
            (P515, 5, 15),
            (P600, 6, 0),
            (P601, 6, 1),
            (P602, 6, 2),
            (P603, 6, 3),
            (P604, 6, 4),
            (P605, 6, 5),
            (P606, 6, 6),
            (P607, 6, 7),
            (P608, 6, 8),
            (P609, 6, 9),
            (P610, 6, 10),
            (P611, 6, 11),
            (P612, 6, 12),
            (P613, 6, 13),
            (P614, 6, 14),
            (P615, 6, 15),
            (P700, 7, 0),
            (P701, 7, 1),
            (P702, 7, 2),
            (P703, 7, 3),
            (P704, 7, 4),
            (P705, 7, 5),
            (P706, 7, 6),
            (P707, 7, 7),
            (P708, 7, 8),
            (P709, 7, 9),
            (P710, 7, 10),
            (P711, 7, 11),
            (P712, 7, 12),
            (P713, 7, 13),
            (P714, 7, 14),
            (P715, 7, 15),
            (P800, 8, 0),
            (P801, 8, 1),
            (P802, 8, 2),
            (P803, 8, 3),
            (P804, 8, 4),
            (P805, 8, 5),
            (P806, 8, 6),
            (P807, 8, 7),
            (P808, 8, 8),
            (P809, 8, 9),
            (P810, 8, 10),
            (P811, 8, 11),
            (P812, 8, 12),
            (P813, 8, 13),
            (P814, 8, 14),
            (P815, 8, 15),
            (P900, 9, 0),
            (P901, 9, 1),
            (P902, 9, 2),
            (P903, 9, 3),
            (P904, 9, 4),
            (P905, 9, 5),
            (P906, 9, 6),
            (P907, 9, 7),
            (P908, 9, 8),
            (P909, 9, 9),
            (P910, 9, 10),
            (P911, 9, 11),
            (P912, 9, 12),
            (P913, 9, 13),
            (P914, 9, 14),
            (P915, 9, 15),
        }
    };
}
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Event {
    /// High Speed Comparator channel 0 interrupt
    Acmphs0Int = 198,
    /// High Speed Comparator channel 1 interrupt
    Acmphs1Int = 199,
    /// High Speed Comparator channel 2 interrupt
    Acmphs2Int = 200,
    /// High Speed Comparator channel 3 interrupt
    Acmphs3Int = 201,
    /// End of A/D scanning operation(Gr.0)
    AdcAdi0 = 845,
    /// End of A/D scanning operation(Gr.1)
    AdcAdi1 = 846,
    /// End of A/D scanning operation(Gr.2)
    AdcAdi2 = 847,
    /// End of A/D scanning operation(Gr.3)
    AdcAdi3 = 848,
    /// End of A/D scanning operation(Gr.4)
    AdcAdi4 = 849,
    /// End of A/D scanning operation(Gr.5)
    AdcAdi5 = 850,
    /// End of A/D scanning operation(Gr.6)
    AdcAdi6 = 851,
    /// End of A/D scanning operation(Gr.7)
    AdcAdi7 = 852,
    /// End of A/D scanning operation(Gr.8)
    AdcAdi8 = 853,
    /// End of calibration of A/D converter unit 0
    AdcCalend0 = 870,
    /// End of calibration of A/D converter unit 1
    AdcCalend1 = 878,
    /// Calibration request unit 0
    AdcCalreq0 = 869,
    /// Calibration request unit 1
    AdcCalreq1 = 877,
    /// Composite compare match 0
    AdcCcmpm0 = 865,
    /// Composite compare match 1
    AdcCcmpm1 = 873,
    /// Composite condition compare mismatch 0
    AdcCcmpum0 = 866,
    /// Composite condition compare mismatch 1
    AdcCcmpum1 = 874,
    /// Compare match interrupt with compare table 0
    AdcCmpi0 = 863,
    /// Compare match interrupt with compare table 1
    AdcCmpi1 = 864,
    /// Compare match interrupt with compare table 2
    AdcCmpi2 = 871,
    /// Compare match interrupt with compare table 3
    AdcCmpi3 = 872,
    /// A/D converter unit 0 Error
    AdcErr0 = 867,
    /// A/D converter unit 1 Error
    AdcErr1 = 875,
    /// FIFO data overflow
    AdcFifoovf = 844,
    /// FIFO data read request interrupt(Gr.0)
    AdcFiforeq0 = 854,
    /// FIFO data read request interrupt(Gr.1)
    AdcFiforeq1 = 855,
    /// FIFO data read request interrupt(Gr.2)
    AdcFiforeq2 = 856,
    /// FIFO data read request interrupt(Gr.3)
    AdcFiforeq3 = 857,
    /// FIFO data read request interrupt(Gr.4)
    AdcFiforeq4 = 858,
    /// FIFO data read request interrupt(Gr.5)
    AdcFiforeq5 = 859,
    /// FIFO data read request interrupt(Gr.6)
    AdcFiforeq6 = 860,
    /// FIFO data read request interrupt(Gr.7)
    AdcFiforeq7 = 861,
    /// FIFO data read request interrupt(Gr.8)
    AdcFiforeq8 = 862,
    /// Limiter clip interrupt with the limit table 0 to 7
    AdcLimclpi = 843,
    /// A/D conversion overflow on A/D converter unit 0
    AdcResovf0 = 868,
    /// A/D conversion overflow on A/D converter unit 1
    AdcResovf1 = 876,
    /// Compare match A
    Agt0CompareA = 135,
    /// Compare match B
    Agt0CompareB = 136,
    /// AGT interrupt
    Agt0Int = 134,
    /// Compare match A
    Agt1CompareA = 138,
    /// Compare match B
    Agt1CompareB = 139,
    /// AGT interrupt
    Agt1Int = 137,
    /// BUS error
    BusErr = 99,
    /// Frequency error interrupt
    CacFrequencyError = 212,
    /// Measurement end interrupt
    CacMeasurementEnd = 213,
    /// Overflow interrupt
    CacOverflow = 214,
    /// Channel  DMA request
    Can0CfDmareq = 815,
    /// Channel  error
    Can0Cherr = 813,
    /// Common FIFO receive interrupt
    Can0Comfrx = 814,
    /// RX fifo DMA request 0
    Can0Dmareq0 = 804,
    /// RX fifo DMA request 1
    Can0Dmareq1 = 805,
    /// CANFD0 ECC error
    Can0MramEri = 824,
    /// Receive message buffer interrupt
    Can0Rxmb = 816,
    /// Transmit interrupt
    Can0Tx = 812,
    /// Channel  DMA request
    Can1CfDmareq = 820,
    /// Channel  error
    Can1Cherr = 818,
    /// Common FIFO receive interrupt
    Can1Comfrx = 819,
    /// RX fifo DMA request 0
    Can1Dmareq0 = 808,
    /// RX fifo DMA request 1
    Can1Dmareq1 = 809,
    /// CANFD1 ECC error
    Can1MramEri = 825,
    /// Receive message buffer interrupt
    Can1Rxmb = 821,
    /// Transmit interrupt
    Can1Tx = 817,
    /// Global error
    CanGlerr = 803,
    /// Global receive FIFO interrupt
    CanRxf = 802,
    /// CEU interrupt
    CeuCeui = 919,
    /// Main Clock oscillation stop
    CgcMoscStop = 118,
    /// Sub oscillation stop
    CgcSoscStop = 119,
    /// Common memory error
    CmErr = 100,
    /// CPU 0 lockup
    Cpu0Lockup = 97,
    /// CPU 1 lockup
    Cpu1Lockup = 98,
    /// Coresight Crosstrigger Event
    DbgCtiirq0 = 88,
    /// Coresight Crosstrigger Event
    DbgCtiirq1 = 89,
    /// JB RXI
    DbgJbrxi = 90,
    /// DMA1/DTC1 transfer error
    Dma1Transerr = 87,
    /// DMAC0 transfer end
    Dmac0Int = 64,
    /// DMAC10 transfer end
    Dmac10Int = 72,
    /// DMAC11 transfer end
    Dmac11Int = 73,
    /// DMAC12 transfer end
    Dmac12Int = 74,
    /// DMAC13 transfer end
    Dmac13Int = 75,
    /// DMAC14 transfer end
    Dmac14Int = 76,
    /// DMAC15 transfer end
    Dmac15Int = 77,
    /// DMAC16 transfer end
    Dmac16Int = 78,
    /// DMAC17 transfer end
    Dmac17Int = 79,
    /// DMAC1 transfer end
    Dmac1Int = 65,
    /// DMAC2 transfer end
    Dmac2Int = 66,
    /// DMAC3 transfer end
    Dmac3Int = 67,
    /// DMAC4 transfer end
    Dmac4Int = 68,
    /// DMAC5 transfer end
    Dmac5Int = 69,
    /// DMAC6 transfer end
    Dmac6Int = 70,
    /// DMAC7 transfer end
    Dmac7Int = 71,
    /// DMA/DTC transfer error
    DmaTranserr = 86,
    /// Data operation circuit interrupt
    DocInt = 879,
    /// DRW interrupt
    DrwInt = 901,
    /// DTC1 transfer end
    Dtc1End = 85,
    /// DTC transfer end
    DtcEnd = 82,
    /// Software event 0
    ElcSoftwareEvent0 = 204,
    /// Software event 1
    ElcSoftwareEvent1 = 205,
    /// Software event 2
    ElcSoftwareEvent2 = 206,
    /// Software event 3
    ElcSoftwareEvent3 = 207,
    /// Common Error Interrupt
    EtherCaei = 667,
    /// Common Status Interrupt
    EtherCami = 675,
    /// ETHA0 Error Interrupt
    EtherEaei0 = 669,
    /// ETHA1 Error Interrupt
    EtherEaei1 = 670,
    /// ETHA0 Status Interrupt
    EtherEasi0 = 676,
    /// ETHA1 Status Interrupt
    EtherEasi1 = 677,
    /// Forwarding Error Interrupt
    EtherFwei = 666,
    /// Forwarding Status Interrupt
    EtherFwsi = 673,
    /// GWCA Data Interrupt 0
    EtherGwdi0 = 678,
    /// GWCA Data Interrupt 1
    EtherGwdi1 = 679,
    /// GWCA Data Interrupt 2
    EtherGwdi2 = 680,
    /// GWCA Data Interrupt 3
    EtherGwdi3 = 681,
    /// GWCA Data Interrupt 4
    EtherGwdi4 = 682,
    /// GWCA Data Interrupt 5
    EtherGwdi5 = 683,
    /// GWCA Data Interrupt 6
    EtherGwdi6 = 684,
    /// GWCA Data Interrupt 7
    EtherGwdi7 = 685,
    /// GWCA0 Error Interrupt
    EtherGwei = 668,
    /// MDIO Interrupt 0
    EtherMdio0 = 688,
    /// MDIO Interrupt 1
    EtherMdio1 = 689,
    /// gPTP Status Interrupt 0
    EtherPtpsi0 = 671,
    /// gPTP Status Interrupt 1
    EtherPtpsi1 = 672,
    /// RMAC0 PHY Interrupt
    EtherRmpi0 = 690,
    /// RMAC1 PHY Interrupt
    EtherRmpi1 = 691,
    /// Switch Status Interrupt
    EtherSwsi = 674,
    /// Time Stamp Data Interrupt 0
    EtherTsdi0 = 686,
    /// Time Stamp Data Interrupt 1
    EtherTsdi1 = 687,
    /// FPU exception
    FpuExc = 101,
    /// Specified line
    GlcdcLineDetect = 898,
    /// Graphic 1 underflow
    GlcdcUnderflow1 = 899,
    /// Graphic 2 underflow
    GlcdcUnderflow2 = 900,
    /// Capture/Compare match A
    Gpt0CaptureCompareA = 385,
    /// Capture/Compare match B
    Gpt0CaptureCompareB = 386,
    /// Compare match C
    Gpt0CompareC = 387,
    /// Compare match D
    Gpt0CompareD = 388,
    /// Compare match E
    Gpt0CompareE = 389,
    /// Compare match F
    Gpt0CompareF = 390,
    /// Overflow
    Gpt0CounterOverflow = 391,
    /// Underflow
    Gpt0CounterUnderflow = 392,
    /// Period count function finish
    Gpt0Pc = 393,
    /// Capture/Compare match A
    Gpt10CaptureCompareA = 475,
    /// Capture/Compare match B
    Gpt10CaptureCompareB = 476,
    /// Compare match C
    Gpt10CompareC = 477,
    /// Compare match D
    Gpt10CompareD = 478,
    /// Compare match E
    Gpt10CompareE = 479,
    /// Compare match F
    Gpt10CompareF = 480,
    /// Overflow
    Gpt10CounterOverflow = 481,
    /// Underflow
    Gpt10CounterUnderflow = 482,
    /// Period count function finish
    Gpt10Pc = 483,
    /// Capture/Compare match A
    Gpt11CaptureCompareA = 484,
    /// Capture/Compare match B
    Gpt11CaptureCompareB = 485,
    /// Compare match C
    Gpt11CompareC = 486,
    /// Compare match D
    Gpt11CompareD = 487,
    /// Compare match E
    Gpt11CompareE = 488,
    /// Compare match F
    Gpt11CompareF = 489,
    /// Overflow
    Gpt11CounterOverflow = 490,
    /// Underflow
    Gpt11CounterUnderflow = 491,
    /// Period count function finish
    Gpt11Pc = 492,
    /// Capture/Compare match A
    Gpt12CaptureCompareA = 493,
    /// Capture/Compare match B
    Gpt12CaptureCompareB = 494,
    /// Compare match C
    Gpt12CompareC = 495,
    /// Compare match D
    Gpt12CompareD = 496,
    /// Compare match E
    Gpt12CompareE = 497,
    /// Compare match F
    Gpt12CompareF = 498,
    /// Overflow
    Gpt12CounterOverflow = 499,
    /// Underflow
    Gpt12CounterUnderflow = 500,
    /// Period count function finish
    Gpt12Pc = 501,
    /// Capture/Compare match A
    Gpt13CaptureCompareA = 502,
    /// Capture/Compare match B
    Gpt13CaptureCompareB = 503,
    /// Compare match C
    Gpt13CompareC = 504,
    /// Compare match D
    Gpt13CompareD = 505,
    /// Compare match E
    Gpt13CompareE = 506,
    /// Compare match F
    Gpt13CompareF = 507,
    /// Overflow
    Gpt13CounterOverflow = 508,
    /// Underflow
    Gpt13CounterUnderflow = 509,
    /// Period count function finish
    Gpt13Pc = 510,
    /// Capture/Compare match A
    Gpt1CaptureCompareA = 394,
    /// Capture/Compare match B
    Gpt1CaptureCompareB = 395,
    /// Compare match C
    Gpt1CompareC = 396,
    /// Compare match D
    Gpt1CompareD = 397,
    /// Compare match E
    Gpt1CompareE = 398,
    /// Compare match F
    Gpt1CompareF = 399,
    /// Overflow
    Gpt1CounterOverflow = 400,
    /// Underflow
    Gpt1CounterUnderflow = 401,
    /// Period count function finish
    Gpt1Pc = 402,
    /// Capture/Compare match A
    Gpt2CaptureCompareA = 403,
    /// Capture/Compare match B
    Gpt2CaptureCompareB = 404,
    /// Compare match C
    Gpt2CompareC = 405,
    /// Compare match D
    Gpt2CompareD = 406,
    /// Compare match E
    Gpt2CompareE = 407,
    /// Compare match F
    Gpt2CompareF = 408,
    /// Overflow
    Gpt2CounterOverflow = 409,
    /// Underflow
    Gpt2CounterUnderflow = 410,
    /// Period count function finish
    Gpt2Pc = 411,
    /// Capture/Compare match A
    Gpt3CaptureCompareA = 412,
    /// Capture/Compare match B
    Gpt3CaptureCompareB = 413,
    /// Compare match C
    Gpt3CompareC = 414,
    /// Compare match D
    Gpt3CompareD = 415,
    /// Compare match E
    Gpt3CompareE = 416,
    /// Compare match F
    Gpt3CompareF = 417,
    /// Overflow
    Gpt3CounterOverflow = 418,
    /// Underflow
    Gpt3CounterUnderflow = 419,
    /// Period count function finish
    Gpt3Pc = 420,
    /// Capture/Compare match A
    Gpt4CaptureCompareA = 421,
    /// Capture/Compare match B
    Gpt4CaptureCompareB = 422,
    /// Compare match C
    Gpt4CompareC = 423,
    /// Compare match D
    Gpt4CompareD = 424,
    /// Compare match E
    Gpt4CompareE = 425,
    /// Compare match F
    Gpt4CompareF = 426,
    /// Overflow
    Gpt4CounterOverflow = 427,
    /// Underflow
    Gpt4CounterUnderflow = 428,
    /// Capture/Compare match A
    Gpt5CaptureCompareA = 430,
    /// Capture/Compare match B
    Gpt5CaptureCompareB = 431,
    /// Compare match C
    Gpt5CompareC = 432,
    /// Compare match D
    Gpt5CompareD = 433,
    /// Compare match E
    Gpt5CompareE = 434,
    /// Compare match F
    Gpt5CompareF = 435,
    /// Overflow
    Gpt5CounterOverflow = 436,
    /// Underflow
    Gpt5CounterUnderflow = 437,
    /// Capture/Compare match A
    Gpt6CaptureCompareA = 439,
    /// Capture/Compare match B
    Gpt6CaptureCompareB = 440,
    /// Compare match C
    Gpt6CompareC = 441,
    /// Compare match D
    Gpt6CompareD = 442,
    /// Compare match E
    Gpt6CompareE = 443,
    /// Compare match F
    Gpt6CompareF = 444,
    /// Overflow
    Gpt6CounterOverflow = 445,
    /// Underflow
    Gpt6CounterUnderflow = 446,
    /// Capture/Compare match A
    Gpt7CaptureCompareA = 448,
    /// Capture/Compare match B
    Gpt7CaptureCompareB = 449,
    /// Compare match C
    Gpt7CompareC = 450,
    /// Compare match D
    Gpt7CompareD = 451,
    /// Compare match E
    Gpt7CompareE = 452,
    /// Compare match F
    Gpt7CompareF = 453,
    /// Overflow
    Gpt7CounterOverflow = 454,
    /// Underflow
    Gpt7CounterUnderflow = 455,
    /// Capture/Compare match A
    Gpt8CaptureCompareA = 457,
    /// Capture/Compare match B
    Gpt8CaptureCompareB = 458,
    /// Compare match C
    Gpt8CompareC = 459,
    /// Compare match D
    Gpt8CompareD = 460,
    /// Compare match E
    Gpt8CompareE = 461,
    /// Compare match F
    Gpt8CompareF = 462,
    /// Overflow
    Gpt8CounterOverflow = 463,
    /// Underflow
    Gpt8CounterUnderflow = 464,
    /// Capture/Compare match A
    Gpt9CaptureCompareA = 466,
    /// Capture/Compare match B
    Gpt9CaptureCompareB = 467,
    /// Compare match C
    Gpt9CompareC = 468,
    /// Compare match D
    Gpt9CompareD = 469,
    /// Compare match E
    Gpt9CompareE = 470,
    /// Compare match F
    Gpt9CompareF = 471,
    /// Overflow
    Gpt9CounterOverflow = 472,
    /// Underflow
    Gpt9CounterUnderflow = 473,
    /// Media Clock Recovery Match
    Gptp0Match = 696,
    /// Media Clock Recovery Match
    Gptp1Match = 697,
    /// PTP Pulse Out 0
    GptpPtpout0 = 692,
    /// PTP Pulse Out 1
    GptpPtpout1 = 693,
    /// PTP Pulse Out 2
    GptpPtpout2 = 694,
    /// PTP Pulse Out 3
    GptpPtpout3 = 695,
    /// Additional master-initiated bus event
    I3c0Amev = 841,
    /// Command buffer empty
    I3c0Command = 827,
    /// Error
    I3c0Eei = 837,
    /// High priority command queue empty
    I3c0Hcmd = 833,
    /// High priority response queue full
    I3c0Hresp = 832,
    /// High priority rx data buffer full
    I3c0Hrx = 834,
    /// High priority tx data buffer empty
    I3c0Htx = 835,
    /// IBI status buffer full
    I3c0Ibi = 828,
    /// MREF capture
    I3c0Mrefcpt = 840,
    /// MREF counter overflow
    I3c0Mrefovf = 839,
    /// Receive status buffer full
    I3c0RcvStatus = 831,
    /// Response status buffer full
    I3c0Response = 826,
    /// Receive
    I3c0Rx = 829,
    /// Synchronous timing
    I3c0Stev = 838,
    /// Transmit end
    I3c0Tend = 836,
    /// Transmit
    I3c0Tx = 830,
    /// Wake-up Condition Detection interrupt
    I3c0Wu = 842,
    /// External pin interrupt 0
    IcuIrq0 = 1,
    /// External pin interrupt 1
    IcuIrq1 = 2,
    /// External pin interrupt 10
    IcuIrq10 = 11,
    /// External pin interrupt 11
    IcuIrq11 = 12,
    /// External pin interrupt 12
    IcuIrq12 = 13,
    /// External pin interrupt 13
    IcuIrq13 = 14,
    /// External pin interrupt 14
    IcuIrq14 = 15,
    /// External pin interrupt 15
    IcuIrq15 = 16,
    /// External pin interrupt 16
    IcuIrq16 = 17,
    /// External pin interrupt 17
    IcuIrq17 = 18,
    /// External pin interrupt 18
    IcuIrq18 = 19,
    /// External pin interrupt 19
    IcuIrq19 = 20,
    /// External pin interrupt 2
    IcuIrq2 = 3,
    /// External pin interrupt 20
    IcuIrq20 = 21,
    /// External pin interrupt 21
    IcuIrq21 = 22,
    /// External pin interrupt 22
    IcuIrq22 = 23,
    /// External pin interrupt 23
    IcuIrq23 = 24,
    /// External pin interrupt 24
    IcuIrq24 = 25,
    /// External pin interrupt 25
    IcuIrq25 = 26,
    /// External pin interrupt 26
    IcuIrq26 = 27,
    /// External pin interrupt 27
    IcuIrq27 = 28,
    /// External pin interrupt 28
    IcuIrq28 = 29,
    /// External pin interrupt 29
    IcuIrq29 = 30,
    /// External pin interrupt 3
    IcuIrq3 = 4,
    /// External pin interrupt 30
    IcuIrq30 = 31,
    /// External pin interrupt 31
    IcuIrq31 = 32,
    /// External pin interrupt 4
    IcuIrq4 = 5,
    /// External pin interrupt 5
    IcuIrq5 = 6,
    /// External pin interrupt 6
    IcuIrq6 = 7,
    /// External pin interrupt 7
    IcuIrq7 = 8,
    /// External pin interrupt 8
    IcuIrq8 = 9,
    /// External pin interrupt 9
    IcuIrq9 = 10,
    /// Transfer error
    Iic0Eri = 159,
    /// Receive data full
    Iic0Rxi = 156,
    /// Transmit end
    Iic0Tei = 158,
    /// Transmit data empty
    Iic0Txi = 157,
    /// Wakeup interrupt
    Iic0Wui = 160,
    /// Transfer error
    Iic1Eri = 164,
    /// Receive data full
    Iic1Rxi = 161,
    /// Transmit end
    Iic1Tei = 163,
    /// Transmit data empty
    Iic1Txi = 162,
    /// Transfer error
    Iic2Eri = 169,
    /// Receive data full
    Iic2Rxi = 166,
    /// Transmit end
    Iic2Tei = 168,
    /// Transmit data empty
    Iic2Txi = 167,
    /// Port 1 event
    IoportEvent1 = 208,
    /// Port 2 event
    IoportEvent2 = 209,
    /// Port 3 event
    IoportEvent3 = 210,
    /// Port 4 event
    IoportEvent4 = 211,
    /// CPU Mutual Interrupt 0
    IpcIrq0 = 91,
    /// CPU Mutual Interrupt 1
    IpcIrq1 = 92,
    /// IWDT underflow
    IwdtUnderflow = 146,
    /// Local memory 0 error
    Lm0Err = 95,
    /// Local memory 1 error
    Lm1Err = 96,
    /// Voltage monitor 1 interrupt
    LvdLvd1 = 112,
    /// Voltage monitor 2 interrupt
    LvdLvd2 = 113,
    /// Data Lane interrupt
    MipicsiDl = 912,
    /// Generic Short Packet interrupt
    MipicsiGst = 915,
    /// Power Management interrupt
    MipicsiPm = 914,
    /// Receive interrupt
    MipicsiRx = 911,
    /// Virtual Channel interrupt
    MipicsiVc = 913,
    /// DSI fatal error interrupt
    MipidsiFerr = 908,
    /// DSI D-PHY PPI interrupt
    MipidsiPpi = 909,
    /// DSI packet receive interrupt
    MipidsiRcv = 907,
    /// Sequence operation channel 0 interrupt
    MipidsiSeq0 = 904,
    /// Sequence operation channel 1 interrupt
    MipidsiSeq1 = 905,
    /// Video-Input operation channel1 interrupt
    MipidsiVin1 = 906,
    /// MRAM sequencer ready
    MramEndofpe = 109,
    /// MRAM sequencer error interrupt for MRC
    MramMrcpr = 107,
    /// MRAM read error interrupt for MRC
    MramMrcrd = 104,
    /// MRAM sequencer error interrupt for MRE
    MramMrepr = 108,
    /// MRAM read error interrupt for MRE
    MramMrerd = 105,
    /// NPU IRQ
    NpuIrq = 103,
    /// UVW edge event
    OpsUvwEdge = 384,
    /// Data reception interrupt channel 0
    PdmDat0 = 191,
    /// Data reception interrupt channel 1
    PdmDat1 = 192,
    /// Data reception interrupt channel 2
    PdmDat2 = 193,
    /// Error detection interrupt channel 0
    PdmErr0 = 195,
    /// Error detection interrupt channel 1
    PdmErr1 = 196,
    /// Error detection interrupt channel 2
    PdmErr2 = 197,
    /// Sound detection interrupt
    PdmSdet = 194,
    /// Port Output disable 0 interrupt
    Poeg0Event = 215,
    /// Port Output disable 1 interrupt
    Poeg1Event = 216,
    /// Port Output disable 2 interrupt
    Poeg2Event = 217,
    /// Port Output disable 3 interrupt
    Poeg3Event = 218,
    /// RSIP Tamper Detection
    RsipTadi = 881,
    /// Alarm interrupt
    RtcAlarm = 149,
    /// Carry interrupt
    RtcCarry = 151,
    /// Periodic interrupt
    RtcPeriod = 150,
    /// Active edge detection
    Sci0Aed = 712,
    /// Address match event
    Sci0Am = 714,
    /// Break field detection
    Sci0Bfd = 713,
    /// Receive error
    Sci0Eri = 711,
    /// Receive data full
    Sci0Rxi = 708,
    /// Transmit end
    Sci0Tei = 710,
    /// Transmit data empty
    Sci0Txi = 709,
    /// Active edge detection
    Sci10Aed = 782,
    /// Address match event
    Sci10Am = 784,
    /// Break field detection
    Sci10Bfd = 783,
    /// Receive error
    Sci10Eri = 781,
    /// Receive data full
    Sci10Rxi = 778,
    /// Transmit end
    Sci10Tei = 780,
    /// Transmit data empty
    Sci10Txi = 779,
    /// Active edge detection
    Sci11Aed = 789,
    /// Address match event
    Sci11Am = 791,
    /// Break field detection
    Sci11Bfd = 790,
    /// Receive error
    Sci11Eri = 788,
    /// Receive data full
    Sci11Rxi = 785,
    /// Transmit end
    Sci11Tei = 787,
    /// Transmit data empty
    Sci11Txi = 786,
    /// Active edge detection
    Sci1Aed = 719,
    /// Address match event
    Sci1Am = 721,
    /// Break field detection
    Sci1Bfd = 720,
    /// Receive error
    Sci1Eri = 718,
    /// Receive data full
    Sci1Rxi = 715,
    /// Transmit end
    Sci1Tei = 717,
    /// Transmit data empty
    Sci1Txi = 716,
    /// Active edge detection
    Sci2Aed = 726,
    /// Address match event
    Sci2Am = 728,
    /// Break field detection
    Sci2Bfd = 727,
    /// Receive error
    Sci2Eri = 725,
    /// Receive data full
    Sci2Rxi = 722,
    /// Transmit end
    Sci2Tei = 724,
    /// Transmit data empty
    Sci2Txi = 723,
    /// Active edge detection
    Sci3Aed = 733,
    /// Address match event
    Sci3Am = 735,
    /// Break field detection
    Sci3Bfd = 734,
    /// Receive error
    Sci3Eri = 732,
    /// Receive data full
    Sci3Rxi = 729,
    /// Transmit end
    Sci3Tei = 731,
    /// Transmit data empty
    Sci3Txi = 730,
    /// Active edge detection
    Sci4Aed = 740,
    /// Address match event
    Sci4Am = 742,
    /// Break field detection
    Sci4Bfd = 741,
    /// Receive error
    Sci4Eri = 739,
    /// Receive data full
    Sci4Rxi = 736,
    /// Transmit end
    Sci4Tei = 738,
    /// Transmit data empty
    Sci4Txi = 737,
    /// Active edge detection
    Sci5Aed = 747,
    /// Address match event
    Sci5Am = 749,
    /// Break field detection
    Sci5Bfd = 748,
    /// Receive error
    Sci5Eri = 746,
    /// Receive data full
    Sci5Rxi = 743,
    /// Transmit end
    Sci5Tei = 745,
    /// Transmit data empty
    Sci5Txi = 744,
    /// Active edge detection
    Sci6Aed = 754,
    /// Address match event
    Sci6Am = 756,
    /// Break field detection
    Sci6Bfd = 755,
    /// Receive error
    Sci6Eri = 753,
    /// Receive data full
    Sci6Rxi = 750,
    /// Transmit end
    Sci6Tei = 752,
    /// Transmit data empty
    Sci6Txi = 751,
    /// Active edge detection
    Sci7Aed = 761,
    /// Address match event
    Sci7Am = 763,
    /// Break field detection
    Sci7Bfd = 762,
    /// Receive error
    Sci7Eri = 760,
    /// Receive data full
    Sci7Rxi = 757,
    /// Transmit end
    Sci7Tei = 759,
    /// Transmit data empty
    Sci7Txi = 758,
    /// Active edge detection
    Sci8Aed = 768,
    /// Address match event
    Sci8Am = 770,
    /// Break field detection
    Sci8Bfd = 769,
    /// Receive error
    Sci8Eri = 767,
    /// Receive data full
    Sci8Rxi = 764,
    /// Transmit end
    Sci8Tei = 766,
    /// Transmit data empty
    Sci8Txi = 765,
    /// Active edge detection
    Sci9Aed = 775,
    /// Address match event
    Sci9Am = 777,
    /// Break field detection
    Sci9Bfd = 776,
    /// Receive error
    Sci9Eri = 774,
    /// Receive data full
    Sci9Rxi = 771,
    /// Transmit end
    Sci9Tei = 773,
    /// Transmit data empty
    Sci9Txi = 772,
    /// Card access
    Sdhimmc0Accs = 171,
    /// Card detect
    Sdhimmc0Card = 173,
    /// DMA transfer request
    Sdhimmc0DmaReq = 174,
    /// SDIO access
    Sdhimmc0Sdio = 172,
    /// Card access
    Sdhimmc1Accs = 175,
    /// Card detect
    Sdhimmc1Card = 177,
    /// DMA transfer request
    Sdhimmc1DmaReq = 178,
    /// SDIO access
    Sdhimmc1Sdio = 176,
    /// Error
    Spi0Eri = 795,
    /// Idle
    Spi0Idle = 794,
    /// Receive buffer full
    Spi0Rxi = 792,
    /// Transmission complete event
    Spi0Tei = 796,
    /// Transmit buffer empty
    Spi0Txi = 793,
    /// Error
    Spi1Eri = 800,
    /// Idle
    Spi1Idle = 799,
    /// Receive buffer full
    Spi1Rxi = 797,
    /// Transmission complete event
    Spi1Tei = 801,
    /// Transmit buffer empty
    Spi1Txi = 798,
    /// Error interrupt
    Ssi0Int = 182,
    /// Receive data full
    Ssi0Rxi = 180,
    /// Transmit data empty
    Ssi0Txi = 179,
    /// Error interrupt
    Ssi1Int = 186,
    /// Receive data full/Transmit data empty
    Ssi1Rxi = 185,
    /// ULPT0 Compare match A
    Ulpt0CompareA = 129,
    /// ULPT0 Compare match B
    Ulpt0CompareB = 130,
    /// ULPT0 Underflow
    Ulpt0Int = 128,
    /// ULPT1 Compare match A
    Ulpt1CompareA = 132,
    /// ULPT1 Compare match B
    Ulpt1CompareB = 133,
    /// ULPT1 Underflow
    Ulpt1Int = 131,
    /// DMA/DTC transfer request 0
    UsbfsFifo0 = 152,
    /// DMA/DTC transfer request 1
    UsbfsFifo1 = 153,
    /// USBFS interrupt
    UsbfsInt = 154,
    /// USBFS resume interrupt
    UsbfsResume = 155,
    /// DMA transfer request 0
    UsbhsFifo0 = 705,
    /// DMA transfer request 1
    UsbhsFifo1 = 706,
    /// USBHS interrupt
    UsbhsUsbIntResume = 707,
    /// VBATT Tamper Detection
    VbattTadi = 117,
    /// Interrupt Request for SYNC Error
    VinErr = 918,
    /// Interrupt Request
    VinIrq = 917,
    /// WDT0 underflow
    Wdt0Underflow = 147,
    /// WDT1 underflow
    Wdt1Underflow = 148,
    /// xSPI1 Complete
    Xspi1Cmp = 190,
    /// xSPI1 Error
    Xspi1Err = 189,
    /// xSPI Complete
    XspiCmp = 188,
    /// xSPI Error
    XspiErr = 187,
}
#[allow(non_upper_case_globals)]
impl Event {
    /// Error
    pub const Iicb0Eri: Self = Self::I3c0Eei;
    /// Receive
    pub const Iicb0Rxi: Self = Self::I3c0Rx;
    /// Transmit end
    pub const Iicb0Tei: Self = Self::I3c0Tend;
    /// Transmit
    pub const Iicb0Txi: Self = Self::I3c0Tx;
    /// Receive data full/Transmit data empty
    pub const Ssi1Txi: Self = Self::Ssi1Rxi;
}
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    IEL0 = 0,
    IEL1 = 1,
    IEL2 = 2,
    IEL3 = 3,
    IEL4 = 4,
    IEL5 = 5,
    IEL6 = 6,
    IEL7 = 7,
    IEL8 = 8,
    IEL9 = 9,
    IEL10 = 10,
    IEL11 = 11,
    IEL12 = 12,
    IEL13 = 13,
    IEL14 = 14,
    IEL15 = 15,
    IEL16 = 16,
    IEL17 = 17,
    IEL18 = 18,
    IEL19 = 19,
    IEL20 = 20,
    IEL21 = 21,
    IEL22 = 22,
    IEL23 = 23,
    IEL24 = 24,
    IEL25 = 25,
    IEL26 = 26,
    IEL27 = 27,
    IEL28 = 28,
    IEL29 = 29,
    IEL30 = 30,
    IEL31 = 31,
    IEL32 = 32,
    IEL33 = 33,
    IEL34 = 34,
    IEL35 = 35,
    IEL36 = 36,
    IEL37 = 37,
    IEL38 = 38,
    IEL39 = 39,
    IEL40 = 40,
    IEL41 = 41,
    IEL42 = 42,
    IEL43 = 43,
    IEL44 = 44,
    IEL45 = 45,
    IEL46 = 46,
    IEL47 = 47,
    IEL48 = 48,
    IEL49 = 49,
    IEL50 = 50,
    IEL51 = 51,
    IEL52 = 52,
    IEL53 = 53,
    IEL54 = 54,
    IEL55 = 55,
    IEL56 = 56,
    IEL57 = 57,
    IEL58 = 58,
    IEL59 = 59,
    IEL60 = 60,
    IEL61 = 61,
    IEL62 = 62,
    IEL63 = 63,
    IEL64 = 64,
    IEL65 = 65,
    IEL66 = 66,
    IEL67 = 67,
    IEL68 = 68,
    IEL69 = 69,
    IEL70 = 70,
    IEL71 = 71,
    IEL72 = 72,
    IEL73 = 73,
    IEL74 = 74,
    IEL75 = 75,
    IEL76 = 76,
    IEL77 = 77,
    IEL78 = 78,
    IEL79 = 79,
    IEL80 = 80,
    IEL81 = 81,
    IEL82 = 82,
    IEL83 = 83,
    IEL84 = 84,
    IEL85 = 85,
    IEL86 = 86,
    IEL87 = 87,
    IEL88 = 88,
    IEL89 = 89,
    IEL90 = 90,
    IEL91 = 91,
    IEL92 = 92,
    IEL93 = 93,
    IEL94 = 94,
    IEL95 = 95,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[cfg(feature = "embassy")]
embassy_hal_internal::interrupt_mod!(
    IEL0, IEL1, IEL2, IEL3, IEL4, IEL5, IEL6, IEL7, IEL8, IEL9, IEL10, IEL11, IEL12, IEL13, IEL14,
    IEL15, IEL16, IEL17, IEL18, IEL19, IEL20, IEL21, IEL22, IEL23, IEL24, IEL25, IEL26, IEL27,
    IEL28, IEL29, IEL30, IEL31, IEL32, IEL33, IEL34, IEL35, IEL36, IEL37, IEL38, IEL39, IEL40,
    IEL41, IEL42, IEL43, IEL44, IEL45, IEL46, IEL47, IEL48, IEL49, IEL50, IEL51, IEL52, IEL53,
    IEL54, IEL55, IEL56, IEL57, IEL58, IEL59, IEL60, IEL61, IEL62, IEL63, IEL64, IEL65, IEL66,
    IEL67, IEL68, IEL69, IEL70, IEL71, IEL72, IEL73, IEL74, IEL75, IEL76, IEL77, IEL78, IEL79,
    IEL80, IEL81, IEL82, IEL83, IEL84, IEL85, IEL86, IEL87, IEL88, IEL89, IEL90, IEL91, IEL92,
    IEL93, IEL94, IEL95,
);
extern "C" {
    pub fn IEL0();
    pub fn IEL1();
    pub fn IEL2();
    pub fn IEL3();
    pub fn IEL4();
    pub fn IEL5();
    pub fn IEL6();
    pub fn IEL7();
    pub fn IEL8();
    pub fn IEL9();
    pub fn IEL10();
    pub fn IEL11();
    pub fn IEL12();
    pub fn IEL13();
    pub fn IEL14();
    pub fn IEL15();
    pub fn IEL16();
    pub fn IEL17();
    pub fn IEL18();
    pub fn IEL19();
    pub fn IEL20();
    pub fn IEL21();
    pub fn IEL22();
    pub fn IEL23();
    pub fn IEL24();
    pub fn IEL25();
    pub fn IEL26();
    pub fn IEL27();
    pub fn IEL28();
    pub fn IEL29();
    pub fn IEL30();
    pub fn IEL31();
    pub fn IEL32();
    pub fn IEL33();
    pub fn IEL34();
    pub fn IEL35();
    pub fn IEL36();
    pub fn IEL37();
    pub fn IEL38();
    pub fn IEL39();
    pub fn IEL40();
    pub fn IEL41();
    pub fn IEL42();
    pub fn IEL43();
    pub fn IEL44();
    pub fn IEL45();
    pub fn IEL46();
    pub fn IEL47();
    pub fn IEL48();
    pub fn IEL49();
    pub fn IEL50();
    pub fn IEL51();
    pub fn IEL52();
    pub fn IEL53();
    pub fn IEL54();
    pub fn IEL55();
    pub fn IEL56();
    pub fn IEL57();
    pub fn IEL58();
    pub fn IEL59();
    pub fn IEL60();
    pub fn IEL61();
    pub fn IEL62();
    pub fn IEL63();
    pub fn IEL64();
    pub fn IEL65();
    pub fn IEL66();
    pub fn IEL67();
    pub fn IEL68();
    pub fn IEL69();
    pub fn IEL70();
    pub fn IEL71();
    pub fn IEL72();
    pub fn IEL73();
    pub fn IEL74();
    pub fn IEL75();
    pub fn IEL76();
    pub fn IEL77();
    pub fn IEL78();
    pub fn IEL79();
    pub fn IEL80();
    pub fn IEL81();
    pub fn IEL82();
    pub fn IEL83();
    pub fn IEL84();
    pub fn IEL85();
    pub fn IEL86();
    pub fn IEL87();
    pub fn IEL88();
    pub fn IEL89();
    pub fn IEL90();
    pub fn IEL91();
    pub fn IEL92();
    pub fn IEL93();
    pub fn IEL94();
    pub fn IEL95();
}
#[derive(Copy, Clone)]
#[repr(C)]
pub union Vector {
    pub _handler: unsafe extern "C" fn(),
    pub _reserved: u32,
}
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 96] = [
    Vector { _handler: IEL0 },
    Vector { _handler: IEL1 },
    Vector { _handler: IEL2 },
    Vector { _handler: IEL3 },
    Vector { _handler: IEL4 },
    Vector { _handler: IEL5 },
    Vector { _handler: IEL6 },
    Vector { _handler: IEL7 },
    Vector { _handler: IEL8 },
    Vector { _handler: IEL9 },
    Vector { _handler: IEL10 },
    Vector { _handler: IEL11 },
    Vector { _handler: IEL12 },
    Vector { _handler: IEL13 },
    Vector { _handler: IEL14 },
    Vector { _handler: IEL15 },
    Vector { _handler: IEL16 },
    Vector { _handler: IEL17 },
    Vector { _handler: IEL18 },
    Vector { _handler: IEL19 },
    Vector { _handler: IEL20 },
    Vector { _handler: IEL21 },
    Vector { _handler: IEL22 },
    Vector { _handler: IEL23 },
    Vector { _handler: IEL24 },
    Vector { _handler: IEL25 },
    Vector { _handler: IEL26 },
    Vector { _handler: IEL27 },
    Vector { _handler: IEL28 },
    Vector { _handler: IEL29 },
    Vector { _handler: IEL30 },
    Vector { _handler: IEL31 },
    Vector { _handler: IEL32 },
    Vector { _handler: IEL33 },
    Vector { _handler: IEL34 },
    Vector { _handler: IEL35 },
    Vector { _handler: IEL36 },
    Vector { _handler: IEL37 },
    Vector { _handler: IEL38 },
    Vector { _handler: IEL39 },
    Vector { _handler: IEL40 },
    Vector { _handler: IEL41 },
    Vector { _handler: IEL42 },
    Vector { _handler: IEL43 },
    Vector { _handler: IEL44 },
    Vector { _handler: IEL45 },
    Vector { _handler: IEL46 },
    Vector { _handler: IEL47 },
    Vector { _handler: IEL48 },
    Vector { _handler: IEL49 },
    Vector { _handler: IEL50 },
    Vector { _handler: IEL51 },
    Vector { _handler: IEL52 },
    Vector { _handler: IEL53 },
    Vector { _handler: IEL54 },
    Vector { _handler: IEL55 },
    Vector { _handler: IEL56 },
    Vector { _handler: IEL57 },
    Vector { _handler: IEL58 },
    Vector { _handler: IEL59 },
    Vector { _handler: IEL60 },
    Vector { _handler: IEL61 },
    Vector { _handler: IEL62 },
    Vector { _handler: IEL63 },
    Vector { _handler: IEL64 },
    Vector { _handler: IEL65 },
    Vector { _handler: IEL66 },
    Vector { _handler: IEL67 },
    Vector { _handler: IEL68 },
    Vector { _handler: IEL69 },
    Vector { _handler: IEL70 },
    Vector { _handler: IEL71 },
    Vector { _handler: IEL72 },
    Vector { _handler: IEL73 },
    Vector { _handler: IEL74 },
    Vector { _handler: IEL75 },
    Vector { _handler: IEL76 },
    Vector { _handler: IEL77 },
    Vector { _handler: IEL78 },
    Vector { _handler: IEL79 },
    Vector { _handler: IEL80 },
    Vector { _handler: IEL81 },
    Vector { _handler: IEL82 },
    Vector { _handler: IEL83 },
    Vector { _handler: IEL84 },
    Vector { _handler: IEL85 },
    Vector { _handler: IEL86 },
    Vector { _handler: IEL87 },
    Vector { _handler: IEL88 },
    Vector { _handler: IEL89 },
    Vector { _handler: IEL90 },
    Vector { _handler: IEL91 },
    Vector { _handler: IEL92 },
    Vector { _handler: IEL93 },
    Vector { _handler: IEL94 },
    Vector { _handler: IEL95 },
];
