// This file is autogenerated by ra-metapac-gen: do not edit by hand.
#![allow(clippy::missing_safety_doc)]
#![allow(clippy::identity_op)]
#![allow(clippy::unnecessary_cast)]
#![allow(clippy::erasing_op)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]

#[doc = "Pin Function Select Register block."]
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct Pfs {
    ptr: *mut u8,
}
unsafe impl Send for Pfs {}
unsafe impl Sync for Pfs {}
impl Pfs {
    #[inline(always)]
    pub const unsafe fn from_ptr(ptr: *mut ()) -> Self {
        Self { ptr: ptr as _ }
    }
    #[inline(always)]
    pub const fn as_ptr(&self) -> *mut () {
        self.ptr as _
    }
}
pub mod regs {
    #[doc = "Pin Function Select Register (32-bit)."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct Pfs(pub u32);
    impl Pfs {
        #[doc = "Port Output Data"]
        #[must_use]
        #[inline(always)]
        pub const fn podr(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        #[doc = "Port Output Data"]
        #[inline(always)]
        pub const fn set_podr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
        }
        #[doc = "Port Input Data (read-only)"]
        #[must_use]
        #[inline(always)]
        pub const fn pidr(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        #[doc = "Port Input Data (read-only)"]
        #[inline(always)]
        pub const fn set_pidr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize);
        }
        #[doc = "Port Direction (0=input, 1=output)"]
        #[must_use]
        #[inline(always)]
        pub const fn pdr(&self) -> bool {
            let val = (self.0 >> 2usize) & 0x01;
            val != 0
        }
        #[doc = "Port Direction (0=input, 1=output)"]
        #[inline(always)]
        pub const fn set_pdr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize);
        }
        #[doc = "Pull-up Control"]
        #[must_use]
        #[inline(always)]
        pub const fn pcr(&self) -> bool {
            let val = (self.0 >> 4usize) & 0x01;
            val != 0
        }
        #[doc = "Pull-up Control"]
        #[inline(always)]
        pub const fn set_pcr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 4usize)) | (((val as u32) & 0x01) << 4usize);
        }
        #[doc = "N-Channel Open Drain Control"]
        #[must_use]
        #[inline(always)]
        pub const fn ncodr(&self) -> bool {
            let val = (self.0 >> 6usize) & 0x01;
            val != 0
        }
        #[doc = "N-Channel Open Drain Control"]
        #[inline(always)]
        pub const fn set_ncodr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 6usize)) | (((val as u32) & 0x01) << 6usize);
        }
        #[doc = "Drive Strength Control"]
        #[must_use]
        #[inline(always)]
        pub const fn dscr(&self) -> u8 {
            let val = (self.0 >> 10usize) & 0x03;
            val as u8
        }
        #[doc = "Drive Strength Control"]
        #[inline(always)]
        pub const fn set_dscr(&mut self, val: u8) {
            self.0 = (self.0 & !(0x03 << 10usize)) | (((val as u32) & 0x03) << 10usize);
        }
        #[doc = "Event on Rising"]
        #[must_use]
        #[inline(always)]
        pub const fn eor(&self) -> bool {
            let val = (self.0 >> 12usize) & 0x01;
            val != 0
        }
        #[doc = "Event on Rising"]
        #[inline(always)]
        pub const fn set_eor(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 12usize)) | (((val as u32) & 0x01) << 12usize);
        }
        #[doc = "Event on Falling"]
        #[must_use]
        #[inline(always)]
        pub const fn eof(&self) -> bool {
            let val = (self.0 >> 13usize) & 0x01;
            val != 0
        }
        #[doc = "Event on Falling"]
        #[inline(always)]
        pub const fn set_eof(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 13usize)) | (((val as u32) & 0x01) << 13usize);
        }
        #[doc = "IRQ Input Enable"]
        #[must_use]
        #[inline(always)]
        pub const fn isel(&self) -> bool {
            let val = (self.0 >> 14usize) & 0x01;
            val != 0
        }
        #[doc = "IRQ Input Enable"]
        #[inline(always)]
        pub const fn set_isel(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 14usize)) | (((val as u32) & 0x01) << 14usize);
        }
        #[doc = "Analog Input Enable"]
        #[must_use]
        #[inline(always)]
        pub const fn asel(&self) -> bool {
            let val = (self.0 >> 15usize) & 0x01;
            val != 0
        }
        #[doc = "Analog Input Enable"]
        #[inline(always)]
        pub const fn set_asel(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 15usize)) | (((val as u32) & 0x01) << 15usize);
        }
        #[doc = "Port Mode Control (0=GPIO, 1=peripheral)"]
        #[must_use]
        #[inline(always)]
        pub const fn pmr(&self) -> bool {
            let val = (self.0 >> 16usize) & 0x01;
            val != 0
        }
        #[doc = "Port Mode Control (0=GPIO, 1=peripheral)"]
        #[inline(always)]
        pub const fn set_pmr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 16usize)) | (((val as u32) & 0x01) << 16usize);
        }
        #[doc = "Peripheral Function Select"]
        #[must_use]
        #[inline(always)]
        pub const fn psel(&self) -> u8 {
            let val = (self.0 >> 24usize) & 0x1f;
            val as u8
        }
        #[doc = "Peripheral Function Select"]
        #[inline(always)]
        pub const fn set_psel(&mut self, val: u8) {
            self.0 = (self.0 & !(0x1f << 24usize)) | (((val as u32) & 0x1f) << 24usize);
        }
    }
    impl Default for Pfs {
        #[inline(always)]
        fn default() -> Pfs {
            Pfs(0)
        }
    }
    impl core::fmt::Debug for Pfs {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("Pfs")
                .field("podr", &self.podr())
                .field("pidr", &self.pidr())
                .field("pdr", &self.pdr())
                .field("pcr", &self.pcr())
                .field("ncodr", &self.ncodr())
                .field("dscr", &self.dscr())
                .field("eor", &self.eor())
                .field("eof", &self.eof())
                .field("isel", &self.isel())
                .field("asel", &self.asel())
                .field("pmr", &self.pmr())
                .field("psel", &self.psel())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for Pfs {
        fn format(&self, f: defmt::Formatter) {
            defmt :: write ! (f , "Pfs {{ podr: {=bool:?}, pidr: {=bool:?}, pdr: {=bool:?}, pcr: {=bool:?}, ncodr: {=bool:?}, dscr: {=u8:?}, eor: {=bool:?}, eof: {=bool:?}, isel: {=bool:?}, asel: {=bool:?}, pmr: {=bool:?}, psel: {=u8:?} }}" , self . podr () , self . pidr () , self . pdr () , self . pcr () , self . ncodr () , self . dscr () , self . eor () , self . eof () , self . isel () , self . asel () , self . pmr () , self . psel ())
        }
    }
    #[doc = "Pin Function Select Register (8-bit byte access)."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct PfsBy(pub u8);
    impl PfsBy {
        #[doc = "Port Output Data"]
        #[must_use]
        #[inline(always)]
        pub const fn podr(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        #[doc = "Port Output Data"]
        #[inline(always)]
        pub const fn set_podr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u8) & 0x01) << 0usize);
        }
        #[doc = "Port Input Data (read-only)"]
        #[must_use]
        #[inline(always)]
        pub const fn pidr(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        #[doc = "Port Input Data (read-only)"]
        #[inline(always)]
        pub const fn set_pidr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u8) & 0x01) << 1usize);
        }
        #[doc = "Port Direction (0=input, 1=output)"]
        #[must_use]
        #[inline(always)]
        pub const fn pdr(&self) -> bool {
            let val = (self.0 >> 2usize) & 0x01;
            val != 0
        }
        #[doc = "Port Direction (0=input, 1=output)"]
        #[inline(always)]
        pub const fn set_pdr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 2usize)) | (((val as u8) & 0x01) << 2usize);
        }
        #[doc = "Pull-up Control"]
        #[must_use]
        #[inline(always)]
        pub const fn pcr(&self) -> bool {
            let val = (self.0 >> 4usize) & 0x01;
            val != 0
        }
        #[doc = "Pull-up Control"]
        #[inline(always)]
        pub const fn set_pcr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 4usize)) | (((val as u8) & 0x01) << 4usize);
        }
        #[doc = "N-Channel Open Drain Control"]
        #[must_use]
        #[inline(always)]
        pub const fn ncodr(&self) -> bool {
            let val = (self.0 >> 6usize) & 0x01;
            val != 0
        }
        #[doc = "N-Channel Open Drain Control"]
        #[inline(always)]
        pub const fn set_ncodr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 6usize)) | (((val as u8) & 0x01) << 6usize);
        }
    }
    impl Default for PfsBy {
        #[inline(always)]
        fn default() -> PfsBy {
            PfsBy(0)
        }
    }
    impl core::fmt::Debug for PfsBy {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("PfsBy")
                .field("podr", &self.podr())
                .field("pidr", &self.pidr())
                .field("pdr", &self.pdr())
                .field("pcr", &self.pcr())
                .field("ncodr", &self.ncodr())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for PfsBy {
        fn format(&self, f: defmt::Formatter) {
            defmt :: write ! (f , "PfsBy {{ podr: {=bool:?}, pidr: {=bool:?}, pdr: {=bool:?}, pcr: {=bool:?}, ncodr: {=bool:?} }}" , self . podr () , self . pidr () , self . pdr () , self . pcr () , self . ncodr ())
        }
    }
    #[doc = "Pin Function Select Register (16-bit half access)."]
    #[repr(transparent)]
    #[derive(Copy, Clone, Eq, PartialEq)]
    pub struct PfsHa(pub u16);
    impl PfsHa {
        #[doc = "Port Output Data"]
        #[must_use]
        #[inline(always)]
        pub const fn podr(&self) -> bool {
            let val = (self.0 >> 0usize) & 0x01;
            val != 0
        }
        #[doc = "Port Output Data"]
        #[inline(always)]
        pub const fn set_podr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u16) & 0x01) << 0usize);
        }
        #[doc = "Port Input Data (read-only)"]
        #[must_use]
        #[inline(always)]
        pub const fn pidr(&self) -> bool {
            let val = (self.0 >> 1usize) & 0x01;
            val != 0
        }
        #[doc = "Port Input Data (read-only)"]
        #[inline(always)]
        pub const fn set_pidr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u16) & 0x01) << 1usize);
        }
        #[doc = "Port Direction (0=input, 1=output)"]
        #[must_use]
        #[inline(always)]
        pub const fn pdr(&self) -> bool {
            let val = (self.0 >> 2usize) & 0x01;
            val != 0
        }
        #[doc = "Port Direction (0=input, 1=output)"]
        #[inline(always)]
        pub const fn set_pdr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 2usize)) | (((val as u16) & 0x01) << 2usize);
        }
        #[doc = "Pull-up Control"]
        #[must_use]
        #[inline(always)]
        pub const fn pcr(&self) -> bool {
            let val = (self.0 >> 4usize) & 0x01;
            val != 0
        }
        #[doc = "Pull-up Control"]
        #[inline(always)]
        pub const fn set_pcr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 4usize)) | (((val as u16) & 0x01) << 4usize);
        }
        #[doc = "N-Channel Open Drain Control"]
        #[must_use]
        #[inline(always)]
        pub const fn ncodr(&self) -> bool {
            let val = (self.0 >> 6usize) & 0x01;
            val != 0
        }
        #[doc = "N-Channel Open Drain Control"]
        #[inline(always)]
        pub const fn set_ncodr(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 6usize)) | (((val as u16) & 0x01) << 6usize);
        }
        #[doc = "Drive Strength Control"]
        #[must_use]
        #[inline(always)]
        pub const fn dscr(&self) -> u8 {
            let val = (self.0 >> 10usize) & 0x03;
            val as u8
        }
        #[doc = "Drive Strength Control"]
        #[inline(always)]
        pub const fn set_dscr(&mut self, val: u8) {
            self.0 = (self.0 & !(0x03 << 10usize)) | (((val as u16) & 0x03) << 10usize);
        }
        #[doc = "Event on Rising"]
        #[must_use]
        #[inline(always)]
        pub const fn eor(&self) -> bool {
            let val = (self.0 >> 12usize) & 0x01;
            val != 0
        }
        #[doc = "Event on Rising"]
        #[inline(always)]
        pub const fn set_eor(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 12usize)) | (((val as u16) & 0x01) << 12usize);
        }
        #[doc = "Event on Falling"]
        #[must_use]
        #[inline(always)]
        pub const fn eof(&self) -> bool {
            let val = (self.0 >> 13usize) & 0x01;
            val != 0
        }
        #[doc = "Event on Falling"]
        #[inline(always)]
        pub const fn set_eof(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 13usize)) | (((val as u16) & 0x01) << 13usize);
        }
        #[doc = "IRQ Input Enable"]
        #[must_use]
        #[inline(always)]
        pub const fn isel(&self) -> bool {
            let val = (self.0 >> 14usize) & 0x01;
            val != 0
        }
        #[doc = "IRQ Input Enable"]
        #[inline(always)]
        pub const fn set_isel(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 14usize)) | (((val as u16) & 0x01) << 14usize);
        }
        #[doc = "Analog Input Enable"]
        #[must_use]
        #[inline(always)]
        pub const fn asel(&self) -> bool {
            let val = (self.0 >> 15usize) & 0x01;
            val != 0
        }
        #[doc = "Analog Input Enable"]
        #[inline(always)]
        pub const fn set_asel(&mut self, val: bool) {
            self.0 = (self.0 & !(0x01 << 15usize)) | (((val as u16) & 0x01) << 15usize);
        }
    }
    impl Default for PfsHa {
        #[inline(always)]
        fn default() -> PfsHa {
            PfsHa(0)
        }
    }
    impl core::fmt::Debug for PfsHa {
        fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
            f.debug_struct("PfsHa")
                .field("podr", &self.podr())
                .field("pidr", &self.pidr())
                .field("pdr", &self.pdr())
                .field("pcr", &self.pcr())
                .field("ncodr", &self.ncodr())
                .field("dscr", &self.dscr())
                .field("eor", &self.eor())
                .field("eof", &self.eof())
                .field("isel", &self.isel())
                .field("asel", &self.asel())
                .finish()
        }
    }
    #[cfg(feature = "defmt")]
    impl defmt::Format for PfsHa {
        fn format(&self, f: defmt::Formatter) {
            defmt :: write ! (f , "PfsHa {{ podr: {=bool:?}, pidr: {=bool:?}, pdr: {=bool:?}, pcr: {=bool:?}, ncodr: {=bool:?}, dscr: {=u8:?}, eor: {=bool:?}, eof: {=bool:?}, isel: {=bool:?}, asel: {=bool:?} }}" , self . podr () , self . pidr () , self . pdr () , self . pcr () , self . ncodr () , self . dscr () , self . eor () , self . eof () , self . isel () , self . asel ())
        }
    }
}
