PROVIDE(NonMaskableInt = DefaultHandler);
PROVIDE(HardFault = DefaultHandler);
PROVIDE(MemoryManagement = DefaultHandler);
PROVIDE(BusFault = DefaultHandler);
PROVIDE(UsageFault = DefaultHandler);
PROVIDE(SecureFault = DefaultHandler);
PROVIDE(SVCall = DefaultHandler);
PROVIDE(DebugMonitor = DefaultHandler);
PROVIDE(PendSV = DefaultHandler);
PROVIDE(SysTick = DefaultHandler);
EXTERN(IEL0);
PROVIDE(IEL0 = DefaultHandler);
EXTERN(IEL1);
PROVIDE(IEL1 = DefaultHandler);
EXTERN(IEL2);
PROVIDE(IEL2 = DefaultHandler);
EXTERN(IEL3);
PROVIDE(IEL3 = DefaultHandler);
EXTERN(IEL4);
PROVIDE(IEL4 = DefaultHandler);
EXTERN(IEL5);
PROVIDE(IEL5 = DefaultHandler);
EXTERN(IEL6);
PROVIDE(IEL6 = DefaultHandler);
EXTERN(IEL7);
PROVIDE(IEL7 = DefaultHandler);
EXTERN(IEL8);
PROVIDE(IEL8 = DefaultHandler);
EXTERN(IEL9);
PROVIDE(IEL9 = DefaultHandler);
EXTERN(IEL10);
PROVIDE(IEL10 = DefaultHandler);
EXTERN(IEL11);
PROVIDE(IEL11 = DefaultHandler);
EXTERN(IEL12);
PROVIDE(IEL12 = DefaultHandler);
EXTERN(IEL13);
PROVIDE(IEL13 = DefaultHandler);
EXTERN(IEL14);
PROVIDE(IEL14 = DefaultHandler);
EXTERN(IEL15);
PROVIDE(IEL15 = DefaultHandler);
EXTERN(IEL16);
PROVIDE(IEL16 = DefaultHandler);
EXTERN(IEL17);
PROVIDE(IEL17 = DefaultHandler);
EXTERN(IEL18);
PROVIDE(IEL18 = DefaultHandler);
EXTERN(IEL19);
PROVIDE(IEL19 = DefaultHandler);
EXTERN(IEL20);
PROVIDE(IEL20 = DefaultHandler);
EXTERN(IEL21);
PROVIDE(IEL21 = DefaultHandler);
EXTERN(IEL22);
PROVIDE(IEL22 = DefaultHandler);
EXTERN(IEL23);
PROVIDE(IEL23 = DefaultHandler);
EXTERN(IEL24);
PROVIDE(IEL24 = DefaultHandler);
EXTERN(IEL25);
PROVIDE(IEL25 = DefaultHandler);
EXTERN(IEL26);
PROVIDE(IEL26 = DefaultHandler);
EXTERN(IEL27);
PROVIDE(IEL27 = DefaultHandler);
EXTERN(IEL28);
PROVIDE(IEL28 = DefaultHandler);
EXTERN(IEL29);
PROVIDE(IEL29 = DefaultHandler);
EXTERN(IEL30);
PROVIDE(IEL30 = DefaultHandler);
EXTERN(IEL31);
PROVIDE(IEL31 = DefaultHandler);
