// This file is autogenerated by ra-metapac-gen: do not edit by hand.
#[path = "../../peripherals/agt_16bits.rs"]
pub mod agt;
#[path = "../../peripherals/gpt_v1.rs"]
pub mod gpt;
#[path = "../../peripherals/icu_ra2l1.rs"]
pub mod icu;
#[path = "../../peripherals/mstp_v1.rs"]
pub mod mstp;
#[path = "../../peripherals/pfs_v1.rs"]
pub mod pfs;
#[path = "../../peripherals/port_v1.rs"]
pub mod port;
#[path = "../../peripherals/sysc_v1.rs"]
pub mod sysc;

pub const AGT0: agt::Agt = unsafe { agt::Agt::from_ptr(0x40084000usize as _) };
pub const AGT1: agt::Agt = unsafe { agt::Agt::from_ptr(0x40084100usize as _) };
pub const GPT0: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40078000usize as _) };
pub const GPT1: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40078100usize as _) };
pub const GPT2: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40078200usize as _) };
pub const GPT3: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40078300usize as _) };
pub const GPT4: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40078400usize as _) };
pub const GPT5: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40078500usize as _) };
pub const GPT6: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40078600usize as _) };
pub const GPT7: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40078700usize as _) };
pub const GPT8: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40078800usize as _) };
pub const GPT9: gpt::Gpt = unsafe { gpt::Gpt::from_ptr(0x40078900usize as _) };
pub const ICU: icu::Icu = unsafe { icu::Icu::from_ptr(0x40006000usize as _) };
pub const MSTP: mstp::Mstp = unsafe { mstp::Mstp::from_ptr(0x40047000usize as _) };
pub const PFS: pfs::Pfs = unsafe { pfs::Pfs::from_ptr(0x40040800usize as _) };
pub const PORT0: port::PortExtended = unsafe { port::PortExtended::from_ptr(0x40040000usize as _) };
pub const PORT1: port::PortExtended = unsafe { port::PortExtended::from_ptr(0x40040020usize as _) };
pub const PORT2: port::PortExtended = unsafe { port::PortExtended::from_ptr(0x40040040usize as _) };
pub const PORT3: port::PortExtended = unsafe { port::PortExtended::from_ptr(0x40040060usize as _) };
pub const PORT4: port::PortExtended = unsafe { port::PortExtended::from_ptr(0x40040080usize as _) };
pub const PORT5: port::PortExtended = unsafe { port::PortExtended::from_ptr(0x400400a0usize as _) };
pub const PORT6: port::PortExtended = unsafe { port::PortExtended::from_ptr(0x400400c0usize as _) };
pub const PORT7: port::PortExtended = unsafe { port::PortExtended::from_ptr(0x400400e0usize as _) };
pub const PORT8: port::PortExtended = unsafe { port::PortExtended::from_ptr(0x40040100usize as _) };
pub const SYSC: sysc::Sysc = unsafe { sysc::Sysc::from_ptr(0x4001e000usize as _) };

#[macro_export]
macro_rules! foreach_event {
    ($($m:tt)*) => {
        $($m)*! {
            (Acmplp0Int, 9, (0, 4, 8, 12, 16, 20, 24, 28)),
            (Acmplp1Int, 7, (1, 5, 9, 13, 17, 21, 25, 29)),
            (Adc0CompareMatch, 8, (0, 4, 8, 12, 16, 20, 24, 28)),
            (Adc0CompareMismatch, 6, (1, 5, 9, 13, 17, 21, 25, 29)),
            (Adc0ScanEnd, 7, (0, 4, 8, 12, 16, 20, 24, 28)),
            (Adc0ScanEndB, 5, (1, 9, 17, 25)),
            (Adc0WindowA, 5, (2, 6, 10, 14, 18, 22, 26, 30)),
            (Adc0WindowB, 5, (3, 7, 11, 15, 19, 23, 27, 31)),
            (AesRdreq, 18, (1, 5, 9, 13, 17, 21, 25, 29)),
            (AesWrreq, 21, (0, 4, 8, 12, 16, 20, 24, 28)),
            (Agt0CompareA, 22, (0, 8, 16, 24)),
            (Agt0CompareB, 19, (1, 9, 17, 25)),
            (Agt0Int, 17, (3, 11, 19, 27)),
            (Agt1CompareA, 3, (1, 5, 9, 13, 17, 21, 25, 29)),
            (Agt1CompareB, 3, (2, 6, 10, 14, 18, 22, 26, 30)),
            (Agt1Int, 5, (0, 4, 8, 12, 16, 20, 24, 28)),
            (CacFrequencyError, 11, (1, 5, 9, 13, 17, 21, 25, 29)),
            (CacMeasurementEnd, 8, (2, 6, 10, 14, 18, 22, 26, 30)),
            (CacOverflow, 8, (3, 7, 11, 15, 19, 23, 27, 31)),
            (Can0Error, 12, (0, 4, 8, 12, 16, 20, 24, 28)),
            (Can0FifoRx, 12, (1, 5, 9, 13, 17, 21, 25, 29)),
            (Can0FifoTx, 9, (2, 6, 10, 14, 18, 22, 26, 30)),
            (Can0MailboxRx, 9, (3, 7, 11, 15, 19, 23, 27, 31)),
            (Can0MailboxTx, 13, (0, 4, 8, 12, 16, 20, 24, 28)),
            (CgcMoscStop, 20, (6, 14, 22, 30)),
            (CtsuEnd, 7, (3, 7, 11, 15, 19, 23, 27, 31)),
            (CtsuRead, 7, (2, 6, 10, 14, 18, 22, 26, 30)),
            (CtsuWrite, 9, (1, 5, 9, 13, 17, 21, 25, 29)),
            (DocInt, 10, (1, 5, 9, 13, 17, 21, 25, 29)),
            (DtcComplete, 2, (0, 4, 8, 12, 16, 20, 24, 28)),
            (DtcEnd, 10, ()),
            (ElcSoftwareEvent0, 10, (2, 6, 10, 14, 18, 22, 26, 30)),
            (ElcSoftwareEvent1, 10, (3, 7, 11, 15, 19, 23, 27, 31)),
            (FcuFrdyi, 2, (2, 6, 10, 14, 18, 22, 26, 30)),
            (Gpt0CaptureCompareA, 14, (0, 4, 8, 12, 16, 20, 24, 28)),
            (Gpt0CaptureCompareB, 13, (1, 5, 9, 13, 17, 21, 25, 29)),
            (Gpt0CompareC, 12, (2, 6, 10, 14, 18, 22, 26, 30)),
            (Gpt0CompareD, 12, (3, 7, 11, 15, 19, 23, 27, 31)),
            (Gpt0CounterOverflow, 15, (0, 4, 8, 12, 16, 20, 24, 28)),
            (Gpt0CounterUnderflow, 14, (1, 5, 9, 13, 17, 21, 25, 29)),
            (Gpt1CaptureCompareA, 25, (0, 8, 16, 24)),
            (Gpt1CaptureCompareB, 22, (1, 9, 17, 25)),
            (Gpt1CompareC, 20, (2, 10, 18, 26)),
            (Gpt1CompareD, 18, (3, 11, 19, 27)),
            (Gpt1CounterOverflow, 24, (4, 12, 20, 28)),
            (Gpt1CounterUnderflow, 21, (5, 13, 21, 29)),
            (Gpt2CaptureCompareA, 16, (0, 4, 8, 12, 16, 20, 24, 28)),
            (Gpt2CaptureCompareB, 15, (1, 5, 9, 13, 17, 21, 25, 29)),
            (Gpt2CompareC, 13, (2, 6, 10, 14, 18, 22, 26, 30)),
            (Gpt2CompareD, 13, (3, 7, 11, 15, 19, 23, 27, 31)),
            (Gpt2CounterOverflow, 14, (2, 6, 10, 14, 18, 22, 26, 30)),
            (Gpt2CounterUnderflow, 14, (3, 7, 11, 15, 19, 23, 27, 31)),
            (Gpt3CaptureCompareA, 25, (4, 12, 20, 28)),
            (Gpt3CaptureCompareB, 22, (5, 13, 21, 29)),
            (Gpt3CompareC, 21, (6, 14, 22, 30)),
            (Gpt3CompareD, 18, (7, 15, 23, 31)),
            (Gpt3CounterOverflow, 26, (0, 8, 16, 24)),
            (Gpt3CounterUnderflow, 23, (1, 9, 17, 25)),
            (Gpt4CaptureCompareA, 27, (0, 8, 16, 24)),
            (Gpt4CaptureCompareB, 24, (1, 9, 17, 25)),
            (Gpt4CompareC, 21, (2, 10, 18, 26)),
            (Gpt4CompareD, 19, (3, 11, 19, 27)),
            (Gpt4CounterOverflow, 22, (6, 14, 22, 30)),
            (Gpt4CounterUnderflow, 19, (7, 15, 23, 31)),
            (Gpt5CaptureCompareA, 26, (4, 12, 20, 28)),
            (Gpt5CaptureCompareB, 23, (5, 13, 21, 29)),
            (Gpt5CompareC, 23, (6, 14, 22, 30)),
            (Gpt5CompareD, 20, (7, 15, 23, 31)),
            (Gpt5CounterOverflow, 22, (2, 10, 18, 26)),
            (Gpt5CounterUnderflow, 20, (3, 11, 19, 27)),
            (Gpt6CaptureCompareA, 28, (0, 8, 16, 24)),
            (Gpt6CaptureCompareB, 25, (1, 9, 17, 25)),
            (Gpt6CompareC, 23, (2, 10, 18, 26)),
            (Gpt6CompareD, 21, (3, 11, 19, 27)),
            (Gpt6CounterOverflow, 24, (6, 14, 22, 30)),
            (Gpt6CounterUnderflow, 21, (7, 15, 23, 31)),
            (Gpt7CaptureCompareA, 27, (4, 12, 20, 28)),
            (Gpt7CaptureCompareB, 24, (5, 13, 21, 29)),
            (Gpt7CompareC, 25, (6, 14, 22, 30)),
            (Gpt7CompareD, 22, (7, 15, 23, 31)),
            (Gpt7CounterOverflow, 24, (2, 10, 18, 26)),
            (Gpt7CounterUnderflow, 22, (3, 11, 19, 27)),
            (Gpt8CaptureCompareA, 29, (0, 8, 16, 24)),
            (Gpt8CaptureCompareB, 26, (1, 9, 17, 25)),
            (Gpt8CompareC, 25, (2, 10, 18, 26)),
            (Gpt8CompareD, 23, (3, 11, 19, 27)),
            (Gpt8CounterOverflow, 26, (6, 14, 22, 30)),
            (Gpt8CounterUnderflow, 23, (7, 15, 23, 31)),
            (Gpt9CaptureCompareA, 28, (4, 12, 20, 28)),
            (Gpt9CaptureCompareB, 25, (5, 13, 21, 29)),
            (Gpt9CompareC, 27, (6, 14, 22, 30)),
            (Gpt9CompareD, 24, (7, 15, 23, 31)),
            (Gpt9CounterOverflow, 26, (2, 10, 18, 26)),
            (Gpt9CounterUnderflow, 24, (3, 11, 19, 27)),
            (GptUvwedge, 17, (0, 4, 8, 12, 16, 20, 24, 28)),
            (IcuIrq0, 1, (0, 4, 8, 12, 16, 20, 24, 28)),
            (IcuIrq1, 1, (1, 5, 9, 13, 17, 21, 25, 29)),
            (IcuIrq2, 1, (2, 6, 10, 14, 18, 22, 26, 30)),
            (IcuIrq3, 1, (3, 7, 11, 15, 19, 23, 27, 31)),
            (IcuIrq4, 22, (4, 12, 20, 28)),
            (IcuIrq5, 19, (5, 13, 21, 29)),
            (IcuIrq6, 19, (6, 14, 22, 30)),
            (IcuIrq7, 17, (7, 15, 23, 31)),
            (IcuSnoozeCancel, 3, (0, 4, 8, 12, 16, 20, 24, 28)),
            (Iic0Eri, 6, (3, 7, 11, 15, 19, 23, 27, 31)),
            (Iic0Rxi, 10, (0, 4, 8, 12, 16, 20, 24, 28)),
            (Iic0Tei, 6, (2, 6, 10, 14, 18, 22, 26, 30)),
            (Iic0Txi, 8, (1, 5, 9, 13, 17, 21, 25, 29)),
            (Iic0Wui, 11, (0, 4, 8, 12, 16, 20, 24, 28)),
            (Iic1Eri, 20, (5, 13, 21, 29)),
            (Iic1Rxi, 23, (0, 8, 16, 24)),
            (Iic1Tei, 23, (4, 12, 20, 28)),
            (Iic1Txi, 20, (1, 9, 17, 25)),
            (IoportEvent1, 21, (1, 9, 17, 25)),
            (IoportEvent2, 19, (2, 10, 18, 26)),
            (IwdtUnderflow, 3, (3, 7, 11, 15, 19, 23, 27, 31)),
            (KeyInt, 24, (0, 8, 16, 24)),
            (LpmSnoozeRequest, 2, (3, 7, 11, 15, 19, 23, 27, 31)),
            (LvdLvd1, 4, (0, 4, 8, 12, 16, 20, 24, 28)),
            (LvdLvd2, 2, (1, 5, 9, 13, 17, 21, 25, 29)),
            (Poeg0Event, 11, (2, 6, 10, 14, 18, 22, 26, 30)),
            (Poeg1Event, 11, (3, 7, 11, 15, 19, 23, 27, 31)),
            (RtcAlarm, 4, (1, 5, 9, 13, 17, 21, 25, 29)),
            (RtcCarry, 4, (3, 7, 11, 15, 19, 23, 27, 31)),
            (RtcPeriod, 4, (2, 6, 10, 14, 18, 22, 26, 30)),
            (Sci0Am, 19, (0, 4, 8, 12, 16, 20, 24, 28)),
            (Sci0Eri, 15, (3, 7, 11, 15, 19, 23, 27, 31)),
            (Sci0Rxi, 18, (0, 4, 8, 12, 16, 20, 24, 28)),
            (Sci0RxiOrEri, 118, ()),
            (Sci0Tei, 15, (2, 6, 10, 14, 18, 22, 26, 30)),
            (Sci0Txi, 16, (1, 5, 9, 13, 17, 21, 25, 29)),
            (Sci1Am, 26, (5, 13, 21, 29)),
            (Sci1Eri, 25, (3, 11, 19, 27)),
            (Sci1Rxi, 30, (0, 8, 16, 24)),
            (Sci1Tei, 27, (2, 10, 18, 26)),
            (Sci1Txi, 27, (1, 9, 17, 25)),
            (Sci2Am, 28, (1, 9, 17, 25)),
            (Sci2Eri, 25, (7, 15, 23, 31)),
            (Sci2Rxi, 29, (4, 12, 20, 28)),
            (Sci2Tei, 28, (6, 14, 22, 30)),
            (Sci2Txi, 27, (5, 13, 21, 29)),
            (Sci3Am, 29, (6, 14, 22, 30)),
            (Sci3Eri, 26, (3, 11, 19, 27)),
            (Sci3Rxi, 31, (0, 8, 16, 24)),
            (Sci3Tei, 28, (2, 10, 18, 26)),
            (Sci3Txi, 29, (1, 9, 17, 25)),
            (Sci9Am, 27, (3, 11, 19, 27)),
            (Sci9Eri, 26, (7, 15, 23, 31)),
            (Sci9Rxi, 30, (4, 12, 20, 28)),
            (Sci9Tei, 30, (6, 14, 22, 30)),
            (Sci9Txi, 28, (5, 13, 21, 29)),
            (Spi0Eri, 16, (3, 7, 11, 15, 19, 23, 27, 31)),
            (Spi0Idle, 16, (2, 6, 10, 14, 18, 22, 26, 30)),
            (Spi0Rxi, 20, (0, 4, 8, 12, 16, 20, 24, 28)),
            (Spi0Tei, 17, (2, 6, 10, 14, 18, 22, 26, 30)),
            (Spi0Txi, 17, (1, 5, 9, 13, 17, 21, 25, 29)),
            (Spi1Eri, 27, (7, 15, 23, 31)),
            (Spi1Idle, 29, (2, 10, 18, 26)),
            (Spi1Rxi, 31, (4, 12, 20, 28)),
            (Spi1Tei, 31, (6, 14, 22, 30)),
            (Spi1Txi, 29, (5, 13, 21, 29)),
            (TrngRdreq, 18, (2, 6, 10, 14, 18, 22, 26, 30)),
            (WdtUnderflow, 6, (0, 4, 8, 12, 16, 20, 24, 28)),
        }
    };
}
#[macro_export]
macro_rules! foreach_peripheral {
    ($m:path) => {
        $m! {
            AGT0 = 0,
            AGT1 = 1,
            GPT0 = 2,
            GPT1 = 3,
            GPT2 = 4,
            GPT3 = 5,
            GPT4 = 6,
            GPT5 = 7,
            GPT6 = 8,
            GPT7 = 9,
            GPT8 = 10,
            GPT9 = 11,
            ICU = 12,
            MSTP = 13,
            PFS = 14,
            PORT0 = 15,
            PORT1 = 16,
            PORT2 = 17,
            PORT3 = 18,
            PORT4 = 19,
            PORT5 = 20,
            PORT6 = 21,
            PORT7 = 22,
            PORT8 = 23,
            SYSC = 24,
        }
    };
}
#[macro_export]
macro_rules! foreach_pin {
    ($m:path) => {
        $m! {
            (P000, 0, 0),
            (P001, 0, 1),
            (P002, 0, 2),
            (P003, 0, 3),
            (P004, 0, 4),
            (P005, 0, 5),
            (P006, 0, 6),
            (P007, 0, 7),
            (P008, 0, 8),
            (P010, 0, 10),
            (P011, 0, 11),
            (P012, 0, 12),
            (P013, 0, 13),
            (P014, 0, 14),
            (P015, 0, 15),
            (P100, 1, 0),
            (P101, 1, 1),
            (P102, 1, 2),
            (P103, 1, 3),
            (P104, 1, 4),
            (P105, 1, 5),
            (P106, 1, 6),
            (P107, 1, 7),
            (P108, 1, 8),
            (P109, 1, 9),
            (P110, 1, 10),
            (P111, 1, 11),
            (P112, 1, 12),
            (P113, 1, 13),
            (P114, 1, 14),
            (P115, 1, 15),
            (P200, 2, 0),
            (P201, 2, 1),
            (P202, 2, 2),
            (P203, 2, 3),
            (P204, 2, 4),
            (P205, 2, 5),
            (P206, 2, 6),
            (P207, 2, 7),
            (P208, 2, 8),
            (P212, 2, 12),
            (P213, 2, 13),
            (P214, 2, 14),
            (P215, 2, 15),
            (P300, 3, 0),
            (P301, 3, 1),
            (P302, 3, 2),
            (P303, 3, 3),
            (P304, 3, 4),
            (P305, 3, 5),
            (P306, 3, 6),
            (P307, 3, 7),
            (P400, 4, 0),
            (P401, 4, 1),
            (P402, 4, 2),
            (P403, 4, 3),
            (P404, 4, 4),
            (P405, 4, 5),
            (P406, 4, 6),
            (P407, 4, 7),
            (P408, 4, 8),
            (P409, 4, 9),
            (P410, 4, 10),
            (P411, 4, 11),
            (P412, 4, 12),
            (P413, 4, 13),
            (P414, 4, 14),
            (P415, 4, 15),
            (P500, 5, 0),
            (P501, 5, 1),
            (P502, 5, 2),
            (P503, 5, 3),
            (P504, 5, 4),
            (P505, 5, 5),
            (P600, 6, 0),
            (P601, 6, 1),
            (P602, 6, 2),
            (P603, 6, 3),
            (P608, 6, 8),
            (P609, 6, 9),
            (P610, 6, 10),
            (P708, 7, 8),
            (P714, 7, 14),
            (P808, 8, 8),
            (P809, 8, 9),
        }
    };
}
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Event {
    /// group0 (IELSR[0, 8, 16, 24]) / group4 (IELSR[4, 12, 20, 28])
    Acmplp0Int = 9,
    /// group1 (IELSR[1, 9, 17, 25]) / group5 (IELSR[5, 13, 21, 29])
    Acmplp1Int = 7,
    /// group0 (IELSR[0, 8, 16, 24]) / group4 (IELSR[4, 12, 20, 28])
    Adc0CompareMatch = 8,
    /// group1 (IELSR[1, 9, 17, 25]) / group5 (IELSR[5, 13, 21, 29])
    Adc0CompareMismatch = 6,
    /// group1 (IELSR[1, 9, 17, 25])
    Adc0ScanEndB = 5,
    /// group1 (IELSR[1, 9, 17, 25]) / group5 (IELSR[5, 13, 21, 29])
    AesRdreq = 18,
    /// group0 (IELSR[0, 8, 16, 24]) / group4 (IELSR[4, 12, 20, 28])
    AesWrreq = 21,
    /// group0 (IELSR[0, 8, 16, 24])
    Agt0CompareA = 22,
    /// group1 (IELSR[1, 9, 17, 25])
    Agt0CompareB = 19,
    /// group3 (IELSR[3, 11, 19, 27])
    Agt0Int = 17,
    /// group1 (IELSR[1, 9, 17, 25]) / group5 (IELSR[5, 13, 21, 29])
    Agt1CompareA = 3,
    /// group1 (IELSR[1, 9, 17, 25]) / group5 (IELSR[5, 13, 21, 29])
    CacFrequencyError = 11,
    /// group0 (IELSR[0, 8, 16, 24]) / group4 (IELSR[4, 12, 20, 28])
    Can0Error = 12,
    /// group0 (IELSR[0, 8, 16, 24]) / group4 (IELSR[4, 12, 20, 28])
    Can0MailboxTx = 13,
    /// group6 (IELSR[6, 14, 22, 30])
    CgcMoscStop = 20,
    /// group1 (IELSR[1, 9, 17, 25]) / group5 (IELSR[5, 13, 21, 29])
    DocInt = 10,
    /// group0 (IELSR[0, 8, 16, 24]) / group4 (IELSR[4, 12, 20, 28])
    DtcComplete = 2,
    /// group0 (IELSR[0, 8, 16, 24]) / group4 (IELSR[4, 12, 20, 28])
    Gpt0CaptureCompareA = 14,
    /// group0 (IELSR[0, 8, 16, 24]) / group4 (IELSR[4, 12, 20, 28])
    Gpt0CounterOverflow = 15,
    /// group0 (IELSR[0, 8, 16, 24])
    Gpt1CaptureCompareA = 25,
    /// group4 (IELSR[4, 12, 20, 28])
    Gpt1CounterOverflow = 24,
    /// group0 (IELSR[0, 8, 16, 24]) / group4 (IELSR[4, 12, 20, 28])
    Gpt2CaptureCompareA = 16,
    /// group0 (IELSR[0, 8, 16, 24])
    Gpt3CounterOverflow = 26,
    /// group1 (IELSR[1, 9, 17, 25])
    Gpt3CounterUnderflow = 23,
    /// group0 (IELSR[0, 8, 16, 24])
    Gpt4CaptureCompareA = 27,
    /// group0 (IELSR[0, 8, 16, 24])
    Gpt6CaptureCompareA = 28,
    /// group0 (IELSR[0, 8, 16, 24])
    Gpt8CaptureCompareA = 29,
    /// group0 (IELSR[0, 8, 16, 24]) / group4 (IELSR[4, 12, 20, 28])
    IcuIrq0 = 1,
    /// group0 (IELSR[0, 8, 16, 24]) / group4 (IELSR[4, 12, 20, 28])
    LvdLvd1 = 4,
    /// Receive data full/Receive error
    Sci0RxiOrEri = 118,
    /// group0 (IELSR[0, 8, 16, 24])
    Sci1Rxi = 30,
    /// group0 (IELSR[0, 8, 16, 24])
    Sci3Rxi = 31,
}
#[allow(non_upper_case_globals)]
impl Event {
    /// group0 (IELSR[0, 8, 16, 24]) / group4 (IELSR[4, 12, 20, 28])
    pub const Adc0ScanEnd: Self = Self::Acmplp1Int;
    /// group2 (IELSR[2, 10, 18, 26]) / group6 (IELSR[6, 14, 22, 30])
    pub const Adc0WindowA: Self = Self::Adc0ScanEndB;
    /// group3 (IELSR[3, 11, 19, 27]) / group7 (IELSR[7, 15, 23, 31])
    pub const Adc0WindowB: Self = Self::Adc0ScanEndB;
    /// group2 (IELSR[2, 10, 18, 26]) / group6 (IELSR[6, 14, 22, 30])
    pub const Agt1CompareB: Self = Self::Agt1CompareA;
    /// group0 (IELSR[0, 8, 16, 24]) / group4 (IELSR[4, 12, 20, 28])
    pub const Agt1Int: Self = Self::Adc0ScanEndB;
    /// group2 (IELSR[2, 10, 18, 26]) / group6 (IELSR[6, 14, 22, 30])
    pub const CacMeasurementEnd: Self = Self::Adc0CompareMatch;
    /// group3 (IELSR[3, 11, 19, 27]) / group7 (IELSR[7, 15, 23, 31])
    pub const CacOverflow: Self = Self::Adc0CompareMatch;
    /// group1 (IELSR[1, 9, 17, 25]) / group5 (IELSR[5, 13, 21, 29])
    pub const Can0FifoRx: Self = Self::Can0Error;
    /// group2 (IELSR[2, 10, 18, 26]) / group6 (IELSR[6, 14, 22, 30])
    pub const Can0FifoTx: Self = Self::Acmplp0Int;
    /// group3 (IELSR[3, 11, 19, 27]) / group7 (IELSR[7, 15, 23, 31])
    pub const Can0MailboxRx: Self = Self::Acmplp0Int;
    /// group3 (IELSR[3, 11, 19, 27]) / group7 (IELSR[7, 15, 23, 31])
    pub const CtsuEnd: Self = Self::Acmplp1Int;
    /// group2 (IELSR[2, 10, 18, 26]) / group6 (IELSR[6, 14, 22, 30])
    pub const CtsuRead: Self = Self::Acmplp1Int;
    /// group1 (IELSR[1, 9, 17, 25]) / group5 (IELSR[5, 13, 21, 29])
    pub const CtsuWrite: Self = Self::Acmplp0Int;
    /// DTC transfer end
    pub const DtcEnd: Self = Self::DocInt;
    /// group2 (IELSR[2, 10, 18, 26]) / group6 (IELSR[6, 14, 22, 30])
    pub const ElcSoftwareEvent0: Self = Self::DocInt;
    /// group3 (IELSR[3, 11, 19, 27]) / group7 (IELSR[7, 15, 23, 31])
    pub const ElcSoftwareEvent1: Self = Self::DocInt;
    /// group2 (IELSR[2, 10, 18, 26]) / group6 (IELSR[6, 14, 22, 30])
    pub const FcuFrdyi: Self = Self::DtcComplete;
    /// group1 (IELSR[1, 9, 17, 25]) / group5 (IELSR[5, 13, 21, 29])
    pub const Gpt0CaptureCompareB: Self = Self::Can0MailboxTx;
    /// group2 (IELSR[2, 10, 18, 26]) / group6 (IELSR[6, 14, 22, 30])
    pub const Gpt0CompareC: Self = Self::Can0Error;
    /// group3 (IELSR[3, 11, 19, 27]) / group7 (IELSR[7, 15, 23, 31])
    pub const Gpt0CompareD: Self = Self::Can0Error;
    /// group1 (IELSR[1, 9, 17, 25]) / group5 (IELSR[5, 13, 21, 29])
    pub const Gpt0CounterUnderflow: Self = Self::Gpt0CaptureCompareA;
    /// group1 (IELSR[1, 9, 17, 25])
    pub const Gpt1CaptureCompareB: Self = Self::Agt0CompareA;
    /// group2 (IELSR[2, 10, 18, 26])
    pub const Gpt1CompareC: Self = Self::CgcMoscStop;
    /// group3 (IELSR[3, 11, 19, 27])
    pub const Gpt1CompareD: Self = Self::AesRdreq;
    /// group5 (IELSR[5, 13, 21, 29])
    pub const Gpt1CounterUnderflow: Self = Self::AesWrreq;
    /// group1 (IELSR[1, 9, 17, 25]) / group5 (IELSR[5, 13, 21, 29])
    pub const Gpt2CaptureCompareB: Self = Self::Gpt0CounterOverflow;
    /// group2 (IELSR[2, 10, 18, 26]) / group6 (IELSR[6, 14, 22, 30])
    pub const Gpt2CompareC: Self = Self::Can0MailboxTx;
    /// group3 (IELSR[3, 11, 19, 27]) / group7 (IELSR[7, 15, 23, 31])
    pub const Gpt2CompareD: Self = Self::Can0MailboxTx;
    /// group2 (IELSR[2, 10, 18, 26]) / group6 (IELSR[6, 14, 22, 30])
    pub const Gpt2CounterOverflow: Self = Self::Gpt0CaptureCompareA;
    /// group3 (IELSR[3, 11, 19, 27]) / group7 (IELSR[7, 15, 23, 31])
    pub const Gpt2CounterUnderflow: Self = Self::Gpt0CaptureCompareA;
    /// group4 (IELSR[4, 12, 20, 28])
    pub const Gpt3CaptureCompareA: Self = Self::Gpt1CaptureCompareA;
    /// group5 (IELSR[5, 13, 21, 29])
    pub const Gpt3CaptureCompareB: Self = Self::Agt0CompareA;
    /// group6 (IELSR[6, 14, 22, 30])
    pub const Gpt3CompareC: Self = Self::AesWrreq;
    /// group7 (IELSR[7, 15, 23, 31])
    pub const Gpt3CompareD: Self = Self::AesRdreq;
    /// group1 (IELSR[1, 9, 17, 25])
    pub const Gpt4CaptureCompareB: Self = Self::Gpt1CounterOverflow;
    /// group2 (IELSR[2, 10, 18, 26])
    pub const Gpt4CompareC: Self = Self::AesWrreq;
    /// group3 (IELSR[3, 11, 19, 27])
    pub const Gpt4CompareD: Self = Self::Agt0CompareB;
    /// group6 (IELSR[6, 14, 22, 30])
    pub const Gpt4CounterOverflow: Self = Self::Agt0CompareA;
    /// group7 (IELSR[7, 15, 23, 31])
    pub const Gpt4CounterUnderflow: Self = Self::Agt0CompareB;
    /// group4 (IELSR[4, 12, 20, 28])
    pub const Gpt5CaptureCompareA: Self = Self::Gpt3CounterOverflow;
    /// group5 (IELSR[5, 13, 21, 29])
    pub const Gpt5CaptureCompareB: Self = Self::Gpt3CounterUnderflow;
    /// group6 (IELSR[6, 14, 22, 30])
    pub const Gpt5CompareC: Self = Self::Gpt3CounterUnderflow;
    /// group7 (IELSR[7, 15, 23, 31])
    pub const Gpt5CompareD: Self = Self::CgcMoscStop;
    /// group2 (IELSR[2, 10, 18, 26])
    pub const Gpt5CounterOverflow: Self = Self::Agt0CompareA;
    /// group3 (IELSR[3, 11, 19, 27])
    pub const Gpt5CounterUnderflow: Self = Self::CgcMoscStop;
    /// group1 (IELSR[1, 9, 17, 25])
    pub const Gpt6CaptureCompareB: Self = Self::Gpt1CaptureCompareA;
    /// group2 (IELSR[2, 10, 18, 26])
    pub const Gpt6CompareC: Self = Self::Gpt3CounterUnderflow;
    /// group3 (IELSR[3, 11, 19, 27])
    pub const Gpt6CompareD: Self = Self::AesWrreq;
    /// group6 (IELSR[6, 14, 22, 30])
    pub const Gpt6CounterOverflow: Self = Self::Gpt1CounterOverflow;
    /// group7 (IELSR[7, 15, 23, 31])
    pub const Gpt6CounterUnderflow: Self = Self::AesWrreq;
    /// group4 (IELSR[4, 12, 20, 28])
    pub const Gpt7CaptureCompareA: Self = Self::Gpt4CaptureCompareA;
    /// group5 (IELSR[5, 13, 21, 29])
    pub const Gpt7CaptureCompareB: Self = Self::Gpt1CounterOverflow;
    /// group6 (IELSR[6, 14, 22, 30])
    pub const Gpt7CompareC: Self = Self::Gpt1CaptureCompareA;
    /// group7 (IELSR[7, 15, 23, 31])
    pub const Gpt7CompareD: Self = Self::Agt0CompareA;
    /// group2 (IELSR[2, 10, 18, 26])
    pub const Gpt7CounterOverflow: Self = Self::Gpt1CounterOverflow;
    /// group3 (IELSR[3, 11, 19, 27])
    pub const Gpt7CounterUnderflow: Self = Self::Agt0CompareA;
    /// group1 (IELSR[1, 9, 17, 25])
    pub const Gpt8CaptureCompareB: Self = Self::Gpt3CounterOverflow;
    /// group2 (IELSR[2, 10, 18, 26])
    pub const Gpt8CompareC: Self = Self::Gpt1CaptureCompareA;
    /// group3 (IELSR[3, 11, 19, 27])
    pub const Gpt8CompareD: Self = Self::Gpt3CounterUnderflow;
    /// group6 (IELSR[6, 14, 22, 30])
    pub const Gpt8CounterOverflow: Self = Self::Gpt3CounterOverflow;
    /// group7 (IELSR[7, 15, 23, 31])
    pub const Gpt8CounterUnderflow: Self = Self::Gpt3CounterUnderflow;
    /// group4 (IELSR[4, 12, 20, 28])
    pub const Gpt9CaptureCompareA: Self = Self::Gpt6CaptureCompareA;
    /// group5 (IELSR[5, 13, 21, 29])
    pub const Gpt9CaptureCompareB: Self = Self::Gpt1CaptureCompareA;
    /// group6 (IELSR[6, 14, 22, 30])
    pub const Gpt9CompareC: Self = Self::Gpt4CaptureCompareA;
    /// group7 (IELSR[7, 15, 23, 31])
    pub const Gpt9CompareD: Self = Self::Gpt1CounterOverflow;
    /// group2 (IELSR[2, 10, 18, 26])
    pub const Gpt9CounterOverflow: Self = Self::Gpt3CounterOverflow;
    /// group3 (IELSR[3, 11, 19, 27])
    pub const Gpt9CounterUnderflow: Self = Self::Gpt1CounterOverflow;
    /// group0 (IELSR[0, 8, 16, 24]) / group4 (IELSR[4, 12, 20, 28])
    pub const GptUvwedge: Self = Self::Agt0Int;
    /// group1 (IELSR[1, 9, 17, 25]) / group5 (IELSR[5, 13, 21, 29])
    pub const IcuIrq1: Self = Self::IcuIrq0;
    /// group2 (IELSR[2, 10, 18, 26]) / group6 (IELSR[6, 14, 22, 30])
    pub const IcuIrq2: Self = Self::IcuIrq0;
    /// group3 (IELSR[3, 11, 19, 27]) / group7 (IELSR[7, 15, 23, 31])
    pub const IcuIrq3: Self = Self::IcuIrq0;
    /// group4 (IELSR[4, 12, 20, 28])
    pub const IcuIrq4: Self = Self::Agt0CompareA;
    /// group5 (IELSR[5, 13, 21, 29])
    pub const IcuIrq5: Self = Self::Agt0CompareB;
    /// group6 (IELSR[6, 14, 22, 30])
    pub const IcuIrq6: Self = Self::Agt0CompareB;
    /// group7 (IELSR[7, 15, 23, 31])
    pub const IcuIrq7: Self = Self::Agt0Int;
    /// group0 (IELSR[0, 8, 16, 24]) / group4 (IELSR[4, 12, 20, 28])
    pub const IcuSnoozeCancel: Self = Self::Agt1CompareA;
    /// group3 (IELSR[3, 11, 19, 27]) / group7 (IELSR[7, 15, 23, 31])
    pub const Iic0Eri: Self = Self::Adc0CompareMismatch;
    /// group0 (IELSR[0, 8, 16, 24]) / group4 (IELSR[4, 12, 20, 28])
    pub const Iic0Rxi: Self = Self::DocInt;
    /// group2 (IELSR[2, 10, 18, 26]) / group6 (IELSR[6, 14, 22, 30])
    pub const Iic0Tei: Self = Self::Adc0CompareMismatch;
    /// group1 (IELSR[1, 9, 17, 25]) / group5 (IELSR[5, 13, 21, 29])
    pub const Iic0Txi: Self = Self::Adc0CompareMatch;
    /// group0 (IELSR[0, 8, 16, 24]) / group4 (IELSR[4, 12, 20, 28])
    pub const Iic0Wui: Self = Self::CacFrequencyError;
    /// group5 (IELSR[5, 13, 21, 29])
    pub const Iic1Eri: Self = Self::CgcMoscStop;
    /// group0 (IELSR[0, 8, 16, 24])
    pub const Iic1Rxi: Self = Self::Gpt3CounterUnderflow;
    /// group4 (IELSR[4, 12, 20, 28])
    pub const Iic1Tei: Self = Self::Gpt3CounterUnderflow;
    /// group1 (IELSR[1, 9, 17, 25])
    pub const Iic1Txi: Self = Self::CgcMoscStop;
    /// group1 (IELSR[1, 9, 17, 25])
    pub const IoportEvent1: Self = Self::AesWrreq;
    /// group2 (IELSR[2, 10, 18, 26])
    pub const IoportEvent2: Self = Self::Agt0CompareB;
    /// group3 (IELSR[3, 11, 19, 27]) / group7 (IELSR[7, 15, 23, 31])
    pub const IwdtUnderflow: Self = Self::Agt1CompareA;
    /// group0 (IELSR[0, 8, 16, 24])
    pub const KeyInt: Self = Self::Gpt1CounterOverflow;
    /// group3 (IELSR[3, 11, 19, 27]) / group7 (IELSR[7, 15, 23, 31])
    pub const LpmSnoozeRequest: Self = Self::DtcComplete;
    /// group1 (IELSR[1, 9, 17, 25]) / group5 (IELSR[5, 13, 21, 29])
    pub const LvdLvd2: Self = Self::DtcComplete;
    /// group2 (IELSR[2, 10, 18, 26]) / group6 (IELSR[6, 14, 22, 30])
    pub const Poeg0Event: Self = Self::CacFrequencyError;
    /// group3 (IELSR[3, 11, 19, 27]) / group7 (IELSR[7, 15, 23, 31])
    pub const Poeg1Event: Self = Self::CacFrequencyError;
    /// group1 (IELSR[1, 9, 17, 25]) / group5 (IELSR[5, 13, 21, 29])
    pub const RtcAlarm: Self = Self::LvdLvd1;
    /// group3 (IELSR[3, 11, 19, 27]) / group7 (IELSR[7, 15, 23, 31])
    pub const RtcCarry: Self = Self::LvdLvd1;
    /// group2 (IELSR[2, 10, 18, 26]) / group6 (IELSR[6, 14, 22, 30])
    pub const RtcPeriod: Self = Self::LvdLvd1;
    /// group0 (IELSR[0, 8, 16, 24]) / group4 (IELSR[4, 12, 20, 28])
    pub const Sci0Am: Self = Self::Agt0CompareB;
    /// group3 (IELSR[3, 11, 19, 27]) / group7 (IELSR[7, 15, 23, 31])
    pub const Sci0Eri: Self = Self::Gpt0CounterOverflow;
    /// group0 (IELSR[0, 8, 16, 24]) / group4 (IELSR[4, 12, 20, 28])
    pub const Sci0Rxi: Self = Self::AesRdreq;
    /// group2 (IELSR[2, 10, 18, 26]) / group6 (IELSR[6, 14, 22, 30])
    pub const Sci0Tei: Self = Self::Gpt0CounterOverflow;
    /// group1 (IELSR[1, 9, 17, 25]) / group5 (IELSR[5, 13, 21, 29])
    pub const Sci0Txi: Self = Self::Gpt2CaptureCompareA;
    /// group5 (IELSR[5, 13, 21, 29])
    pub const Sci1Am: Self = Self::Gpt3CounterOverflow;
    /// group3 (IELSR[3, 11, 19, 27])
    pub const Sci1Eri: Self = Self::Gpt1CaptureCompareA;
    /// group2 (IELSR[2, 10, 18, 26])
    pub const Sci1Tei: Self = Self::Gpt4CaptureCompareA;
    /// group1 (IELSR[1, 9, 17, 25])
    pub const Sci1Txi: Self = Self::Gpt4CaptureCompareA;
    /// group1 (IELSR[1, 9, 17, 25])
    pub const Sci2Am: Self = Self::Gpt6CaptureCompareA;
    /// group7 (IELSR[7, 15, 23, 31])
    pub const Sci2Eri: Self = Self::Gpt1CaptureCompareA;
    /// group4 (IELSR[4, 12, 20, 28])
    pub const Sci2Rxi: Self = Self::Gpt8CaptureCompareA;
    /// group6 (IELSR[6, 14, 22, 30])
    pub const Sci2Tei: Self = Self::Gpt6CaptureCompareA;
    /// group5 (IELSR[5, 13, 21, 29])
    pub const Sci2Txi: Self = Self::Gpt4CaptureCompareA;
    /// group6 (IELSR[6, 14, 22, 30])
    pub const Sci3Am: Self = Self::Gpt8CaptureCompareA;
    /// group3 (IELSR[3, 11, 19, 27])
    pub const Sci3Eri: Self = Self::Gpt3CounterOverflow;
    /// group2 (IELSR[2, 10, 18, 26])
    pub const Sci3Tei: Self = Self::Gpt6CaptureCompareA;
    /// group1 (IELSR[1, 9, 17, 25])
    pub const Sci3Txi: Self = Self::Gpt8CaptureCompareA;
    /// group3 (IELSR[3, 11, 19, 27])
    pub const Sci9Am: Self = Self::Gpt4CaptureCompareA;
    /// group7 (IELSR[7, 15, 23, 31])
    pub const Sci9Eri: Self = Self::Gpt3CounterOverflow;
    /// group4 (IELSR[4, 12, 20, 28])
    pub const Sci9Rxi: Self = Self::Sci1Rxi;
    /// group6 (IELSR[6, 14, 22, 30])
    pub const Sci9Tei: Self = Self::Sci1Rxi;
    /// group5 (IELSR[5, 13, 21, 29])
    pub const Sci9Txi: Self = Self::Gpt6CaptureCompareA;
    /// group3 (IELSR[3, 11, 19, 27]) / group7 (IELSR[7, 15, 23, 31])
    pub const Spi0Eri: Self = Self::Gpt2CaptureCompareA;
    /// group2 (IELSR[2, 10, 18, 26]) / group6 (IELSR[6, 14, 22, 30])
    pub const Spi0Idle: Self = Self::Gpt2CaptureCompareA;
    /// group0 (IELSR[0, 8, 16, 24]) / group4 (IELSR[4, 12, 20, 28])
    pub const Spi0Rxi: Self = Self::CgcMoscStop;
    /// group2 (IELSR[2, 10, 18, 26]) / group6 (IELSR[6, 14, 22, 30])
    pub const Spi0Tei: Self = Self::Agt0Int;
    /// group1 (IELSR[1, 9, 17, 25]) / group5 (IELSR[5, 13, 21, 29])
    pub const Spi0Txi: Self = Self::Agt0Int;
    /// group7 (IELSR[7, 15, 23, 31])
    pub const Spi1Eri: Self = Self::Gpt4CaptureCompareA;
    /// group2 (IELSR[2, 10, 18, 26])
    pub const Spi1Idle: Self = Self::Gpt8CaptureCompareA;
    /// group4 (IELSR[4, 12, 20, 28])
    pub const Spi1Rxi: Self = Self::Sci3Rxi;
    /// group6 (IELSR[6, 14, 22, 30])
    pub const Spi1Tei: Self = Self::Sci3Rxi;
    /// group5 (IELSR[5, 13, 21, 29])
    pub const Spi1Txi: Self = Self::Gpt8CaptureCompareA;
    /// group2 (IELSR[2, 10, 18, 26]) / group6 (IELSR[6, 14, 22, 30])
    pub const TrngRdreq: Self = Self::AesRdreq;
    /// group0 (IELSR[0, 8, 16, 24]) / group4 (IELSR[4, 12, 20, 28])
    pub const WdtUnderflow: Self = Self::Adc0CompareMismatch;
}
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    IEL0 = 0,
    IEL1 = 1,
    IEL2 = 2,
    IEL3 = 3,
    IEL4 = 4,
    IEL5 = 5,
    IEL6 = 6,
    IEL7 = 7,
    IEL8 = 8,
    IEL9 = 9,
    IEL10 = 10,
    IEL11 = 11,
    IEL12 = 12,
    IEL13 = 13,
    IEL14 = 14,
    IEL15 = 15,
    IEL16 = 16,
    IEL17 = 17,
    IEL18 = 18,
    IEL19 = 19,
    IEL20 = 20,
    IEL21 = 21,
    IEL22 = 22,
    IEL23 = 23,
    IEL24 = 24,
    IEL25 = 25,
    IEL26 = 26,
    IEL27 = 27,
    IEL28 = 28,
    IEL29 = 29,
    IEL30 = 30,
    IEL31 = 31,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[cfg(feature = "embassy")]
embassy_hal_internal::interrupt_mod!(
    IEL0, IEL1, IEL2, IEL3, IEL4, IEL5, IEL6, IEL7, IEL8, IEL9, IEL10, IEL11, IEL12, IEL13, IEL14,
    IEL15, IEL16, IEL17, IEL18, IEL19, IEL20, IEL21, IEL22, IEL23, IEL24, IEL25, IEL26, IEL27,
    IEL28, IEL29, IEL30, IEL31,
);
extern "C" {
    pub fn IEL0();
    pub fn IEL1();
    pub fn IEL2();
    pub fn IEL3();
    pub fn IEL4();
    pub fn IEL5();
    pub fn IEL6();
    pub fn IEL7();
    pub fn IEL8();
    pub fn IEL9();
    pub fn IEL10();
    pub fn IEL11();
    pub fn IEL12();
    pub fn IEL13();
    pub fn IEL14();
    pub fn IEL15();
    pub fn IEL16();
    pub fn IEL17();
    pub fn IEL18();
    pub fn IEL19();
    pub fn IEL20();
    pub fn IEL21();
    pub fn IEL22();
    pub fn IEL23();
    pub fn IEL24();
    pub fn IEL25();
    pub fn IEL26();
    pub fn IEL27();
    pub fn IEL28();
    pub fn IEL29();
    pub fn IEL30();
    pub fn IEL31();
}
#[derive(Copy, Clone)]
#[repr(C)]
pub union Vector {
    pub _handler: unsafe extern "C" fn(),
    pub _reserved: u32,
}
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 32] = [
    Vector { _handler: IEL0 },
    Vector { _handler: IEL1 },
    Vector { _handler: IEL2 },
    Vector { _handler: IEL3 },
    Vector { _handler: IEL4 },
    Vector { _handler: IEL5 },
    Vector { _handler: IEL6 },
    Vector { _handler: IEL7 },
    Vector { _handler: IEL8 },
    Vector { _handler: IEL9 },
    Vector { _handler: IEL10 },
    Vector { _handler: IEL11 },
    Vector { _handler: IEL12 },
    Vector { _handler: IEL13 },
    Vector { _handler: IEL14 },
    Vector { _handler: IEL15 },
    Vector { _handler: IEL16 },
    Vector { _handler: IEL17 },
    Vector { _handler: IEL18 },
    Vector { _handler: IEL19 },
    Vector { _handler: IEL20 },
    Vector { _handler: IEL21 },
    Vector { _handler: IEL22 },
    Vector { _handler: IEL23 },
    Vector { _handler: IEL24 },
    Vector { _handler: IEL25 },
    Vector { _handler: IEL26 },
    Vector { _handler: IEL27 },
    Vector { _handler: IEL28 },
    Vector { _handler: IEL29 },
    Vector { _handler: IEL30 },
    Vector { _handler: IEL31 },
];
