// This file is autogenerated by ra-metapac-gen: do not edit by hand.
pub mod peripherals {
    #[derive(Copy, Clone)]
    pub struct GPT(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for GPT {}
    impl GPT {
        pub const REGS: crate::_peripherals::timer_v3::Gpt =
            unsafe { crate::_peripherals::timer_v3::Gpt::from_ptr(0x40078000 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for GPT {
        type Target = crate::_peripherals::timer_v3::Gpt;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for GPT {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[0]
        }
    }
    #[derive(Copy, Clone)]
    pub struct GPT0(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for GPT0 {}
    impl GPT0 {
        pub const REGS: crate::_peripherals::timer_v3::Gpt =
            unsafe { crate::_peripherals::timer_v3::Gpt::from_ptr(0x40078000 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for GPT0 {
        type Target = crate::_peripherals::timer_v3::Gpt;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for GPT0 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[1]
        }
    }
    #[derive(Copy, Clone)]
    pub struct GPT1(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for GPT1 {}
    impl GPT1 {
        pub const REGS: crate::_peripherals::timer_v3::Gpt =
            unsafe { crate::_peripherals::timer_v3::Gpt::from_ptr(0x40078100 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for GPT1 {
        type Target = crate::_peripherals::timer_v3::Gpt;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for GPT1 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[2]
        }
    }
    #[derive(Copy, Clone)]
    pub struct GPT2(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for GPT2 {}
    impl GPT2 {
        pub const REGS: crate::_peripherals::timer_v3::Gpt =
            unsafe { crate::_peripherals::timer_v3::Gpt::from_ptr(0x40078200 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for GPT2 {
        type Target = crate::_peripherals::timer_v3::Gpt;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for GPT2 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[3]
        }
    }
    #[derive(Copy, Clone)]
    pub struct GPT3(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for GPT3 {}
    impl GPT3 {
        pub const REGS: crate::_peripherals::timer_v3::Gpt =
            unsafe { crate::_peripherals::timer_v3::Gpt::from_ptr(0x40078300 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for GPT3 {
        type Target = crate::_peripherals::timer_v3::Gpt;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for GPT3 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[4]
        }
    }
    #[derive(Copy, Clone)]
    pub struct GPT4(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for GPT4 {}
    impl GPT4 {
        pub const REGS: crate::_peripherals::timer_v3::Gpt =
            unsafe { crate::_peripherals::timer_v3::Gpt::from_ptr(0x40078400 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for GPT4 {
        type Target = crate::_peripherals::timer_v3::Gpt;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for GPT4 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[5]
        }
    }
    #[derive(Copy, Clone)]
    pub struct GPT5(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for GPT5 {}
    impl GPT5 {
        pub const REGS: crate::_peripherals::timer_v3::Gpt =
            unsafe { crate::_peripherals::timer_v3::Gpt::from_ptr(0x40078500 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for GPT5 {
        type Target = crate::_peripherals::timer_v3::Gpt;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for GPT5 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[6]
        }
    }
    #[derive(Copy, Clone)]
    pub struct GPT6(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for GPT6 {}
    impl GPT6 {
        pub const REGS: crate::_peripherals::timer_v3::Gpt =
            unsafe { crate::_peripherals::timer_v3::Gpt::from_ptr(0x40078600 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for GPT6 {
        type Target = crate::_peripherals::timer_v3::Gpt;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for GPT6 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[7]
        }
    }
    #[derive(Copy, Clone)]
    pub struct GPT7(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for GPT7 {}
    impl GPT7 {
        pub const REGS: crate::_peripherals::timer_v3::Gpt =
            unsafe { crate::_peripherals::timer_v3::Gpt::from_ptr(0x40078700 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for GPT7 {
        type Target = crate::_peripherals::timer_v3::Gpt;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for GPT7 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[8]
        }
    }
    #[derive(Copy, Clone)]
    pub struct GPT8(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for GPT8 {}
    impl GPT8 {
        pub const REGS: crate::_peripherals::timer_v3::Gpt =
            unsafe { crate::_peripherals::timer_v3::Gpt::from_ptr(0x40078800 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for GPT8 {
        type Target = crate::_peripherals::timer_v3::Gpt;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for GPT8 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[9]
        }
    }
    #[derive(Copy, Clone)]
    pub struct GPT9(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for GPT9 {}
    impl GPT9 {
        pub const REGS: crate::_peripherals::timer_v3::Gpt =
            unsafe { crate::_peripherals::timer_v3::Gpt::from_ptr(0x40078900 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for GPT9 {
        type Target = crate::_peripherals::timer_v3::Gpt;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for GPT9 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[10]
        }
    }
    #[derive(Copy, Clone)]
    pub struct GPT_OPS(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for GPT_OPS {}
    impl GPT_OPS {
        pub const REGS: crate::_peripherals::timer_v3::Gpt =
            unsafe { crate::_peripherals::timer_v3::Gpt::from_ptr(0x40078ff0 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for GPT_OPS {
        type Target = crate::_peripherals::timer_v3::Gpt;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for GPT_OPS {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[11]
        }
    }
    #[derive(Copy, Clone)]
    pub struct GPT_POEG(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for GPT_POEG {}
    impl GPT_POEG {
        pub const REGS: crate::_peripherals::timer_v3::Gpt =
            unsafe { crate::_peripherals::timer_v3::Gpt::from_ptr(0x40042000 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for GPT_POEG {
        type Target = crate::_peripherals::timer_v3::Gpt;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for GPT_POEG {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[12]
        }
    }
    #[derive(Copy, Clone)]
    pub struct GPT_POEG0(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for GPT_POEG0 {}
    impl GPT_POEG0 {
        pub const REGS: crate::_peripherals::timer_v3::Gpt =
            unsafe { crate::_peripherals::timer_v3::Gpt::from_ptr(0x40042000 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for GPT_POEG0 {
        type Target = crate::_peripherals::timer_v3::Gpt;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for GPT_POEG0 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[13]
        }
    }
    #[derive(Copy, Clone)]
    pub struct GPT_POEG1(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for GPT_POEG1 {}
    impl GPT_POEG1 {
        pub const REGS: crate::_peripherals::timer_v3::Gpt =
            unsafe { crate::_peripherals::timer_v3::Gpt::from_ptr(0x40042100 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for GPT_POEG1 {
        type Target = crate::_peripherals::timer_v3::Gpt;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for GPT_POEG1 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[14]
        }
    }
    #[derive(Copy, Clone)]
    pub struct ICU(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for ICU {}
    impl ICU {
        pub const REGS: crate::_peripherals::icu_v2::Icu =
            unsafe { crate::_peripherals::icu_v2::Icu::from_ptr(0x40006000 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for ICU {
        type Target = crate::_peripherals::icu_v2::Icu;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for ICU {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[15]
        }
    }
    #[derive(Copy, Clone)]
    pub struct MSTP(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for MSTP {}
    impl MSTP {
        pub const REGS: crate::_peripherals::mstp_v3::Mstp =
            unsafe { crate::_peripherals::mstp_v3::Mstp::from_ptr(0x40047000 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for MSTP {
        type Target = crate::_peripherals::mstp_v3::Mstp;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for MSTP {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[16]
        }
    }
    #[derive(Copy, Clone)]
    pub struct PORT0(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for PORT0 {}
    impl PORT0 {
        pub const REGS: crate::_peripherals::gpio_v1::Port =
            unsafe { crate::_peripherals::gpio_v1::Port::from_ptr(0x40040000 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for PORT0 {
        type Target = crate::_peripherals::gpio_v1::Port;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for PORT0 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[17]
        }
    }
    #[derive(Copy, Clone)]
    pub struct PORT1(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for PORT1 {}
    impl PORT1 {
        pub const REGS: crate::_peripherals::gpio_v1::Port =
            unsafe { crate::_peripherals::gpio_v1::Port::from_ptr(0x40040020 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for PORT1 {
        type Target = crate::_peripherals::gpio_v1::Port;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for PORT1 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[18]
        }
    }
    #[derive(Copy, Clone)]
    pub struct PORT2(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for PORT2 {}
    impl PORT2 {
        pub const REGS: crate::_peripherals::gpio_v1::Port =
            unsafe { crate::_peripherals::gpio_v1::Port::from_ptr(0x40040040 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for PORT2 {
        type Target = crate::_peripherals::gpio_v1::Port;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for PORT2 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[19]
        }
    }
    #[derive(Copy, Clone)]
    pub struct PORT3(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for PORT3 {}
    impl PORT3 {
        pub const REGS: crate::_peripherals::gpio_v1::Port =
            unsafe { crate::_peripherals::gpio_v1::Port::from_ptr(0x40040060 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for PORT3 {
        type Target = crate::_peripherals::gpio_v1::Port;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for PORT3 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[20]
        }
    }
    #[derive(Copy, Clone)]
    pub struct PORT4(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for PORT4 {}
    impl PORT4 {
        pub const REGS: crate::_peripherals::gpio_v1::Port =
            unsafe { crate::_peripherals::gpio_v1::Port::from_ptr(0x40040080 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for PORT4 {
        type Target = crate::_peripherals::gpio_v1::Port;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for PORT4 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[21]
        }
    }
    #[derive(Copy, Clone)]
    pub struct PORT5(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for PORT5 {}
    impl PORT5 {
        pub const REGS: crate::_peripherals::gpio_v1::Port =
            unsafe { crate::_peripherals::gpio_v1::Port::from_ptr(0x400400a0 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for PORT5 {
        type Target = crate::_peripherals::gpio_v1::Port;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for PORT5 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[22]
        }
    }
    #[derive(Copy, Clone)]
    pub struct PORT6(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for PORT6 {}
    impl PORT6 {
        pub const REGS: crate::_peripherals::gpio_v1::Port =
            unsafe { crate::_peripherals::gpio_v1::Port::from_ptr(0x400400c0 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for PORT6 {
        type Target = crate::_peripherals::gpio_v1::Port;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for PORT6 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[23]
        }
    }
    #[derive(Copy, Clone)]
    pub struct PORT7(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for PORT7 {}
    impl PORT7 {
        pub const REGS: crate::_peripherals::gpio_v1::Port =
            unsafe { crate::_peripherals::gpio_v1::Port::from_ptr(0x400400e0 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for PORT7 {
        type Target = crate::_peripherals::gpio_v1::Port;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for PORT7 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[24]
        }
    }
    #[derive(Copy, Clone)]
    pub struct PORT8(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for PORT8 {}
    impl PORT8 {
        pub const REGS: crate::_peripherals::gpio_v1::Port =
            unsafe { crate::_peripherals::gpio_v1::Port::from_ptr(0x40040100 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for PORT8 {
        type Target = crate::_peripherals::gpio_v1::Port;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for PORT8 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[25]
        }
    }
    #[derive(Copy, Clone)]
    pub struct RTC(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for RTC {}
    impl RTC {
        pub const REGS: crate::_peripherals::rtc_v1::RtcC =
            unsafe { crate::_peripherals::rtc_v1::RtcC::from_ptr(0x40044000 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for RTC {
        type Target = crate::_peripherals::rtc_v1::RtcC;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for RTC {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[26]
        }
    }
    #[derive(Copy, Clone)]
    pub struct SYSTEM(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for SYSTEM {}
    impl SYSTEM {
        pub const REGS: crate::_peripherals::system_v2::System =
            unsafe { crate::_peripherals::system_v2::System::from_ptr(0x4001e000 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for SYSTEM {
        type Target = crate::_peripherals::system_v2::System;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for SYSTEM {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[27]
        }
    }
    pub struct Peripherals {
        pub gpt: GPT,
        pub gpt0: GPT0,
        pub gpt1: GPT1,
        pub gpt2: GPT2,
        pub gpt3: GPT3,
        pub gpt4: GPT4,
        pub gpt5: GPT5,
        pub gpt6: GPT6,
        pub gpt7: GPT7,
        pub gpt8: GPT8,
        pub gpt9: GPT9,
        pub gpt_ops: GPT_OPS,
        pub gpt_poeg: GPT_POEG,
        pub gpt_poeg0: GPT_POEG0,
        pub gpt_poeg1: GPT_POEG1,
        pub icu: ICU,
        pub mstp: MSTP,
        pub port0: PORT0,
        pub port1: PORT1,
        pub port2: PORT2,
        pub port3: PORT3,
        pub port4: PORT4,
        pub port5: PORT5,
        pub port6: PORT6,
        pub port7: PORT7,
        pub port8: PORT8,
        pub rtc: RTC,
        pub system: SYSTEM,
        pub iel0: IEL0,
        pub iel1: IEL1,
        pub iel2: IEL2,
        pub iel3: IEL3,
        pub iel4: IEL4,
        pub iel5: IEL5,
        pub iel6: IEL6,
        pub iel7: IEL7,
        pub iel8: IEL8,
        pub iel9: IEL9,
        pub iel10: IEL10,
        pub iel11: IEL11,
        pub iel12: IEL12,
        pub iel13: IEL13,
        pub iel14: IEL14,
        pub iel15: IEL15,
        pub iel16: IEL16,
        pub iel17: IEL17,
        pub iel18: IEL18,
        pub iel19: IEL19,
        pub iel20: IEL20,
        pub iel21: IEL21,
        pub iel22: IEL22,
        pub iel23: IEL23,
        pub iel24: IEL24,
        pub iel25: IEL25,
        pub iel26: IEL26,
        pub iel27: IEL27,
        pub iel28: IEL28,
        pub iel29: IEL29,
        pub iel30: IEL30,
        pub iel31: IEL31,
    }
    impl Peripherals {
        pub unsafe fn steal() -> Self {
            Self {
                gpt: GPT(()),
                gpt0: GPT0(()),
                gpt1: GPT1(()),
                gpt2: GPT2(()),
                gpt3: GPT3(()),
                gpt4: GPT4(()),
                gpt5: GPT5(()),
                gpt6: GPT6(()),
                gpt7: GPT7(()),
                gpt8: GPT8(()),
                gpt9: GPT9(()),
                gpt_ops: GPT_OPS(()),
                gpt_poeg: GPT_POEG(()),
                gpt_poeg0: GPT_POEG0(()),
                gpt_poeg1: GPT_POEG1(()),
                icu: ICU(()),
                mstp: MSTP(()),
                port0: PORT0(()),
                port1: PORT1(()),
                port2: PORT2(()),
                port3: PORT3(()),
                port4: PORT4(()),
                port5: PORT5(()),
                port6: PORT6(()),
                port7: PORT7(()),
                port8: PORT8(()),
                rtc: RTC(()),
                system: SYSTEM(()),
                iel0: IEL0(()),
                iel1: IEL1(()),
                iel2: IEL2(()),
                iel3: IEL3(()),
                iel4: IEL4(()),
                iel5: IEL5(()),
                iel6: IEL6(()),
                iel7: IEL7(()),
                iel8: IEL8(()),
                iel9: IEL9(()),
                iel10: IEL10(()),
                iel11: IEL11(()),
                iel12: IEL12(()),
                iel13: IEL13(()),
                iel14: IEL14(()),
                iel15: IEL15(()),
                iel16: IEL16(()),
                iel17: IEL17(()),
                iel18: IEL18(()),
                iel19: IEL19(()),
                iel20: IEL20(()),
                iel21: IEL21(()),
                iel22: IEL22(()),
                iel23: IEL23(()),
                iel24: IEL24(()),
                iel25: IEL25(()),
                iel26: IEL26(()),
                iel27: IEL27(()),
                iel28: IEL28(()),
                iel29: IEL29(()),
                iel30: IEL30(()),
                iel31: IEL31(()),
            }
        }
    }
    #[derive(Copy, Clone)]
    pub struct IEL0(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL0 {}
    #[derive(Copy, Clone)]
    pub struct IEL1(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL1 {}
    #[derive(Copy, Clone)]
    pub struct IEL2(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL2 {}
    #[derive(Copy, Clone)]
    pub struct IEL3(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL3 {}
    #[derive(Copy, Clone)]
    pub struct IEL4(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL4 {}
    #[derive(Copy, Clone)]
    pub struct IEL5(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL5 {}
    #[derive(Copy, Clone)]
    pub struct IEL6(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL6 {}
    #[derive(Copy, Clone)]
    pub struct IEL7(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL7 {}
    #[derive(Copy, Clone)]
    pub struct IEL8(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL8 {}
    #[derive(Copy, Clone)]
    pub struct IEL9(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL9 {}
    #[derive(Copy, Clone)]
    pub struct IEL10(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL10 {}
    #[derive(Copy, Clone)]
    pub struct IEL11(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL11 {}
    #[derive(Copy, Clone)]
    pub struct IEL12(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL12 {}
    #[derive(Copy, Clone)]
    pub struct IEL13(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL13 {}
    #[derive(Copy, Clone)]
    pub struct IEL14(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL14 {}
    #[derive(Copy, Clone)]
    pub struct IEL15(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL15 {}
    #[derive(Copy, Clone)]
    pub struct IEL16(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL16 {}
    #[derive(Copy, Clone)]
    pub struct IEL17(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL17 {}
    #[derive(Copy, Clone)]
    pub struct IEL18(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL18 {}
    #[derive(Copy, Clone)]
    pub struct IEL19(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL19 {}
    #[derive(Copy, Clone)]
    pub struct IEL20(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL20 {}
    #[derive(Copy, Clone)]
    pub struct IEL21(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL21 {}
    #[derive(Copy, Clone)]
    pub struct IEL22(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL22 {}
    #[derive(Copy, Clone)]
    pub struct IEL23(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL23 {}
    #[derive(Copy, Clone)]
    pub struct IEL24(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL24 {}
    #[derive(Copy, Clone)]
    pub struct IEL25(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL25 {}
    #[derive(Copy, Clone)]
    pub struct IEL26(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL26 {}
    #[derive(Copy, Clone)]
    pub struct IEL27(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL27 {}
    #[derive(Copy, Clone)]
    pub struct IEL28(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL28 {}
    #[derive(Copy, Clone)]
    pub struct IEL29(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL29 {}
    #[derive(Copy, Clone)]
    pub struct IEL30(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL30 {}
    #[derive(Copy, Clone)]
    pub struct IEL31(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL31 {}
}
#[macro_export]
macro_rules! foreach_interrupt {
    ($m:path, $($args:tt)*) => {
        $m! { $($args)* {
            IEL0 = 0,
            IEL1 = 1,
            IEL2 = 2,
            IEL3 = 3,
            IEL4 = 4,
            IEL5 = 5,
            IEL6 = 6,
            IEL7 = 7,
            IEL8 = 8,
            IEL9 = 9,
            IEL10 = 10,
            IEL11 = 11,
            IEL12 = 12,
            IEL13 = 13,
            IEL14 = 14,
            IEL15 = 15,
            IEL16 = 16,
            IEL17 = 17,
            IEL18 = 18,
            IEL19 = 19,
            IEL20 = 20,
            IEL21 = 21,
            IEL22 = 22,
            IEL23 = 23,
            IEL24 = 24,
            IEL25 = 25,
            IEL26 = 26,
            IEL27 = 27,
            IEL28 = 28,
            IEL29 = 29,
            IEL30 = 30,
            IEL31 = 31,
        } }
    };
    ($($m:tt)*) => {
        $($m)*! {
            IEL0 = 0,
            IEL1 = 1,
            IEL2 = 2,
            IEL3 = 3,
            IEL4 = 4,
            IEL5 = 5,
            IEL6 = 6,
            IEL7 = 7,
            IEL8 = 8,
            IEL9 = 9,
            IEL10 = 10,
            IEL11 = 11,
            IEL12 = 12,
            IEL13 = 13,
            IEL14 = 14,
            IEL15 = 15,
            IEL16 = 16,
            IEL17 = 17,
            IEL18 = 18,
            IEL19 = 19,
            IEL20 = 20,
            IEL21 = 21,
            IEL22 = 22,
            IEL23 = 23,
            IEL24 = 24,
            IEL25 = 25,
            IEL26 = 26,
            IEL27 = 27,
            IEL28 = 28,
            IEL29 = 29,
            IEL30 = 30,
            IEL31 = 31,
        }
    };
}
#[macro_export]
macro_rules! foreach_event {
    ($m:path, $($args:tt)*) => {
        $m! { $($args)* {
            IcuIrq0 = 1,
            IcuIrq1 = 2,
            IcuIrq2 = 3,
            IcuIrq3 = 4,
            IcuIrq4 = 5,
            IcuIrq5 = 6,
            IcuIrq6 = 7,
            IcuIrq7 = 8,
            DtcComplete = 9,
            DtcEnd = 10,
            IcuSnoozeCancel = 11,
            FcuFrdyi = 12,
            LvdLvd1 = 13,
            LvdLvd2 = 14,
            CgcMoscStop = 15,
            LpmSnoozeRequest = 16,
            Agt0Int = 17,
            Agt0CompareA = 18,
            Agt0CompareB = 19,
            Agt1Int = 20,
            Agt1CompareA = 21,
            Agt1CompareB = 22,
            IwdtUnderflow = 23,
            WdtUnderflow = 24,
            RtcAlarm = 25,
            RtcPeriod = 26,
            RtcCarry = 27,
            Adc0ScanEnd = 28,
            Adc0ScanEndB = 29,
            Adc0WindowA = 30,
            Adc0WindowB = 31,
            Adc0CompareMatch = 32,
            Adc0CompareMismatch = 33,
            Acmplp0Int = 35,
            Acmplp1Int = 36,
            Iic0Rxi = 39,
            Iic0Txi = 40,
            Iic0Tei = 41,
            Iic0Eri = 42,
            Iic0Wui = 43,
            Iic1Rxi = 44,
            Iic1Txi = 45,
            Iic1Tei = 46,
            Iic1Eri = 47,
            CtsuWrite = 48,
            CtsuRead = 49,
            CtsuEnd = 50,
            KeyInt = 51,
            DocInt = 52,
            CacFrequencyError = 53,
            CacMeasurementEnd = 54,
            CacOverflow = 55,
            Can0Error = 56,
            Can0FifoRx = 57,
            Can0FifoTx = 58,
            Can0MailboxRx = 59,
            Can0MailboxTx = 60,
            IoportEvent1 = 61,
            IoportEvent2 = 62,
            ElcSoftwareEvent0 = 63,
            ElcSoftwareEvent1 = 64,
            Poeg0Event = 65,
            Poeg1Event = 66,
            Gpt0CaptureCompareA = 70,
            Gpt0CaptureCompareB = 71,
            Gpt0CompareC = 72,
            Gpt0CompareD = 73,
            Gpt0CounterOverflow = 74,
            Gpt0CounterUnderflow = 75,
            Gpt1CaptureCompareA = 76,
            Gpt1CaptureCompareB = 77,
            Gpt1CompareC = 78,
            Gpt1CompareD = 79,
            Gpt1CounterOverflow = 80,
            Gpt1CounterUnderflow = 81,
            Gpt2CaptureCompareA = 82,
            Gpt2CaptureCompareB = 83,
            Gpt2CompareC = 84,
            Gpt2CompareD = 85,
            Gpt2CounterOverflow = 86,
            Gpt2CounterUnderflow = 87,
            Gpt3CaptureCompareA = 88,
            Gpt3CaptureCompareB = 89,
            Gpt3CompareC = 90,
            Gpt3CompareD = 91,
            Gpt3CounterOverflow = 92,
            Gpt3CounterUnderflow = 93,
            Gpt4CaptureCompareA = 94,
            Gpt4CaptureCompareB = 95,
            Gpt4CompareC = 96,
            Gpt4CompareD = 97,
            Gpt4CounterOverflow = 98,
            Gpt4CounterUnderflow = 99,
            Gpt5CaptureCompareA = 100,
            Gpt5CaptureCompareB = 101,
            Gpt5CompareC = 102,
            Gpt5CompareD = 103,
            Gpt5CounterOverflow = 104,
            Gpt5CounterUnderflow = 105,
            Gpt6CaptureCompareA = 106,
            Gpt6CaptureCompareB = 107,
            Gpt6CompareC = 108,
            Gpt6CompareD = 109,
            Gpt6CounterOverflow = 110,
            Gpt6CounterUnderflow = 111,
            GptUvwedge = 112,
            Sci0Rxi = 113,
            Sci0Txi = 114,
            Sci0Tei = 115,
            Sci0Eri = 116,
            Sci0Am = 117,
            Sci0RxiOrEri = 118,
            Sci1Rxi = 119,
            Sci1Txi = 120,
            Sci1Tei = 121,
            Sci1Eri = 122,
            Sci1Am = 123,
            Sci9Rxi = 124,
            Sci9Txi = 125,
            Sci9Tei = 126,
            Sci9Eri = 127,
            Sci9Am = 128,
            Spi0Rxi = 129,
            Spi0Txi = 130,
            Spi0Idle = 131,
            Spi0Eri = 132,
            Spi0Tei = 133,
            Spi1Rxi = 134,
            Spi1Txi = 135,
            Spi1Idle = 136,
            Spi1Eri = 137,
            Spi1Tei = 138,
            AesWrreq = 139,
            AesRdreq = 140,
            TrngRdreq = 141,
            Sci2Rxi = 142,
            Sci2Txi = 143,
            Sci2Tei = 144,
            Sci2Eri = 145,
            Sci2Am = 146,
            Sci3Rxi = 147,
            Sci3Txi = 148,
            Sci3Tei = 149,
            Sci3Eri = 150,
            Sci3Am = 151,
            Gpt7CaptureCompareA = 152,
            Gpt7CaptureCompareB = 153,
            Gpt7CompareC = 154,
            Gpt7CompareD = 155,
            Gpt7CounterOverflow = 156,
            Gpt7CounterUnderflow = 157,
            Gpt8CaptureCompareA = 158,
            Gpt8CaptureCompareB = 159,
            Gpt8CompareC = 160,
            Gpt8CompareD = 161,
            Gpt8CounterOverflow = 162,
            Gpt8CounterUnderflow = 163,
            Gpt9CaptureCompareA = 164,
            Gpt9CaptureCompareB = 165,
            Gpt9CompareC = 166,
            Gpt9CompareD = 167,
            Gpt9CounterOverflow = 168,
            Gpt9CounterUnderflow = 169,
        } }
    };
    ($($m:tt)*) => {
        $($m)*! {
            IcuIrq0 = 1,
            IcuIrq1 = 2,
            IcuIrq2 = 3,
            IcuIrq3 = 4,
            IcuIrq4 = 5,
            IcuIrq5 = 6,
            IcuIrq6 = 7,
            IcuIrq7 = 8,
            DtcComplete = 9,
            DtcEnd = 10,
            IcuSnoozeCancel = 11,
            FcuFrdyi = 12,
            LvdLvd1 = 13,
            LvdLvd2 = 14,
            CgcMoscStop = 15,
            LpmSnoozeRequest = 16,
            Agt0Int = 17,
            Agt0CompareA = 18,
            Agt0CompareB = 19,
            Agt1Int = 20,
            Agt1CompareA = 21,
            Agt1CompareB = 22,
            IwdtUnderflow = 23,
            WdtUnderflow = 24,
            RtcAlarm = 25,
            RtcPeriod = 26,
            RtcCarry = 27,
            Adc0ScanEnd = 28,
            Adc0ScanEndB = 29,
            Adc0WindowA = 30,
            Adc0WindowB = 31,
            Adc0CompareMatch = 32,
            Adc0CompareMismatch = 33,
            Acmplp0Int = 35,
            Acmplp1Int = 36,
            Iic0Rxi = 39,
            Iic0Txi = 40,
            Iic0Tei = 41,
            Iic0Eri = 42,
            Iic0Wui = 43,
            Iic1Rxi = 44,
            Iic1Txi = 45,
            Iic1Tei = 46,
            Iic1Eri = 47,
            CtsuWrite = 48,
            CtsuRead = 49,
            CtsuEnd = 50,
            KeyInt = 51,
            DocInt = 52,
            CacFrequencyError = 53,
            CacMeasurementEnd = 54,
            CacOverflow = 55,
            Can0Error = 56,
            Can0FifoRx = 57,
            Can0FifoTx = 58,
            Can0MailboxRx = 59,
            Can0MailboxTx = 60,
            IoportEvent1 = 61,
            IoportEvent2 = 62,
            ElcSoftwareEvent0 = 63,
            ElcSoftwareEvent1 = 64,
            Poeg0Event = 65,
            Poeg1Event = 66,
            Gpt0CaptureCompareA = 70,
            Gpt0CaptureCompareB = 71,
            Gpt0CompareC = 72,
            Gpt0CompareD = 73,
            Gpt0CounterOverflow = 74,
            Gpt0CounterUnderflow = 75,
            Gpt1CaptureCompareA = 76,
            Gpt1CaptureCompareB = 77,
            Gpt1CompareC = 78,
            Gpt1CompareD = 79,
            Gpt1CounterOverflow = 80,
            Gpt1CounterUnderflow = 81,
            Gpt2CaptureCompareA = 82,
            Gpt2CaptureCompareB = 83,
            Gpt2CompareC = 84,
            Gpt2CompareD = 85,
            Gpt2CounterOverflow = 86,
            Gpt2CounterUnderflow = 87,
            Gpt3CaptureCompareA = 88,
            Gpt3CaptureCompareB = 89,
            Gpt3CompareC = 90,
            Gpt3CompareD = 91,
            Gpt3CounterOverflow = 92,
            Gpt3CounterUnderflow = 93,
            Gpt4CaptureCompareA = 94,
            Gpt4CaptureCompareB = 95,
            Gpt4CompareC = 96,
            Gpt4CompareD = 97,
            Gpt4CounterOverflow = 98,
            Gpt4CounterUnderflow = 99,
            Gpt5CaptureCompareA = 100,
            Gpt5CaptureCompareB = 101,
            Gpt5CompareC = 102,
            Gpt5CompareD = 103,
            Gpt5CounterOverflow = 104,
            Gpt5CounterUnderflow = 105,
            Gpt6CaptureCompareA = 106,
            Gpt6CaptureCompareB = 107,
            Gpt6CompareC = 108,
            Gpt6CompareD = 109,
            Gpt6CounterOverflow = 110,
            Gpt6CounterUnderflow = 111,
            GptUvwedge = 112,
            Sci0Rxi = 113,
            Sci0Txi = 114,
            Sci0Tei = 115,
            Sci0Eri = 116,
            Sci0Am = 117,
            Sci0RxiOrEri = 118,
            Sci1Rxi = 119,
            Sci1Txi = 120,
            Sci1Tei = 121,
            Sci1Eri = 122,
            Sci1Am = 123,
            Sci9Rxi = 124,
            Sci9Txi = 125,
            Sci9Tei = 126,
            Sci9Eri = 127,
            Sci9Am = 128,
            Spi0Rxi = 129,
            Spi0Txi = 130,
            Spi0Idle = 131,
            Spi0Eri = 132,
            Spi0Tei = 133,
            Spi1Rxi = 134,
            Spi1Txi = 135,
            Spi1Idle = 136,
            Spi1Eri = 137,
            Spi1Tei = 138,
            AesWrreq = 139,
            AesRdreq = 140,
            TrngRdreq = 141,
            Sci2Rxi = 142,
            Sci2Txi = 143,
            Sci2Tei = 144,
            Sci2Eri = 145,
            Sci2Am = 146,
            Sci3Rxi = 147,
            Sci3Txi = 148,
            Sci3Tei = 149,
            Sci3Eri = 150,
            Sci3Am = 151,
            Gpt7CaptureCompareA = 152,
            Gpt7CaptureCompareB = 153,
            Gpt7CompareC = 154,
            Gpt7CompareD = 155,
            Gpt7CounterOverflow = 156,
            Gpt7CounterUnderflow = 157,
            Gpt8CaptureCompareA = 158,
            Gpt8CaptureCompareB = 159,
            Gpt8CompareC = 160,
            Gpt8CompareD = 161,
            Gpt8CounterOverflow = 162,
            Gpt8CounterUnderflow = 163,
            Gpt9CaptureCompareA = 164,
            Gpt9CaptureCompareB = 165,
            Gpt9CompareC = 166,
            Gpt9CompareD = 167,
            Gpt9CounterOverflow = 168,
            Gpt9CounterUnderflow = 169,
        }
    };
}
#[macro_export]
macro_rules! foreach_peripheral {
    ($m:path) => {
        $m! {
            GPT = 0,
            GPT0 = 1,
            GPT1 = 2,
            GPT2 = 3,
            GPT3 = 4,
            GPT4 = 5,
            GPT5 = 6,
            GPT6 = 7,
            GPT7 = 8,
            GPT8 = 9,
            GPT9 = 10,
            GPT_OPS = 11,
            GPT_POEG = 12,
            GPT_POEG0 = 13,
            GPT_POEG1 = 14,
            ICU = 15,
            MSTP = 16,
            PORT0 = 17,
            PORT1 = 18,
            PORT2 = 19,
            PORT3 = 20,
            PORT4 = 21,
            PORT5 = 22,
            PORT6 = 23,
            PORT7 = 24,
            PORT8 = 25,
            RTC = 26,
            SYSTEM = 27,
        }
    };
}
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Event {
    /// External pin interrupt 0
    IcuIrq0 = 1,
    /// External pin interrupt 1
    IcuIrq1 = 2,
    /// External pin interrupt 2
    IcuIrq2 = 3,
    /// External pin interrupt 3
    IcuIrq3 = 4,
    /// External pin interrupt 4
    IcuIrq4 = 5,
    /// External pin interrupt 5
    IcuIrq5 = 6,
    /// External pin interrupt 6
    IcuIrq6 = 7,
    /// External pin interrupt 7
    IcuIrq7 = 8,
    /// DTC transfer complete
    DtcComplete = 9,
    /// DTC transfer end
    DtcEnd = 10,
    /// Canceling from Snooze mode
    IcuSnoozeCancel = 11,
    /// Flash ready interrupt
    FcuFrdyi = 12,
    /// Voltage monitor 1 interrupt
    LvdLvd1 = 13,
    /// Voltage monitor 2 interrupt
    LvdLvd2 = 14,
    /// Main Clock oscillation stop
    CgcMoscStop = 15,
    /// Snooze entry
    LpmSnoozeRequest = 16,
    /// AGT interrupt
    Agt0Int = 17,
    /// Compare match A
    Agt0CompareA = 18,
    /// Compare match B
    Agt0CompareB = 19,
    /// AGT interrupt
    Agt1Int = 20,
    /// Compare match A
    Agt1CompareA = 21,
    /// Compare match B
    Agt1CompareB = 22,
    /// IWDT underflow
    IwdtUnderflow = 23,
    /// WDT underflow
    WdtUnderflow = 24,
    /// Alarm interrupt
    RtcAlarm = 25,
    /// Periodic interrupt
    RtcPeriod = 26,
    /// Carry interrupt
    RtcCarry = 27,
    /// End of A/D scanning operation
    Adc0ScanEnd = 28,
    /// A/D scan end interrupt for group B
    Adc0ScanEndB = 29,
    /// Window A Compare match interrupt
    Adc0WindowA = 30,
    /// Window B Compare match interrupt
    Adc0WindowB = 31,
    /// Compare match
    Adc0CompareMatch = 32,
    /// Compare mismatch
    Adc0CompareMismatch = 33,
    /// Low Power Comparator channel 0 interrupt
    Acmplp0Int = 35,
    /// Low Power Comparator channel 1 interrupt
    Acmplp1Int = 36,
    /// Receive data full
    Iic0Rxi = 39,
    /// Transmit data empty
    Iic0Txi = 40,
    /// Transmit end
    Iic0Tei = 41,
    /// Transfer error
    Iic0Eri = 42,
    /// Wakeup interrupt
    Iic0Wui = 43,
    /// Receive data full
    Iic1Rxi = 44,
    /// Transmit data empty
    Iic1Txi = 45,
    /// Transmit end
    Iic1Tei = 46,
    /// Transfer error
    Iic1Eri = 47,
    /// Write request interrupt
    CtsuWrite = 48,
    /// Measurement data transfer request interrupt
    CtsuRead = 49,
    /// Measurement end interrupt
    CtsuEnd = 50,
    /// Key interrupt
    KeyInt = 51,
    /// Data operation circuit interrupt
    DocInt = 52,
    /// Frequency error interrupt
    CacFrequencyError = 53,
    /// Measurement end interrupt
    CacMeasurementEnd = 54,
    /// Overflow interrupt
    CacOverflow = 55,
    /// Error interrupt
    Can0Error = 56,
    /// Receive FIFO interrupt
    Can0FifoRx = 57,
    /// Transmit FIFO interrupt
    Can0FifoTx = 58,
    /// Reception complete interrupt
    Can0MailboxRx = 59,
    /// Transmission complete interrupt
    Can0MailboxTx = 60,
    /// Port 1 event
    IoportEvent1 = 61,
    /// Port 2 event
    IoportEvent2 = 62,
    /// Software event 0
    ElcSoftwareEvent0 = 63,
    /// Software event 1
    ElcSoftwareEvent1 = 64,
    /// Port Output disable 0 interrupt
    Poeg0Event = 65,
    /// Port Output disable 1 interrupt
    Poeg1Event = 66,
    /// Capture/Compare match A
    Gpt0CaptureCompareA = 70,
    /// Capture/Compare match B
    Gpt0CaptureCompareB = 71,
    /// Compare match C
    Gpt0CompareC = 72,
    /// Compare match D
    Gpt0CompareD = 73,
    /// Overflow
    Gpt0CounterOverflow = 74,
    /// Underflow
    Gpt0CounterUnderflow = 75,
    /// Capture/Compare match A
    Gpt1CaptureCompareA = 76,
    /// Capture/Compare match B
    Gpt1CaptureCompareB = 77,
    /// Compare match C
    Gpt1CompareC = 78,
    /// Compare match D
    Gpt1CompareD = 79,
    /// Overflow
    Gpt1CounterOverflow = 80,
    /// Underflow
    Gpt1CounterUnderflow = 81,
    /// Capture/Compare match A
    Gpt2CaptureCompareA = 82,
    /// Capture/Compare match B
    Gpt2CaptureCompareB = 83,
    /// Compare match C
    Gpt2CompareC = 84,
    /// Compare match D
    Gpt2CompareD = 85,
    /// Overflow
    Gpt2CounterOverflow = 86,
    /// Underflow
    Gpt2CounterUnderflow = 87,
    /// Capture/Compare match A
    Gpt3CaptureCompareA = 88,
    /// Capture/Compare match B
    Gpt3CaptureCompareB = 89,
    /// Compare match C
    Gpt3CompareC = 90,
    /// Compare match D
    Gpt3CompareD = 91,
    /// Overflow
    Gpt3CounterOverflow = 92,
    /// Underflow
    Gpt3CounterUnderflow = 93,
    /// Capture/Compare match A
    Gpt4CaptureCompareA = 94,
    /// Capture/Compare match B
    Gpt4CaptureCompareB = 95,
    /// Compare match C
    Gpt4CompareC = 96,
    /// Compare match D
    Gpt4CompareD = 97,
    /// Overflow
    Gpt4CounterOverflow = 98,
    /// Underflow
    Gpt4CounterUnderflow = 99,
    /// Capture/Compare match A
    Gpt5CaptureCompareA = 100,
    /// Capture/Compare match B
    Gpt5CaptureCompareB = 101,
    /// Compare match C
    Gpt5CompareC = 102,
    /// Compare match D
    Gpt5CompareD = 103,
    /// Overflow
    Gpt5CounterOverflow = 104,
    /// Underflow
    Gpt5CounterUnderflow = 105,
    /// Capture/Compare match A
    Gpt6CaptureCompareA = 106,
    /// Capture/Compare match B
    Gpt6CaptureCompareB = 107,
    /// Compare match C
    Gpt6CompareC = 108,
    /// Compare match D
    Gpt6CompareD = 109,
    /// Overflow
    Gpt6CounterOverflow = 110,
    /// Underflow
    Gpt6CounterUnderflow = 111,
    /// UVW edge event
    GptUvwedge = 112,
    /// Receive data full
    Sci0Rxi = 113,
    /// Transmit data empty
    Sci0Txi = 114,
    /// Transmit end
    Sci0Tei = 115,
    /// Receive error
    Sci0Eri = 116,
    /// Address match event
    Sci0Am = 117,
    /// Receive data full/Receive error
    Sci0RxiOrEri = 118,
    /// Receive data full
    Sci1Rxi = 119,
    /// Transmit data empty
    Sci1Txi = 120,
    /// Transmit end
    Sci1Tei = 121,
    /// Receive error
    Sci1Eri = 122,
    /// Address match event
    Sci1Am = 123,
    /// Receive data full
    Sci9Rxi = 124,
    /// Transmit data empty
    Sci9Txi = 125,
    /// Transmit end
    Sci9Tei = 126,
    /// Receive error
    Sci9Eri = 127,
    /// Address match event
    Sci9Am = 128,
    /// Receive buffer full
    Spi0Rxi = 129,
    /// Transmit buffer empty
    Spi0Txi = 130,
    /// Idle
    Spi0Idle = 131,
    /// Error
    Spi0Eri = 132,
    /// Transmission complete event
    Spi0Tei = 133,
    /// Receive buffer full
    Spi1Rxi = 134,
    /// Transmit buffer empty
    Spi1Txi = 135,
    /// Idle
    Spi1Idle = 136,
    /// Error
    Spi1Eri = 137,
    /// Transmission complete event
    Spi1Tei = 138,
    /// AES Write Request
    AesWrreq = 139,
    /// AES Read Request
    AesRdreq = 140,
    /// TRNG Read Request
    TrngRdreq = 141,
    /// Receive data full
    Sci2Rxi = 142,
    /// Transmit data empty
    Sci2Txi = 143,
    /// Transmit end
    Sci2Tei = 144,
    /// Receive error
    Sci2Eri = 145,
    /// Address match event
    Sci2Am = 146,
    /// Receive data full
    Sci3Rxi = 147,
    /// Transmit data empty
    Sci3Txi = 148,
    /// Transmit end
    Sci3Tei = 149,
    /// Receive error
    Sci3Eri = 150,
    /// Address match event
    Sci3Am = 151,
    /// Capture/Compare match A
    Gpt7CaptureCompareA = 152,
    /// Capture/Compare match B
    Gpt7CaptureCompareB = 153,
    /// Compare match C
    Gpt7CompareC = 154,
    /// Compare match D
    Gpt7CompareD = 155,
    /// Overflow
    Gpt7CounterOverflow = 156,
    /// Underflow
    Gpt7CounterUnderflow = 157,
    /// Capture/Compare match A
    Gpt8CaptureCompareA = 158,
    /// Capture/Compare match B
    Gpt8CaptureCompareB = 159,
    /// Compare match C
    Gpt8CompareC = 160,
    /// Compare match D
    Gpt8CompareD = 161,
    /// Overflow
    Gpt8CounterOverflow = 162,
    /// Underflow
    Gpt8CounterUnderflow = 163,
    /// Capture/Compare match A
    Gpt9CaptureCompareA = 164,
    /// Capture/Compare match B
    Gpt9CaptureCompareB = 165,
    /// Compare match C
    Gpt9CompareC = 166,
    /// Compare match D
    Gpt9CompareD = 167,
    /// Overflow
    Gpt9CounterOverflow = 168,
    /// Underflow
    Gpt9CounterUnderflow = 169,
}
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    IEL0 = 0,
    IEL1 = 1,
    IEL2 = 2,
    IEL3 = 3,
    IEL4 = 4,
    IEL5 = 5,
    IEL6 = 6,
    IEL7 = 7,
    IEL8 = 8,
    IEL9 = 9,
    IEL10 = 10,
    IEL11 = 11,
    IEL12 = 12,
    IEL13 = 13,
    IEL14 = 14,
    IEL15 = 15,
    IEL16 = 16,
    IEL17 = 17,
    IEL18 = 18,
    IEL19 = 19,
    IEL20 = 20,
    IEL21 = 21,
    IEL22 = 22,
    IEL23 = 23,
    IEL24 = 24,
    IEL25 = 25,
    IEL26 = 26,
    IEL27 = 27,
    IEL28 = 28,
    IEL29 = 29,
    IEL30 = 30,
    IEL31 = 31,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[cfg(feature = "embassy")]
embassy_hal_internal::interrupt_mod!(
    IEL0, IEL1, IEL2, IEL3, IEL4, IEL5, IEL6, IEL7, IEL8, IEL9, IEL10, IEL11, IEL12, IEL13, IEL14,
    IEL15, IEL16, IEL17, IEL18, IEL19, IEL20, IEL21, IEL22, IEL23, IEL24, IEL25, IEL26, IEL27,
    IEL28, IEL29, IEL30, IEL31,
);
extern "C" {
    pub fn IEL0();
    pub fn IEL1();
    pub fn IEL2();
    pub fn IEL3();
    pub fn IEL4();
    pub fn IEL5();
    pub fn IEL6();
    pub fn IEL7();
    pub fn IEL8();
    pub fn IEL9();
    pub fn IEL10();
    pub fn IEL11();
    pub fn IEL12();
    pub fn IEL13();
    pub fn IEL14();
    pub fn IEL15();
    pub fn IEL16();
    pub fn IEL17();
    pub fn IEL18();
    pub fn IEL19();
    pub fn IEL20();
    pub fn IEL21();
    pub fn IEL22();
    pub fn IEL23();
    pub fn IEL24();
    pub fn IEL25();
    pub fn IEL26();
    pub fn IEL27();
    pub fn IEL28();
    pub fn IEL29();
    pub fn IEL30();
    pub fn IEL31();
}
#[derive(Copy, Clone)]
#[repr(C)]
pub union Vector {
    pub _handler: unsafe extern "C" fn(),
    pub _reserved: u32,
}
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 32] = [
    Vector { _handler: IEL0 },
    Vector { _handler: IEL1 },
    Vector { _handler: IEL2 },
    Vector { _handler: IEL3 },
    Vector { _handler: IEL4 },
    Vector { _handler: IEL5 },
    Vector { _handler: IEL6 },
    Vector { _handler: IEL7 },
    Vector { _handler: IEL8 },
    Vector { _handler: IEL9 },
    Vector { _handler: IEL10 },
    Vector { _handler: IEL11 },
    Vector { _handler: IEL12 },
    Vector { _handler: IEL13 },
    Vector { _handler: IEL14 },
    Vector { _handler: IEL15 },
    Vector { _handler: IEL16 },
    Vector { _handler: IEL17 },
    Vector { _handler: IEL18 },
    Vector { _handler: IEL19 },
    Vector { _handler: IEL20 },
    Vector { _handler: IEL21 },
    Vector { _handler: IEL22 },
    Vector { _handler: IEL23 },
    Vector { _handler: IEL24 },
    Vector { _handler: IEL25 },
    Vector { _handler: IEL26 },
    Vector { _handler: IEL27 },
    Vector { _handler: IEL28 },
    Vector { _handler: IEL29 },
    Vector { _handler: IEL30 },
    Vector { _handler: IEL31 },
];
