// This file is autogenerated by ra-metapac-gen: do not edit by hand.
pub const NAME: &str = "R7FA6M1AD2CLJ";
pub const FAMILY: &str = "R7FA6M1";
pub const CORE: &str = "Cortex-M4";
pub const MEMORY: &[MemoryRegion] = &[
    MemoryRegion {
        name: "RAM",
        kind: "RAM",
        address: 536739840,
        size: 262144,
    },
    MemoryRegion {
        name: "FLASH",
        kind: "ROM",
        address: 0,
        size: 524288,
    },
    MemoryRegion {
        name: "DATA_FLASH",
        kind: "ROM",
        address: 1074790400,
        size: 8192,
    },
    MemoryRegion {
        name: "QSPI_FLASH",
        kind: "ROM",
        address: 1610612736,
        size: 67108864,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OFS0",
        kind: "ROM",
        address: 1024,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OFS1",
        kind: "ROM",
        address: 1028,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_SECMPU",
        kind: "ROM",
        address: 1032,
        size: 52,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OSIS",
        kind: "ROM",
        address: 16818512,
        size: 16,
    },
];
pub const PERIPHERALS: &[Peripheral] = &[
    Peripheral {
        name: "GPT",
        address: 1074233344,
        kind: "timer",
        version: "v3",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT0",
        address: 1074233344,
        kind: "timer",
        version: "v4",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT1",
        address: 1074233600,
        kind: "timer",
        version: "v4",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT2",
        address: 1074233856,
        kind: "timer",
        version: "v4",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT3",
        address: 1074234112,
        kind: "timer",
        version: "v4",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT4",
        address: 1074234368,
        kind: "timer",
        version: "v4",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT5",
        address: 1074234624,
        kind: "timer",
        version: "v4",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT6",
        address: 1074234880,
        kind: "timer",
        version: "v4",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT7",
        address: 1074235136,
        kind: "timer",
        version: "v4",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT8",
        address: 1074235392,
        kind: "timer",
        version: "v3",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT9",
        address: 1074235648,
        kind: "timer",
        version: "v3",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT10",
        address: 1074235904,
        kind: "timer",
        version: "v3",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT11",
        address: 1074236160,
        kind: "timer",
        version: "v3",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT12",
        address: 1074236416,
        kind: "timer",
        version: "v3",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT_ODC",
        address: 1074245632,
        kind: "timer",
        version: "v3",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT_ODC0",
        address: 1074245632,
        kind: "timer",
        version: "v3",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT_OPS",
        address: 1074237424,
        kind: "timer",
        version: "v3",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT_POEG",
        address: 1074012160,
        kind: "timer",
        version: "v3",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT_POEG0",
        address: 1074012160,
        kind: "timer",
        version: "v3",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT_POEG1",
        address: 1074012416,
        kind: "timer",
        version: "v3",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT_POEG2",
        address: 1074012672,
        kind: "timer",
        version: "v3",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT_POEG3",
        address: 1074012928,
        kind: "timer",
        version: "v3",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "ICU",
        address: 1073766400,
        kind: "icu",
        version: "v3",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "MSTP",
        address: 1074032640,
        kind: "mstp",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT0",
        address: 1074003968,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT1",
        address: 1074004000,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT2",
        address: 1074004032,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT3",
        address: 1074004064,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT4",
        address: 1074004096,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT5",
        address: 1074004128,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT6",
        address: 1074004160,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT7",
        address: 1074004192,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "RTC",
        address: 1074020352,
        kind: "rtc",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "SYSTEM",
        address: 1073864704,
        kind: "system",
        version: "v4",
        mstp: None,
        bit_width: None,
    },
];
pub const PACKAGES: &[Package] = &[Package {
    name: "100LGA",
    pins: &[
        Pin {
            position: "A1",
            signals: &["p108"],
        },
        Pin {
            position: "A10",
            signals: &["p407"],
        },
        Pin {
            position: "A2",
            signals: &["p300"],
        },
        Pin {
            position: "A3",
            signals: &["vss"],
        },
        Pin {
            position: "A4",
            signals: &["vcc"],
        },
        Pin {
            position: "A5",
            signals: &["p200"],
        },
        Pin {
            position: "A6",
            signals: &["p209"],
        },
        Pin {
            position: "A7",
            signals: &["p205"],
        },
        Pin {
            position: "A8",
            signals: &["vccusb"],
        },
        Pin {
            position: "A9",
            signals: &["usbdm"],
        },
        Pin {
            position: "B1",
            signals: &["p109"],
        },
        Pin {
            position: "B10",
            signals: &["p409"],
        },
        Pin {
            position: "B2",
            signals: &["p302"],
        },
        Pin {
            position: "B3",
            signals: &["p303"],
        },
        Pin {
            position: "B4",
            signals: &["p304"],
        },
        Pin {
            position: "B5",
            signals: &["p201"],
        },
        Pin {
            position: "B6",
            signals: &["p208"],
        },
        Pin {
            position: "B7",
            signals: &["p214"],
        },
        Pin {
            position: "B8",
            signals: &["vssusb"],
        },
        Pin {
            position: "B9",
            signals: &["usbdp"],
        },
        Pin {
            position: "C1",
            signals: &["p112"],
        },
        Pin {
            position: "C10",
            signals: &["p412"],
        },
        Pin {
            position: "C2",
            signals: &["p301"],
        },
        Pin {
            position: "C3",
            signals: &["p110"],
        },
        Pin {
            position: "C4",
            signals: &["p305"],
        },
        Pin {
            position: "C5",
            signals: &["p307"],
        },
        Pin {
            position: "C6",
            signals: &["p210"],
        },
        Pin {
            position: "C7",
            signals: &["p206"],
        },
        Pin {
            position: "C8",
            signals: &["p207"],
        },
        Pin {
            position: "D8",
            signals: &["p413"],
        },
        Pin {
            position: "D1",
            signals: &["p608"],
        },
        Pin {
            position: "D10",
            signals: &["vcc"],
        },
        Pin {
            position: "D2",
            signals: &["p114"],
        },
        Pin {
            position: "D3",
            signals: &["p111"],
        },
        Pin {
            position: "D4",
            signals: &["p306"],
        },
        Pin {
            position: "D5",
            signals: &["res"],
        },
        Pin {
            position: "D6",
            signals: &["p211"],
        },
        Pin {
            position: "D7",
            signals: &["p408"],
        },
        Pin {
            position: "C9",
            signals: &["p411"],
        },
        Pin {
            position: "D9",
            signals: &["vss"],
        },
        Pin {
            position: "E1",
            signals: &["vcc"],
        },
        Pin {
            position: "E10",
            signals: &["p212"],
        },
        Pin {
            position: "E2",
            signals: &["p610"],
        },
        Pin {
            position: "E3",
            signals: &["p609"],
        },
        Pin {
            position: "E4",
            signals: &["p115"],
        },
        Pin {
            position: "E5",
            signals: &["p113"],
        },
        Pin {
            position: "E6",
            signals: &["p410"],
        },
        Pin {
            position: "E7",
            signals: &["p414"],
        },
        Pin {
            position: "E8",
            signals: &["p415"],
        },
        Pin {
            position: "E9",
            signals: &["p213"],
        },
        Pin {
            position: "F1",
            signals: &["vcl"],
        },
        Pin {
            position: "F10",
            signals: &["xcout"],
        },
        Pin {
            position: "F2",
            signals: &["vss"],
        },
        Pin {
            position: "F3",
            signals: &["p602"],
        },
        Pin {
            position: "F4",
            signals: &["p601"],
        },
        Pin {
            position: "F5",
            signals: &["p600"],
        },
        Pin {
            position: "F6",
            signals: &["p402"],
        },
        Pin {
            position: "F7",
            signals: &["p406"],
        },
        Pin {
            position: "F8",
            signals: &["p708"],
        },
        Pin {
            position: "F9",
            signals: &["xcin"],
        },
        Pin {
            position: "G1",
            signals: &["p105"],
        },
        Pin {
            position: "G10",
            signals: &["vcl0"],
        },
        Pin {
            position: "G2",
            signals: &["p106"],
        },
        Pin {
            position: "G3",
            signals: &["p107"],
        },
        Pin {
            position: "G4",
            signals: &["p503"],
        },
        Pin {
            position: "G5",
            signals: &["p504"],
        },
        Pin {
            position: "G6",
            signals: &["p508"],
        },
        Pin {
            position: "G7",
            signals: &["p006"],
        },
        Pin {
            position: "G8",
            signals: &["p404"],
        },
        Pin {
            position: "G9",
            signals: &["vbatt"],
        },
        Pin {
            position: "H1",
            signals: &["p104"],
        },
        Pin {
            position: "H10",
            signals: &["p403"],
        },
        Pin {
            position: "H2",
            signals: &["p101"],
        },
        Pin {
            position: "H3",
            signals: &["p103"],
        },
        Pin {
            position: "H4",
            signals: &["p100"],
        },
        Pin {
            position: "H5",
            signals: &["avcc0"],
        },
        Pin {
            position: "H6",
            signals: &["avss0"],
        },
        Pin {
            position: "H7",
            signals: &["p007"],
        },
        Pin {
            position: "H8",
            signals: &["p003"],
        },
        Pin {
            position: "H9",
            signals: &["p405"],
        },
        Pin {
            position: "J1",
            signals: &["p102"],
        },
        Pin {
            position: "J10",
            signals: &["p400"],
        },
        Pin {
            position: "J2",
            signals: &["p501"],
        },
        Pin {
            position: "J3",
            signals: &["vss"],
        },
        Pin {
            position: "J4",
            signals: &["p015"],
        },
        Pin {
            position: "J5",
            signals: &["vrefl"],
        },
        Pin {
            position: "J6",
            signals: &["vrefl0"],
        },
        Pin {
            position: "J7",
            signals: &["p008"],
        },
        Pin {
            position: "J8",
            signals: &["p004"],
        },
        Pin {
            position: "J9",
            signals: &["p401"],
        },
        Pin {
            position: "K1",
            signals: &["p500"],
        },
        Pin {
            position: "K10",
            signals: &["p000"],
        },
        Pin {
            position: "K2",
            signals: &["p502"],
        },
        Pin {
            position: "K3",
            signals: &["vcc"],
        },
        Pin {
            position: "K4",
            signals: &["p014"],
        },
        Pin {
            position: "K5",
            signals: &["vrefh"],
        },
        Pin {
            position: "K6",
            signals: &["vrefh0"],
        },
        Pin {
            position: "K7",
            signals: &["p005"],
        },
        Pin {
            position: "K8",
            signals: &["p002"],
        },
        Pin {
            position: "K9",
            signals: &["p001"],
        },
    ],
}];
