// This file is autogenerated by ra-metapac-gen: do not edit by hand.
pub mod peripherals {
    #[derive(Copy, Clone)]
    pub struct ICU(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for ICU {}
    impl ICU {
        pub const REGS: crate::_peripherals::icu_v1::Icu =
            unsafe { crate::_peripherals::icu_v1::Icu::from_ptr(0x40006000 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for ICU {
        type Target = crate::_peripherals::icu_v1::Icu;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for ICU {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[0]
        }
    }
    #[derive(Copy, Clone)]
    pub struct MSTP(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for MSTP {}
    impl MSTP {
        pub const REGS: crate::_peripherals::mstp_v1::Mstp =
            unsafe { crate::_peripherals::mstp_v1::Mstp::from_ptr(0x40047000 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for MSTP {
        type Target = crate::_peripherals::mstp_v1::Mstp;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for MSTP {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[1]
        }
    }
    #[derive(Copy, Clone)]
    pub struct PORT0(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for PORT0 {}
    impl PORT0 {
        pub const REGS: crate::_peripherals::gpio_v3::Port =
            unsafe { crate::_peripherals::gpio_v3::Port::from_ptr(0x400a0000 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for PORT0 {
        type Target = crate::_peripherals::gpio_v3::Port;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for PORT0 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[2]
        }
    }
    #[derive(Copy, Clone)]
    pub struct PORT1(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for PORT1 {}
    impl PORT1 {
        pub const REGS: crate::_peripherals::gpio_v3::Port =
            unsafe { crate::_peripherals::gpio_v3::Port::from_ptr(0x400a0020 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for PORT1 {
        type Target = crate::_peripherals::gpio_v3::Port;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for PORT1 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[3]
        }
    }
    #[derive(Copy, Clone)]
    pub struct PORT2(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for PORT2 {}
    impl PORT2 {
        pub const REGS: crate::_peripherals::gpio_v3::Port =
            unsafe { crate::_peripherals::gpio_v3::Port::from_ptr(0x400a0040 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for PORT2 {
        type Target = crate::_peripherals::gpio_v3::Port;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for PORT2 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[4]
        }
    }
    #[derive(Copy, Clone)]
    pub struct PORT3(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for PORT3 {}
    impl PORT3 {
        pub const REGS: crate::_peripherals::gpio_v3::Port =
            unsafe { crate::_peripherals::gpio_v3::Port::from_ptr(0x400a0060 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for PORT3 {
        type Target = crate::_peripherals::gpio_v3::Port;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for PORT3 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[5]
        }
    }
    #[derive(Copy, Clone)]
    pub struct PORT4(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for PORT4 {}
    impl PORT4 {
        pub const REGS: crate::_peripherals::gpio_v3::Port =
            unsafe { crate::_peripherals::gpio_v3::Port::from_ptr(0x400a0080 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for PORT4 {
        type Target = crate::_peripherals::gpio_v3::Port;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for PORT4 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[6]
        }
    }
    #[derive(Copy, Clone)]
    pub struct PORT5(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for PORT5 {}
    impl PORT5 {
        pub const REGS: crate::_peripherals::gpio_v3::Port =
            unsafe { crate::_peripherals::gpio_v3::Port::from_ptr(0x400a00a0 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for PORT5 {
        type Target = crate::_peripherals::gpio_v3::Port;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for PORT5 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[7]
        }
    }
    #[derive(Copy, Clone)]
    pub struct PORT9(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for PORT9 {}
    impl PORT9 {
        pub const REGS: crate::_peripherals::gpio_v3::Port =
            unsafe { crate::_peripherals::gpio_v3::Port::from_ptr(0x400a0120 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for PORT9 {
        type Target = crate::_peripherals::gpio_v3::Port;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for PORT9 {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[8]
        }
    }
    #[derive(Copy, Clone)]
    pub struct RTC_C(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for RTC_C {}
    impl RTC_C {
        pub const REGS: crate::_peripherals::rtc_v1::RtcC =
            unsafe { crate::_peripherals::rtc_v1::RtcC::from_ptr(0x400a2c00 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for RTC_C {
        type Target = crate::_peripherals::rtc_v1::RtcC;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for RTC_C {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[9]
        }
    }
    #[derive(Copy, Clone)]
    pub struct SYSTEM(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for SYSTEM {}
    impl SYSTEM {
        pub const REGS: crate::_peripherals::system_v2::System =
            unsafe { crate::_peripherals::system_v2::System::from_ptr(0x4001e000 as *mut ()) };
        pub unsafe fn steal() -> Self {
            Self(())
        }
    }
    impl core::ops::Deref for SYSTEM {
        type Target = crate::_peripherals::system_v2::System;
        fn deref(&self) -> &Self::Target {
            &Self::REGS
        }
    }
    #[cfg(feature = "metadata")]
    impl crate::Peripheral for SYSTEM {
        fn metadata() -> &'static crate::metadata::Peripheral {
            &crate::metadata::PERIPHERALS[10]
        }
    }
    pub struct Peripherals {
        pub icu: ICU,
        pub mstp: MSTP,
        pub port0: PORT0,
        pub port1: PORT1,
        pub port2: PORT2,
        pub port3: PORT3,
        pub port4: PORT4,
        pub port5: PORT5,
        pub port9: PORT9,
        pub rtc_c: RTC_C,
        pub system: SYSTEM,
        pub iel0: IEL0,
        pub iel1: IEL1,
        pub iel2: IEL2,
        pub iel3: IEL3,
        pub iel4: IEL4,
        pub iel5: IEL5,
        pub iel6: IEL6,
        pub iel7: IEL7,
        pub iel8: IEL8,
        pub iel9: IEL9,
        pub iel10: IEL10,
        pub iel11: IEL11,
        pub iel12: IEL12,
        pub iel13: IEL13,
        pub iel14: IEL14,
        pub iel15: IEL15,
        pub iel16: IEL16,
        pub iel17: IEL17,
        pub iel18: IEL18,
        pub iel19: IEL19,
        pub iel20: IEL20,
        pub iel21: IEL21,
        pub iel22: IEL22,
        pub iel23: IEL23,
        pub iel24: IEL24,
        pub iel25: IEL25,
        pub iel26: IEL26,
        pub iel27: IEL27,
        pub iel28: IEL28,
        pub iel29: IEL29,
        pub iel30: IEL30,
        pub iel31: IEL31,
        pub iel32: IEL32,
        pub iel33: IEL33,
        pub iel34: IEL34,
        pub iel35: IEL35,
        pub iel36: IEL36,
        pub iel37: IEL37,
        pub iel38: IEL38,
        pub iel39: IEL39,
        pub iel40: IEL40,
        pub iel41: IEL41,
        pub iel42: IEL42,
        pub iel43: IEL43,
        pub iel44: IEL44,
        pub iel45: IEL45,
        pub iel46: IEL46,
        pub iel47: IEL47,
        pub iel48: IEL48,
        pub iel49: IEL49,
        pub iel50: IEL50,
        pub iel51: IEL51,
        pub iel52: IEL52,
        pub iel53: IEL53,
        pub iel54: IEL54,
        pub iel55: IEL55,
        pub iel56: IEL56,
        pub iel57: IEL57,
        pub iel58: IEL58,
        pub iel59: IEL59,
        pub iel60: IEL60,
        pub iel61: IEL61,
        pub iel62: IEL62,
        pub iel63: IEL63,
    }
    impl Peripherals {
        pub unsafe fn steal() -> Self {
            Self {
                icu: ICU(()),
                mstp: MSTP(()),
                port0: PORT0(()),
                port1: PORT1(()),
                port2: PORT2(()),
                port3: PORT3(()),
                port4: PORT4(()),
                port5: PORT5(()),
                port9: PORT9(()),
                rtc_c: RTC_C(()),
                system: SYSTEM(()),
                iel0: IEL0(()),
                iel1: IEL1(()),
                iel2: IEL2(()),
                iel3: IEL3(()),
                iel4: IEL4(()),
                iel5: IEL5(()),
                iel6: IEL6(()),
                iel7: IEL7(()),
                iel8: IEL8(()),
                iel9: IEL9(()),
                iel10: IEL10(()),
                iel11: IEL11(()),
                iel12: IEL12(()),
                iel13: IEL13(()),
                iel14: IEL14(()),
                iel15: IEL15(()),
                iel16: IEL16(()),
                iel17: IEL17(()),
                iel18: IEL18(()),
                iel19: IEL19(()),
                iel20: IEL20(()),
                iel21: IEL21(()),
                iel22: IEL22(()),
                iel23: IEL23(()),
                iel24: IEL24(()),
                iel25: IEL25(()),
                iel26: IEL26(()),
                iel27: IEL27(()),
                iel28: IEL28(()),
                iel29: IEL29(()),
                iel30: IEL30(()),
                iel31: IEL31(()),
                iel32: IEL32(()),
                iel33: IEL33(()),
                iel34: IEL34(()),
                iel35: IEL35(()),
                iel36: IEL36(()),
                iel37: IEL37(()),
                iel38: IEL38(()),
                iel39: IEL39(()),
                iel40: IEL40(()),
                iel41: IEL41(()),
                iel42: IEL42(()),
                iel43: IEL43(()),
                iel44: IEL44(()),
                iel45: IEL45(()),
                iel46: IEL46(()),
                iel47: IEL47(()),
                iel48: IEL48(()),
                iel49: IEL49(()),
                iel50: IEL50(()),
                iel51: IEL51(()),
                iel52: IEL52(()),
                iel53: IEL53(()),
                iel54: IEL54(()),
                iel55: IEL55(()),
                iel56: IEL56(()),
                iel57: IEL57(()),
                iel58: IEL58(()),
                iel59: IEL59(()),
                iel60: IEL60(()),
                iel61: IEL61(()),
                iel62: IEL62(()),
                iel63: IEL63(()),
            }
        }
    }
    #[derive(Copy, Clone)]
    pub struct IEL0(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL0 {}
    #[derive(Copy, Clone)]
    pub struct IEL1(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL1 {}
    #[derive(Copy, Clone)]
    pub struct IEL2(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL2 {}
    #[derive(Copy, Clone)]
    pub struct IEL3(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL3 {}
    #[derive(Copy, Clone)]
    pub struct IEL4(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL4 {}
    #[derive(Copy, Clone)]
    pub struct IEL5(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL5 {}
    #[derive(Copy, Clone)]
    pub struct IEL6(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL6 {}
    #[derive(Copy, Clone)]
    pub struct IEL7(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL7 {}
    #[derive(Copy, Clone)]
    pub struct IEL8(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL8 {}
    #[derive(Copy, Clone)]
    pub struct IEL9(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL9 {}
    #[derive(Copy, Clone)]
    pub struct IEL10(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL10 {}
    #[derive(Copy, Clone)]
    pub struct IEL11(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL11 {}
    #[derive(Copy, Clone)]
    pub struct IEL12(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL12 {}
    #[derive(Copy, Clone)]
    pub struct IEL13(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL13 {}
    #[derive(Copy, Clone)]
    pub struct IEL14(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL14 {}
    #[derive(Copy, Clone)]
    pub struct IEL15(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL15 {}
    #[derive(Copy, Clone)]
    pub struct IEL16(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL16 {}
    #[derive(Copy, Clone)]
    pub struct IEL17(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL17 {}
    #[derive(Copy, Clone)]
    pub struct IEL18(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL18 {}
    #[derive(Copy, Clone)]
    pub struct IEL19(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL19 {}
    #[derive(Copy, Clone)]
    pub struct IEL20(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL20 {}
    #[derive(Copy, Clone)]
    pub struct IEL21(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL21 {}
    #[derive(Copy, Clone)]
    pub struct IEL22(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL22 {}
    #[derive(Copy, Clone)]
    pub struct IEL23(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL23 {}
    #[derive(Copy, Clone)]
    pub struct IEL24(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL24 {}
    #[derive(Copy, Clone)]
    pub struct IEL25(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL25 {}
    #[derive(Copy, Clone)]
    pub struct IEL26(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL26 {}
    #[derive(Copy, Clone)]
    pub struct IEL27(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL27 {}
    #[derive(Copy, Clone)]
    pub struct IEL28(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL28 {}
    #[derive(Copy, Clone)]
    pub struct IEL29(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL29 {}
    #[derive(Copy, Clone)]
    pub struct IEL30(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL30 {}
    #[derive(Copy, Clone)]
    pub struct IEL31(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL31 {}
    #[derive(Copy, Clone)]
    pub struct IEL32(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL32 {}
    #[derive(Copy, Clone)]
    pub struct IEL33(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL33 {}
    #[derive(Copy, Clone)]
    pub struct IEL34(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL34 {}
    #[derive(Copy, Clone)]
    pub struct IEL35(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL35 {}
    #[derive(Copy, Clone)]
    pub struct IEL36(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL36 {}
    #[derive(Copy, Clone)]
    pub struct IEL37(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL37 {}
    #[derive(Copy, Clone)]
    pub struct IEL38(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL38 {}
    #[derive(Copy, Clone)]
    pub struct IEL39(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL39 {}
    #[derive(Copy, Clone)]
    pub struct IEL40(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL40 {}
    #[derive(Copy, Clone)]
    pub struct IEL41(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL41 {}
    #[derive(Copy, Clone)]
    pub struct IEL42(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL42 {}
    #[derive(Copy, Clone)]
    pub struct IEL43(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL43 {}
    #[derive(Copy, Clone)]
    pub struct IEL44(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL44 {}
    #[derive(Copy, Clone)]
    pub struct IEL45(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL45 {}
    #[derive(Copy, Clone)]
    pub struct IEL46(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL46 {}
    #[derive(Copy, Clone)]
    pub struct IEL47(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL47 {}
    #[derive(Copy, Clone)]
    pub struct IEL48(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL48 {}
    #[derive(Copy, Clone)]
    pub struct IEL49(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL49 {}
    #[derive(Copy, Clone)]
    pub struct IEL50(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL50 {}
    #[derive(Copy, Clone)]
    pub struct IEL51(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL51 {}
    #[derive(Copy, Clone)]
    pub struct IEL52(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL52 {}
    #[derive(Copy, Clone)]
    pub struct IEL53(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL53 {}
    #[derive(Copy, Clone)]
    pub struct IEL54(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL54 {}
    #[derive(Copy, Clone)]
    pub struct IEL55(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL55 {}
    #[derive(Copy, Clone)]
    pub struct IEL56(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL56 {}
    #[derive(Copy, Clone)]
    pub struct IEL57(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL57 {}
    #[derive(Copy, Clone)]
    pub struct IEL58(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL58 {}
    #[derive(Copy, Clone)]
    pub struct IEL59(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL59 {}
    #[derive(Copy, Clone)]
    pub struct IEL60(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL60 {}
    #[derive(Copy, Clone)]
    pub struct IEL61(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL61 {}
    #[derive(Copy, Clone)]
    pub struct IEL62(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL62 {}
    #[derive(Copy, Clone)]
    pub struct IEL63(());
    #[cfg(feature = "embassy")]
    impl embassy_hal_internal::PeripheralType for IEL63 {}
}
#[macro_export]
macro_rules! foreach_interrupt {
    ($m:path, $($args:tt)*) => {
        $m! { $($args)* {
            IEL0 = 0,
            IEL1 = 1,
            IEL2 = 2,
            IEL3 = 3,
            IEL4 = 4,
            IEL5 = 5,
            IEL6 = 6,
            IEL7 = 7,
            IEL8 = 8,
            IEL9 = 9,
            IEL10 = 10,
            IEL11 = 11,
            IEL12 = 12,
            IEL13 = 13,
            IEL14 = 14,
            IEL15 = 15,
            IEL16 = 16,
            IEL17 = 17,
            IEL18 = 18,
            IEL19 = 19,
            IEL20 = 20,
            IEL21 = 21,
            IEL22 = 22,
            IEL23 = 23,
            IEL24 = 24,
            IEL25 = 25,
            IEL26 = 26,
            IEL27 = 27,
            IEL28 = 28,
            IEL29 = 29,
            IEL30 = 30,
            IEL31 = 31,
            IEL32 = 32,
            IEL33 = 33,
            IEL34 = 34,
            IEL35 = 35,
            IEL36 = 36,
            IEL37 = 37,
            IEL38 = 38,
            IEL39 = 39,
            IEL40 = 40,
            IEL41 = 41,
            IEL42 = 42,
            IEL43 = 43,
            IEL44 = 44,
            IEL45 = 45,
            IEL46 = 46,
            IEL47 = 47,
            IEL48 = 48,
            IEL49 = 49,
            IEL50 = 50,
            IEL51 = 51,
            IEL52 = 52,
            IEL53 = 53,
            IEL54 = 54,
            IEL55 = 55,
            IEL56 = 56,
            IEL57 = 57,
            IEL58 = 58,
            IEL59 = 59,
            IEL60 = 60,
            IEL61 = 61,
            IEL62 = 62,
            IEL63 = 63,
        } }
    };
    ($($m:tt)*) => {
        $($m)*! {
            IEL0 = 0,
            IEL1 = 1,
            IEL2 = 2,
            IEL3 = 3,
            IEL4 = 4,
            IEL5 = 5,
            IEL6 = 6,
            IEL7 = 7,
            IEL8 = 8,
            IEL9 = 9,
            IEL10 = 10,
            IEL11 = 11,
            IEL12 = 12,
            IEL13 = 13,
            IEL14 = 14,
            IEL15 = 15,
            IEL16 = 16,
            IEL17 = 17,
            IEL18 = 18,
            IEL19 = 19,
            IEL20 = 20,
            IEL21 = 21,
            IEL22 = 22,
            IEL23 = 23,
            IEL24 = 24,
            IEL25 = 25,
            IEL26 = 26,
            IEL27 = 27,
            IEL28 = 28,
            IEL29 = 29,
            IEL30 = 30,
            IEL31 = 31,
            IEL32 = 32,
            IEL33 = 33,
            IEL34 = 34,
            IEL35 = 35,
            IEL36 = 36,
            IEL37 = 37,
            IEL38 = 38,
            IEL39 = 39,
            IEL40 = 40,
            IEL41 = 41,
            IEL42 = 42,
            IEL43 = 43,
            IEL44 = 44,
            IEL45 = 45,
            IEL46 = 46,
            IEL47 = 47,
            IEL48 = 48,
            IEL49 = 49,
            IEL50 = 50,
            IEL51 = 51,
            IEL52 = 52,
            IEL53 = 53,
            IEL54 = 54,
            IEL55 = 55,
            IEL56 = 56,
            IEL57 = 57,
            IEL58 = 58,
            IEL59 = 59,
            IEL60 = 60,
            IEL61 = 61,
            IEL62 = 62,
            IEL63 = 63,
        }
    };
}
#[macro_export]
macro_rules! foreach_event {
    ($m:path, $($args:tt)*) => {
        $m! { $($args)* {
            IcuIrq0 = 1,
            IcuIrq1 = 2,
            IcuIrq2 = 3,
            IcuIrq3 = 4,
            IcuIrq4 = 5,
            IcuIrq5 = 6,
            RtcAlarmOrPeriod = 7,
            Tml0Itl0 = 8,
            Tml0Itl1 = 9,
            Tml0Itl2 = 10,
            Tml0Itl3 = 11,
            Tau0Tmi00 = 12,
            Tau0Tmi01 = 13,
            Tau0Tmi02 = 14,
            Tau0Tmi03 = 15,
            Sau0UartTxi0 = 16,
            Sau0SpiTxrxi00 = 16,
            Sau0IicTxrxi00 = 16,
            Sau0UartRxi0 = 17,
            Sau0SpiTxrxi01 = 17,
            Sau0IicTxrxi01 = 17,
            DtcEnd = 18,
            LvdLvd1 = 19,
            ElcSoftwareEvent0 = 20,
            ElcSoftwareEvent1 = 21,
            Adc0ScanEnd = 22,
            Uarta0Erri = 23,
            Uarta0Txi = 24,
            Uarta0Rxi = 25,
            Iica0Txrxi = 26,
            IcuIrq6 = 27,
            IcuIrq7 = 28,
            Uarta1Erri = 29,
            Uarta1Txi = 30,
            Uarta1Rxi = 31,
            Iica1Txrxi = 32,
        } }
    };
    ($($m:tt)*) => {
        $($m)*! {
            IcuIrq0 = 1,
            IcuIrq1 = 2,
            IcuIrq2 = 3,
            IcuIrq3 = 4,
            IcuIrq4 = 5,
            IcuIrq5 = 6,
            RtcAlarmOrPeriod = 7,
            Tml0Itl0 = 8,
            Tml0Itl1 = 9,
            Tml0Itl2 = 10,
            Tml0Itl3 = 11,
            Tau0Tmi00 = 12,
            Tau0Tmi01 = 13,
            Tau0Tmi02 = 14,
            Tau0Tmi03 = 15,
            Sau0UartTxi0 = 16,
            Sau0SpiTxrxi00 = 16,
            Sau0IicTxrxi00 = 16,
            Sau0UartRxi0 = 17,
            Sau0SpiTxrxi01 = 17,
            Sau0IicTxrxi01 = 17,
            DtcEnd = 18,
            LvdLvd1 = 19,
            ElcSoftwareEvent0 = 20,
            ElcSoftwareEvent1 = 21,
            Adc0ScanEnd = 22,
            Uarta0Erri = 23,
            Uarta0Txi = 24,
            Uarta0Rxi = 25,
            Iica0Txrxi = 26,
            IcuIrq6 = 27,
            IcuIrq7 = 28,
            Uarta1Erri = 29,
            Uarta1Txi = 30,
            Uarta1Rxi = 31,
            Iica1Txrxi = 32,
        }
    };
}
#[macro_export]
macro_rules! foreach_peripheral {
    ($m:path) => {
        $m! {
            ICU = 0,
            MSTP = 1,
            PORT0 = 2,
            PORT1 = 3,
            PORT2 = 4,
            PORT3 = 5,
            PORT4 = 6,
            PORT5 = 7,
            PORT9 = 8,
            RTC_C = 9,
            SYSTEM = 10,
        }
    };
}
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Event {
    /// External pin interrupt 0
    IcuIrq0 = 1,
    /// External pin interrupt 1
    IcuIrq1 = 2,
    /// External pin interrupt 2
    IcuIrq2 = 3,
    /// External pin interrupt 3
    IcuIrq3 = 4,
    /// External pin interrupt 4
    IcuIrq4 = 5,
    /// External pin interrupt 5
    IcuIrq5 = 6,
    /// Alarm or Periodic interrupt
    RtcAlarmOrPeriod = 7,
    /// TML timer0 compare-match
    Tml0Itl0 = 8,
    /// TML timer1 compare-match
    Tml0Itl1 = 9,
    /// TML timer2 compare-match
    Tml0Itl2 = 10,
    /// TML timer3 compare-match
    Tml0Itl3 = 11,
    /// End of timer channel 00 count or capture
    Tau0Tmi00 = 12,
    /// End of timer channel 01 count or capture
    Tau0Tmi01 = 13,
    /// End of timer channel 02 count or capture
    Tau0Tmi02 = 14,
    /// End of timer channel 03 count or capture
    Tau0Tmi03 = 15,
    /// SAU UART TX 0/I2C 00/SPI 00
    Sau0UartTxi0 = 16,
    /// SAU UART RX 0/I2C 01/SPI 01
    Sau0UartRxi0 = 17,
    /// DTC transfer end
    DtcEnd = 18,
    /// Voltage monitor 1 interrupt
    LvdLvd1 = 19,
    /// Software event 0
    ElcSoftwareEvent0 = 20,
    /// Software event 1
    ElcSoftwareEvent1 = 21,
    /// End of A/D scanning operation
    Adc0ScanEnd = 22,
    /// UARTA0 reception communication error occurrence
    Uarta0Erri = 23,
    /// UARTA0 transmission transfer end or buffer empty interrupt
    Uarta0Txi = 24,
    /// UARTA0 reception transfer end
    Uarta0Rxi = 25,
    /// End of IICA0 communication
    Iica0Txrxi = 26,
    /// External pin interrupt 6
    IcuIrq6 = 27,
    /// External pin interrupt 7
    IcuIrq7 = 28,
    /// UARTA1 reception communication error occurrence
    Uarta1Erri = 29,
    /// UARTA1 transmission transfer end or buffer empty interrupt
    Uarta1Txi = 30,
    /// UARTA1 reception transfer end
    Uarta1Rxi = 31,
    /// End of IICA1 communication
    Iica1Txrxi = 32,
}
#[allow(non_upper_case_globals)]
impl Event {
    /// SAU UART TX 0/I2C 00/SPI 00
    pub const Sau0SpiTxrxi00: Self = Self::Sau0UartTxi0;
    /// SAU UART TX 0/I2C 00/SPI 00
    pub const Sau0IicTxrxi00: Self = Self::Sau0UartTxi0;
    /// SAU UART RX 0/I2C 01/SPI 01
    pub const Sau0SpiTxrxi01: Self = Self::Sau0UartRxi0;
    /// SAU UART RX 0/I2C 01/SPI 01
    pub const Sau0IicTxrxi01: Self = Self::Sau0UartRxi0;
}
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    IEL0 = 0,
    IEL1 = 1,
    IEL2 = 2,
    IEL3 = 3,
    IEL4 = 4,
    IEL5 = 5,
    IEL6 = 6,
    IEL7 = 7,
    IEL8 = 8,
    IEL9 = 9,
    IEL10 = 10,
    IEL11 = 11,
    IEL12 = 12,
    IEL13 = 13,
    IEL14 = 14,
    IEL15 = 15,
    IEL16 = 16,
    IEL17 = 17,
    IEL18 = 18,
    IEL19 = 19,
    IEL20 = 20,
    IEL21 = 21,
    IEL22 = 22,
    IEL23 = 23,
    IEL24 = 24,
    IEL25 = 25,
    IEL26 = 26,
    IEL27 = 27,
    IEL28 = 28,
    IEL29 = 29,
    IEL30 = 30,
    IEL31 = 31,
    IEL32 = 32,
    IEL33 = 33,
    IEL34 = 34,
    IEL35 = 35,
    IEL36 = 36,
    IEL37 = 37,
    IEL38 = 38,
    IEL39 = 39,
    IEL40 = 40,
    IEL41 = 41,
    IEL42 = 42,
    IEL43 = 43,
    IEL44 = 44,
    IEL45 = 45,
    IEL46 = 46,
    IEL47 = 47,
    IEL48 = 48,
    IEL49 = 49,
    IEL50 = 50,
    IEL51 = 51,
    IEL52 = 52,
    IEL53 = 53,
    IEL54 = 54,
    IEL55 = 55,
    IEL56 = 56,
    IEL57 = 57,
    IEL58 = 58,
    IEL59 = 59,
    IEL60 = 60,
    IEL61 = 61,
    IEL62 = 62,
    IEL63 = 63,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[cfg(feature = "embassy")]
embassy_hal_internal::interrupt_mod!(
    IEL0, IEL1, IEL2, IEL3, IEL4, IEL5, IEL6, IEL7, IEL8, IEL9, IEL10, IEL11, IEL12, IEL13, IEL14,
    IEL15, IEL16, IEL17, IEL18, IEL19, IEL20, IEL21, IEL22, IEL23, IEL24, IEL25, IEL26, IEL27,
    IEL28, IEL29, IEL30, IEL31, IEL32, IEL33, IEL34, IEL35, IEL36, IEL37, IEL38, IEL39, IEL40,
    IEL41, IEL42, IEL43, IEL44, IEL45, IEL46, IEL47, IEL48, IEL49, IEL50, IEL51, IEL52, IEL53,
    IEL54, IEL55, IEL56, IEL57, IEL58, IEL59, IEL60, IEL61, IEL62, IEL63,
);
extern "C" {
    pub fn IEL0();
    pub fn IEL1();
    pub fn IEL2();
    pub fn IEL3();
    pub fn IEL4();
    pub fn IEL5();
    pub fn IEL6();
    pub fn IEL7();
    pub fn IEL8();
    pub fn IEL9();
    pub fn IEL10();
    pub fn IEL11();
    pub fn IEL12();
    pub fn IEL13();
    pub fn IEL14();
    pub fn IEL15();
    pub fn IEL16();
    pub fn IEL17();
    pub fn IEL18();
    pub fn IEL19();
    pub fn IEL20();
    pub fn IEL21();
    pub fn IEL22();
    pub fn IEL23();
    pub fn IEL24();
    pub fn IEL25();
    pub fn IEL26();
    pub fn IEL27();
    pub fn IEL28();
    pub fn IEL29();
    pub fn IEL30();
    pub fn IEL31();
    pub fn IEL32();
    pub fn IEL33();
    pub fn IEL34();
    pub fn IEL35();
    pub fn IEL36();
    pub fn IEL37();
    pub fn IEL38();
    pub fn IEL39();
    pub fn IEL40();
    pub fn IEL41();
    pub fn IEL42();
    pub fn IEL43();
    pub fn IEL44();
    pub fn IEL45();
    pub fn IEL46();
    pub fn IEL47();
    pub fn IEL48();
    pub fn IEL49();
    pub fn IEL50();
    pub fn IEL51();
    pub fn IEL52();
    pub fn IEL53();
    pub fn IEL54();
    pub fn IEL55();
    pub fn IEL56();
    pub fn IEL57();
    pub fn IEL58();
    pub fn IEL59();
    pub fn IEL60();
    pub fn IEL61();
    pub fn IEL62();
    pub fn IEL63();
}
#[derive(Copy, Clone)]
#[repr(C)]
pub union Vector {
    pub _handler: unsafe extern "C" fn(),
    pub _reserved: u32,
}
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 64] = [
    Vector { _handler: IEL0 },
    Vector { _handler: IEL1 },
    Vector { _handler: IEL2 },
    Vector { _handler: IEL3 },
    Vector { _handler: IEL4 },
    Vector { _handler: IEL5 },
    Vector { _handler: IEL6 },
    Vector { _handler: IEL7 },
    Vector { _handler: IEL8 },
    Vector { _handler: IEL9 },
    Vector { _handler: IEL10 },
    Vector { _handler: IEL11 },
    Vector { _handler: IEL12 },
    Vector { _handler: IEL13 },
    Vector { _handler: IEL14 },
    Vector { _handler: IEL15 },
    Vector { _handler: IEL16 },
    Vector { _handler: IEL17 },
    Vector { _handler: IEL18 },
    Vector { _handler: IEL19 },
    Vector { _handler: IEL20 },
    Vector { _handler: IEL21 },
    Vector { _handler: IEL22 },
    Vector { _handler: IEL23 },
    Vector { _handler: IEL24 },
    Vector { _handler: IEL25 },
    Vector { _handler: IEL26 },
    Vector { _handler: IEL27 },
    Vector { _handler: IEL28 },
    Vector { _handler: IEL29 },
    Vector { _handler: IEL30 },
    Vector { _handler: IEL31 },
    Vector { _handler: IEL32 },
    Vector { _handler: IEL33 },
    Vector { _handler: IEL34 },
    Vector { _handler: IEL35 },
    Vector { _handler: IEL36 },
    Vector { _handler: IEL37 },
    Vector { _handler: IEL38 },
    Vector { _handler: IEL39 },
    Vector { _handler: IEL40 },
    Vector { _handler: IEL41 },
    Vector { _handler: IEL42 },
    Vector { _handler: IEL43 },
    Vector { _handler: IEL44 },
    Vector { _handler: IEL45 },
    Vector { _handler: IEL46 },
    Vector { _handler: IEL47 },
    Vector { _handler: IEL48 },
    Vector { _handler: IEL49 },
    Vector { _handler: IEL50 },
    Vector { _handler: IEL51 },
    Vector { _handler: IEL52 },
    Vector { _handler: IEL53 },
    Vector { _handler: IEL54 },
    Vector { _handler: IEL55 },
    Vector { _handler: IEL56 },
    Vector { _handler: IEL57 },
    Vector { _handler: IEL58 },
    Vector { _handler: IEL59 },
    Vector { _handler: IEL60 },
    Vector { _handler: IEL61 },
    Vector { _handler: IEL62 },
    Vector { _handler: IEL63 },
];
