// This file is autogenerated by ra-metapac-gen: do not edit by hand.
pub const NAME: &str = "R7FA0E2074CFM";
pub const FAMILY: &str = "R7FA0E2";
pub const CORE: &str = "Cortex-M23";
pub const MEMORY: &[MemoryRegion] = &[
    MemoryRegion {
        name: "RAM",
        kind: "RAM",
        address: 536887296,
        size: 16384,
    },
    MemoryRegion {
        name: "FLASH",
        kind: "ROM",
        address: 0,
        size: 65536,
    },
    MemoryRegion {
        name: "DATA_FLASH",
        kind: "ROM",
        address: 1074790400,
        size: 2048,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OFS0",
        kind: "ROM",
        address: 1024,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OFS1",
        kind: "ROM",
        address: 1028,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OSIS",
        kind: "ROM",
        address: 16842776,
        size: 32,
    },
];
pub const PERIPHERALS: &[Peripheral] = &[
    Peripheral {
        name: "ICU",
        address: 1073766400,
        kind: "icu",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "MSTP",
        address: 1074032640,
        kind: "mstp",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT0",
        address: 1074397184,
        kind: "gpio",
        version: "v3",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT1",
        address: 1074397216,
        kind: "gpio",
        version: "v3",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT2",
        address: 1074397248,
        kind: "gpio",
        version: "v3",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT3",
        address: 1074397280,
        kind: "gpio",
        version: "v3",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT4",
        address: 1074397312,
        kind: "gpio",
        version: "v3",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT5",
        address: 1074397344,
        kind: "gpio",
        version: "v3",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT9",
        address: 1074397472,
        kind: "gpio",
        version: "v3",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "RTC_C",
        address: 1074408448,
        kind: "rtc",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "SYSTEM",
        address: 1073864704,
        kind: "system",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
];
pub const PACKAGES: &[Package] = &[Package {
    name: "64LFQFP",
    pins: &[
        Pin {
            position: "64",
            signals: &["p000"],
        },
        Pin {
            position: "63",
            signals: &["p001"],
        },
        Pin {
            position: "62",
            signals: &["p002"],
        },
        Pin {
            position: "61",
            signals: &["p003"],
        },
        Pin {
            position: "60",
            signals: &["p004"],
        },
        Pin {
            position: "57",
            signals: &["p008"],
        },
        Pin {
            position: "56",
            signals: &["p009"],
        },
        Pin {
            position: "59",
            signals: &["p010"],
        },
        Pin {
            position: "58",
            signals: &["p011"],
        },
        Pin {
            position: "55",
            signals: &["p012"],
        },
        Pin {
            position: "54",
            signals: &["p013"],
        },
        Pin {
            position: "53",
            signals: &["p014"],
        },
        Pin {
            position: "52",
            signals: &["p015"],
        },
        Pin {
            position: "48",
            signals: &["p100"],
        },
        Pin {
            position: "47",
            signals: &["p101"],
        },
        Pin {
            position: "46",
            signals: &["p102"],
        },
        Pin {
            position: "45",
            signals: &["p103"],
        },
        Pin {
            position: "44",
            signals: &["p104"],
        },
        Pin {
            position: "43",
            signals: &["p105"],
        },
        Pin {
            position: "42",
            signals: &["p106"],
        },
        Pin {
            position: "41",
            signals: &["p107"],
        },
        Pin {
            position: "33",
            signals: &["p108"],
        },
        Pin {
            position: "34",
            signals: &["p109"],
        },
        Pin {
            position: "35",
            signals: &["p110"],
        },
        Pin {
            position: "36",
            signals: &["p111"],
        },
        Pin {
            position: "37",
            signals: &["p112"],
        },
        Pin {
            position: "38",
            signals: &["p113"],
        },
        Pin {
            position: "39",
            signals: &["p114"],
        },
        Pin {
            position: "40",
            signals: &["p115"],
        },
        Pin {
            position: "27",
            signals: &["p200"],
        },
        Pin {
            position: "26",
            signals: &["p201"],
        },
        Pin {
            position: "24",
            signals: &["p204"],
        },
        Pin {
            position: "23",
            signals: &["p205"],
        },
        Pin {
            position: "22",
            signals: &["p206"],
        },
        Pin {
            position: "21",
            signals: &["p207"],
        },
        Pin {
            position: "20",
            signals: &["p208"],
        },
        Pin {
            position: "10",
            signals: &["p212"],
        },
        Pin {
            position: "9",
            signals: &["p213"],
        },
        Pin {
            position: "7",
            signals: &["p214"],
        },
        Pin {
            position: "6",
            signals: &["p215"],
        },
        Pin {
            position: "32",
            signals: &["p300"],
        },
        Pin {
            position: "31",
            signals: &["p301"],
        },
        Pin {
            position: "30",
            signals: &["p302"],
        },
        Pin {
            position: "29",
            signals: &["p303"],
        },
        Pin {
            position: "28",
            signals: &["p304"],
        },
        Pin {
            position: "1",
            signals: &["p400"],
        },
        Pin {
            position: "2",
            signals: &["p401"],
        },
        Pin {
            position: "3",
            signals: &["p402"],
        },
        Pin {
            position: "4",
            signals: &["p403"],
        },
        Pin {
            position: "16",
            signals: &["p407"],
        },
        Pin {
            position: "15",
            signals: &["p408"],
        },
        Pin {
            position: "14",
            signals: &["p409"],
        },
        Pin {
            position: "13",
            signals: &["p410"],
        },
        Pin {
            position: "12",
            signals: &["p411"],
        },
        Pin {
            position: "49",
            signals: &["p500"],
        },
        Pin {
            position: "50",
            signals: &["p501"],
        },
        Pin {
            position: "51",
            signals: &["p502"],
        },
        Pin {
            position: "19",
            signals: &["p913"],
        },
        Pin {
            position: "18",
            signals: &["p914"],
        },
        Pin {
            position: "17",
            signals: &["p915"],
        },
        Pin {
            position: "25",
            signals: &["res"],
        },
        Pin {
            position: "11",
            signals: &["vcc"],
        },
        Pin {
            position: "5",
            signals: &["vcl"],
        },
        Pin {
            position: "8",
            signals: &["vss"],
        },
    ],
}];
