// This file is autogenerated by ra-metapac-gen: do not edit by hand.
pub const NAME: &str = "R7FA8T1AHECFC";
pub const FAMILY: &str = "R7FA8T1";
pub const CORE: &str = "Cortex-M85";
pub const MEMORY: &[MemoryRegion] = &[
    MemoryRegion {
        name: "RAM_NS",
        kind: "RAM",
        address: 838860800,
        size: 917504,
    },
    MemoryRegion {
        name: "RAM",
        kind: "RAM",
        address: 570425344,
        size: 917504,
    },
    MemoryRegion {
        name: "FLASH_NS",
        kind: "ROM",
        address: 301989888,
        size: 2064384,
    },
    MemoryRegion {
        name: "FLASH",
        kind: "ROM",
        address: 33554432,
        size: 2064384,
    },
    MemoryRegion {
        name: "DATA_FLASH_NS",
        kind: "ROM",
        address: 922746880,
        size: 12288,
    },
    MemoryRegion {
        name: "DATA_FLASH",
        kind: "ROM",
        address: 654311424,
        size: 12288,
    },
    MemoryRegion {
        name: "SDRAM",
        kind: "RAM",
        address: 1744830464,
        size: 134217728,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OFS0",
        kind: "ROM",
        address: 50372864,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OFS2",
        kind: "ROM",
        address: 50372868,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_DUALSEL",
        kind: "ROM",
        address: 50372880,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OFS1",
        kind: "ROM",
        address: 318808448,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BANKSEL",
        kind: "ROM",
        address: 318808464,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BPS",
        kind: "ROM",
        address: 318808512,
        size: 16,
    },
    MemoryRegion {
        name: "OPTION_SETTING_PBPS",
        kind: "ROM",
        address: 318808544,
        size: 16,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OFS1_SEC",
        kind: "ROM",
        address: 50373120,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BANKSEL_SEC",
        kind: "ROM",
        address: 50373136,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BPS_SEC",
        kind: "ROM",
        address: 50373184,
        size: 16,
    },
    MemoryRegion {
        name: "OPTION_SETTING_PBPS_SEC",
        kind: "ROM",
        address: 50373216,
        size: 16,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OFS1_SEL",
        kind: "ROM",
        address: 50373248,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BANKSEL_SEL",
        kind: "ROM",
        address: 50373264,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BPS_SEL",
        kind: "ROM",
        address: 50373312,
        size: 16,
    },
    MemoryRegion {
        name: "ITCM_NS",
        kind: "RAM",
        address: 268435456,
        size: 65536,
    },
    MemoryRegion {
        name: "ITCM",
        kind: "RAM",
        address: 0,
        size: 65536,
    },
    MemoryRegion {
        name: "DTCM_NS",
        kind: "RAM",
        address: 805306368,
        size: 65536,
    },
    MemoryRegion {
        name: "DTCM",
        kind: "RAM",
        address: 536870912,
        size: 65536,
    },
];
pub const PERIPHERALS: &[Peripheral] = &[
    Peripheral {
        name: "GPT",
        address: 1077026816,
        kind: "timer",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT0",
        address: 1077026816,
        kind: "timer",
        version: "v2",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT1",
        address: 1077027072,
        kind: "timer",
        version: "v2",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT2",
        address: 1077027328,
        kind: "timer",
        version: "v2",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT3",
        address: 1077027584,
        kind: "timer",
        version: "v2",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT4",
        address: 1077027840,
        kind: "timer",
        version: "v2",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT5",
        address: 1077028096,
        kind: "timer",
        version: "v2",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT6",
        address: 1077028352,
        kind: "timer",
        version: "v2",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT7",
        address: 1077028608,
        kind: "timer",
        version: "v2",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT8",
        address: 1077028864,
        kind: "timer",
        version: "v2",
        mstp: None,
        bit_width: Some(16),
    },
    Peripheral {
        name: "GPT9",
        address: 1077029120,
        kind: "timer",
        version: "v2",
        mstp: None,
        bit_width: Some(16),
    },
    Peripheral {
        name: "GPT10",
        address: 1077029376,
        kind: "timer",
        version: "v2",
        mstp: None,
        bit_width: Some(16),
    },
    Peripheral {
        name: "GPT11",
        address: 1077029632,
        kind: "timer",
        version: "v2",
        mstp: None,
        bit_width: Some(16),
    },
    Peripheral {
        name: "GPT12",
        address: 1077029888,
        kind: "timer",
        version: "v2",
        mstp: None,
        bit_width: Some(16),
    },
    Peripheral {
        name: "GPT13",
        address: 1077030144,
        kind: "timer",
        version: "v2",
        mstp: None,
        bit_width: Some(16),
    },
    Peripheral {
        name: "GPT_OPS",
        address: 1077034752,
        kind: "timer",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT_POEG",
        address: 1075912704,
        kind: "timer",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT_POEG0",
        address: 1075912704,
        kind: "timer",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT_POEG1",
        address: 1075912960,
        kind: "timer",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT_POEG2",
        address: 1075913216,
        kind: "timer",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT_POEG3",
        address: 1075913472,
        kind: "timer",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "ICU",
        address: 1073766400,
        kind: "icu",
        version: "v5",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "MSTP",
        address: 1075851264,
        kind: "mstp",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT0",
        address: 1077936128,
        kind: "gpio",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT1",
        address: 1077936160,
        kind: "gpio",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT2",
        address: 1077936192,
        kind: "gpio",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT3",
        address: 1077936224,
        kind: "gpio",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT4",
        address: 1077936256,
        kind: "gpio",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT5",
        address: 1077936288,
        kind: "gpio",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT6",
        address: 1077936320,
        kind: "gpio",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT7",
        address: 1077936352,
        kind: "gpio",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT8",
        address: 1077936384,
        kind: "gpio",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT9",
        address: 1077936416,
        kind: "gpio",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "SYSTEM",
        address: 1073864704,
        kind: "system",
        version: "v5",
        mstp: None,
        bit_width: None,
    },
];
pub const PACKAGES: &[Package] = &[Package {
    name: "176QFP",
    pins: &[
        Pin {
            position: "155",
            signals: &["avcc0"],
        },
        Pin {
            position: "156",
            signals: &["avss0"],
        },
        Pin {
            position: "27",
            signals: &["nc"],
        },
        Pin {
            position: "29",
            signals: &["nc"],
        },
        Pin {
            position: "30",
            signals: &["nc"],
        },
        Pin {
            position: "169",
            signals: &["p000"],
        },
        Pin {
            position: "168",
            signals: &["p001"],
        },
        Pin {
            position: "167",
            signals: &["p002"],
        },
        Pin {
            position: "166",
            signals: &["p003"],
        },
        Pin {
            position: "165",
            signals: &["p004"],
        },
        Pin {
            position: "164",
            signals: &["p005"],
        },
        Pin {
            position: "163",
            signals: &["p006"],
        },
        Pin {
            position: "162",
            signals: &["p007"],
        },
        Pin {
            position: "161",
            signals: &["p008"],
        },
        Pin {
            position: "160",
            signals: &["p009"],
        },
        Pin {
            position: "159",
            signals: &["p010"],
        },
        Pin {
            position: "152",
            signals: &["p014"],
        },
        Pin {
            position: "151",
            signals: &["p015"],
        },
        Pin {
            position: "132",
            signals: &["p100"],
        },
        Pin {
            position: "129",
            signals: &["p101"],
        },
        Pin {
            position: "128",
            signals: &["p102"],
        },
        Pin {
            position: "127",
            signals: &["p103"],
        },
        Pin {
            position: "126",
            signals: &["p104"],
        },
        Pin {
            position: "125",
            signals: &["p105"],
        },
        Pin {
            position: "124",
            signals: &["p106"],
        },
        Pin {
            position: "123",
            signals: &["p107"],
        },
        Pin {
            position: "89",
            signals: &["p112"],
        },
        Pin {
            position: "90",
            signals: &["p113"],
        },
        Pin {
            position: "91",
            signals: &["p114"],
        },
        Pin {
            position: "92",
            signals: &["p115"],
        },
        Pin {
            position: "68",
            signals: &["p200"],
        },
        Pin {
            position: "67",
            signals: &["p201"],
        },
        Pin {
            position: "53",
            signals: &["p202"],
        },
        Pin {
            position: "52",
            signals: &["p203"],
        },
        Pin {
            position: "51",
            signals: &["p204"],
        },
        Pin {
            position: "50",
            signals: &["p205"],
        },
        Pin {
            position: "49",
            signals: &["p206"],
        },
        Pin {
            position: "65",
            signals: &["p208"],
        },
        Pin {
            position: "64",
            signals: &["p209"],
        },
        Pin {
            position: "63",
            signals: &["p210"],
        },
        Pin {
            position: "62",
            signals: &["p211"],
        },
        Pin {
            position: "24",
            signals: &["p212"],
        },
        Pin {
            position: "23",
            signals: &["p213"],
        },
        Pin {
            position: "88",
            signals: &["p300"],
        },
        Pin {
            position: "87",
            signals: &["p301"],
        },
        Pin {
            position: "86",
            signals: &["p302"],
        },
        Pin {
            position: "85",
            signals: &["p303"],
        },
        Pin {
            position: "82",
            signals: &["p304"],
        },
        Pin {
            position: "81",
            signals: &["p305"],
        },
        Pin {
            position: "80",
            signals: &["p306"],
        },
        Pin {
            position: "79",
            signals: &["p307"],
        },
        Pin {
            position: "78",
            signals: &["p308"],
        },
        Pin {
            position: "77",
            signals: &["p309"],
        },
        Pin {
            position: "76",
            signals: &["p310"],
        },
        Pin {
            position: "75",
            signals: &["p311"],
        },
        Pin {
            position: "74",
            signals: &["p312"],
        },
        Pin {
            position: "54",
            signals: &["p313"],
        },
        Pin {
            position: "55",
            signals: &["p314"],
        },
        Pin {
            position: "56",
            signals: &["p315"],
        },
        Pin {
            position: "1",
            signals: &["p400"],
        },
        Pin {
            position: "2",
            signals: &["p401"],
        },
        Pin {
            position: "3",
            signals: &["p402"],
        },
        Pin {
            position: "4",
            signals: &["p403"],
        },
        Pin {
            position: "5",
            signals: &["p404"],
        },
        Pin {
            position: "6",
            signals: &["p405"],
        },
        Pin {
            position: "7",
            signals: &["p406"],
        },
        Pin {
            position: "44",
            signals: &["p407"],
        },
        Pin {
            position: "43",
            signals: &["p408"],
        },
        Pin {
            position: "42",
            signals: &["p409"],
        },
        Pin {
            position: "41",
            signals: &["p410"],
        },
        Pin {
            position: "40",
            signals: &["p411"],
        },
        Pin {
            position: "39",
            signals: &["p412"],
        },
        Pin {
            position: "38",
            signals: &["p413"],
        },
        Pin {
            position: "37",
            signals: &["p414"],
        },
        Pin {
            position: "36",
            signals: &["p415"],
        },
        Pin {
            position: "145",
            signals: &["p500"],
        },
        Pin {
            position: "146",
            signals: &["p501"],
        },
        Pin {
            position: "147",
            signals: &["p502"],
        },
        Pin {
            position: "176",
            signals: &["p511"],
        },
        Pin {
            position: "175",
            signals: &["p512"],
        },
        Pin {
            position: "174",
            signals: &["p513"],
        },
        Pin {
            position: "122",
            signals: &["p600"],
        },
        Pin {
            position: "121",
            signals: &["p601"],
        },
        Pin {
            position: "120",
            signals: &["p602"],
        },
        Pin {
            position: "119",
            signals: &["p603"],
        },
        Pin {
            position: "118",
            signals: &["p604"],
        },
        Pin {
            position: "117",
            signals: &["p605"],
        },
        Pin {
            position: "116",
            signals: &["p606"],
        },
        Pin {
            position: "110",
            signals: &["p607"],
        },
        Pin {
            position: "93",
            signals: &["p609"],
        },
        Pin {
            position: "96",
            signals: &["p610"],
        },
        Pin {
            position: "97",
            signals: &["p611"],
        },
        Pin {
            position: "98",
            signals: &["p612"],
        },
        Pin {
            position: "99",
            signals: &["p613"],
        },
        Pin {
            position: "100",
            signals: &["p614"],
        },
        Pin {
            position: "101",
            signals: &["p615"],
        },
        Pin {
            position: "8",
            signals: &["p700"],
        },
        Pin {
            position: "9",
            signals: &["p701"],
        },
        Pin {
            position: "10",
            signals: &["p702"],
        },
        Pin {
            position: "11",
            signals: &["p703"],
        },
        Pin {
            position: "12",
            signals: &["p704"],
        },
        Pin {
            position: "13",
            signals: &["p705"],
        },
        Pin {
            position: "14",
            signals: &["p706"],
        },
        Pin {
            position: "15",
            signals: &["p707"],
        },
        Pin {
            position: "35",
            signals: &["p708"],
        },
        Pin {
            position: "34",
            signals: &["p709"],
        },
        Pin {
            position: "33",
            signals: &["p710"],
        },
        Pin {
            position: "133",
            signals: &["p800"],
        },
        Pin {
            position: "134",
            signals: &["p801"],
        },
        Pin {
            position: "135",
            signals: &["p802"],
        },
        Pin {
            position: "136",
            signals: &["p803"],
        },
        Pin {
            position: "137",
            signals: &["p804"],
        },
        Pin {
            position: "173",
            signals: &["p805"],
        },
        Pin {
            position: "172",
            signals: &["p806"],
        },
        Pin {
            position: "138",
            signals: &["p808"],
        },
        Pin {
            position: "139",
            signals: &["p809"],
        },
        Pin {
            position: "142",
            signals: &["p810"],
        },
        Pin {
            position: "143",
            signals: &["p811"],
        },
        Pin {
            position: "144",
            signals: &["p812"],
        },
        Pin {
            position: "47",
            signals: &["p814"],
        },
        Pin {
            position: "46",
            signals: &["p815"],
        },
        Pin {
            position: "57",
            signals: &["p900"],
        },
        Pin {
            position: "58",
            signals: &["p901"],
        },
        Pin {
            position: "73",
            signals: &["p905"],
        },
        Pin {
            position: "72",
            signals: &["p906"],
        },
        Pin {
            position: "71",
            signals: &["p907"],
        },
        Pin {
            position: "70",
            signals: &["p908"],
        },
        Pin {
            position: "69",
            signals: &["p909"],
        },
        Pin {
            position: "108",
            signals: &["pa00"],
        },
        Pin {
            position: "107",
            signals: &["pa01"],
        },
        Pin {
            position: "102",
            signals: &["pa08"],
        },
        Pin {
            position: "103",
            signals: &["pa09"],
        },
        Pin {
            position: "104",
            signals: &["pa10"],
        },
        Pin {
            position: "16",
            signals: &["pb00"],
        },
        Pin {
            position: "17",
            signals: &["pb01"],
        },
        Pin {
            position: "66",
            signals: &["res"],
        },
        Pin {
            position: "94",
            signals: &["vcc"],
        },
        Pin {
            position: "18",
            signals: &["vcc"],
        },
        Pin {
            position: "25",
            signals: &["vcc"],
        },
        Pin {
            position: "26",
            signals: &["vcc"],
        },
        Pin {
            position: "32",
            signals: &["vcc"],
        },
        Pin {
            position: "149",
            signals: &["vcc"],
        },
        Pin {
            position: "60",
            signals: &["vcc"],
        },
        Pin {
            position: "171",
            signals: &["vcc"],
        },
        Pin {
            position: "106",
            signals: &["vcc"],
        },
        Pin {
            position: "84",
            signals: &["vcc"],
        },
        Pin {
            position: "130",
            signals: &["vcc2"],
        },
        Pin {
            position: "140",
            signals: &["vcc2"],
        },
        Pin {
            position: "111",
            signals: &["vcc_dcdc"],
        },
        Pin {
            position: "112",
            signals: &["vcc_dcdc"],
        },
        Pin {
            position: "48",
            signals: &["vcc_usb"],
        },
        Pin {
            position: "19",
            signals: &["vcl"],
        },
        Pin {
            position: "148",
            signals: &["vcl"],
        },
        Pin {
            position: "61",
            signals: &["vcl"],
        },
        Pin {
            position: "109",
            signals: &["vcl"],
        },
        Pin {
            position: "113",
            signals: &["vlo"],
        },
        Pin {
            position: "114",
            signals: &["vlo"],
        },
        Pin {
            position: "154",
            signals: &["vrefh"],
        },
        Pin {
            position: "158",
            signals: &["vrefh0"],
        },
        Pin {
            position: "153",
            signals: &["vrefl"],
        },
        Pin {
            position: "157",
            signals: &["vrefl0"],
        },
        Pin {
            position: "95",
            signals: &["vss"],
        },
        Pin {
            position: "22",
            signals: &["vss"],
        },
        Pin {
            position: "28",
            signals: &["vss"],
        },
        Pin {
            position: "131",
            signals: &["vss"],
        },
        Pin {
            position: "31",
            signals: &["vss"],
        },
        Pin {
            position: "141",
            signals: &["vss"],
        },
        Pin {
            position: "150",
            signals: &["vss"],
        },
        Pin {
            position: "59",
            signals: &["vss"],
        },
        Pin {
            position: "170",
            signals: &["vss"],
        },
        Pin {
            position: "105",
            signals: &["vss"],
        },
        Pin {
            position: "83",
            signals: &["vss"],
        },
        Pin {
            position: "115",
            signals: &["vss_dcdc"],
        },
        Pin {
            position: "45",
            signals: &["vss_usb"],
        },
        Pin {
            position: "20",
            signals: &["xcin"],
        },
        Pin {
            position: "21",
            signals: &["xcout"],
        },
    ],
}];
