PROVIDE(NonMaskableInt = DefaultHandler);
PROVIDE(HardFault = DefaultHandler);
PROVIDE(MemoryManagement = DefaultHandler);
PROVIDE(BusFault = DefaultHandler);
PROVIDE(UsageFault = DefaultHandler);
PROVIDE(SecureFault = DefaultHandler);
PROVIDE(SVCall = DefaultHandler);
PROVIDE(DebugMonitor = DefaultHandler);
PROVIDE(PendSV = DefaultHandler);
PROVIDE(SysTick = DefaultHandler);
EXTERN(IEL0);
PROVIDE(IEL0 = DefaultHandler);
EXTERN(IEL1);
PROVIDE(IEL1 = DefaultHandler);
EXTERN(IEL2);
PROVIDE(IEL2 = DefaultHandler);
EXTERN(IEL3);
PROVIDE(IEL3 = DefaultHandler);
EXTERN(IEL4);
PROVIDE(IEL4 = DefaultHandler);
EXTERN(IEL5);
PROVIDE(IEL5 = DefaultHandler);
EXTERN(IEL6);
PROVIDE(IEL6 = DefaultHandler);
EXTERN(IEL7);
PROVIDE(IEL7 = DefaultHandler);
EXTERN(IEL8);
PROVIDE(IEL8 = DefaultHandler);
EXTERN(IEL9);
PROVIDE(IEL9 = DefaultHandler);
EXTERN(IEL10);
PROVIDE(IEL10 = DefaultHandler);
EXTERN(IEL11);
PROVIDE(IEL11 = DefaultHandler);
EXTERN(IEL12);
PROVIDE(IEL12 = DefaultHandler);
EXTERN(IEL13);
PROVIDE(IEL13 = DefaultHandler);
EXTERN(IEL14);
PROVIDE(IEL14 = DefaultHandler);
EXTERN(IEL15);
PROVIDE(IEL15 = DefaultHandler);
EXTERN(IEL16);
PROVIDE(IEL16 = DefaultHandler);
EXTERN(IEL17);
PROVIDE(IEL17 = DefaultHandler);
EXTERN(IEL18);
PROVIDE(IEL18 = DefaultHandler);
EXTERN(IEL19);
PROVIDE(IEL19 = DefaultHandler);
EXTERN(IEL20);
PROVIDE(IEL20 = DefaultHandler);
EXTERN(IEL21);
PROVIDE(IEL21 = DefaultHandler);
EXTERN(IEL22);
PROVIDE(IEL22 = DefaultHandler);
EXTERN(IEL23);
PROVIDE(IEL23 = DefaultHandler);
EXTERN(IEL24);
PROVIDE(IEL24 = DefaultHandler);
EXTERN(IEL25);
PROVIDE(IEL25 = DefaultHandler);
EXTERN(IEL26);
PROVIDE(IEL26 = DefaultHandler);
EXTERN(IEL27);
PROVIDE(IEL27 = DefaultHandler);
EXTERN(IEL28);
PROVIDE(IEL28 = DefaultHandler);
EXTERN(IEL29);
PROVIDE(IEL29 = DefaultHandler);
EXTERN(IEL30);
PROVIDE(IEL30 = DefaultHandler);
EXTERN(IEL31);
PROVIDE(IEL31 = DefaultHandler);
EXTERN(IEL32);
PROVIDE(IEL32 = DefaultHandler);
EXTERN(IEL33);
PROVIDE(IEL33 = DefaultHandler);
EXTERN(IEL34);
PROVIDE(IEL34 = DefaultHandler);
EXTERN(IEL35);
PROVIDE(IEL35 = DefaultHandler);
EXTERN(IEL36);
PROVIDE(IEL36 = DefaultHandler);
EXTERN(IEL37);
PROVIDE(IEL37 = DefaultHandler);
EXTERN(IEL38);
PROVIDE(IEL38 = DefaultHandler);
EXTERN(IEL39);
PROVIDE(IEL39 = DefaultHandler);
EXTERN(IEL40);
PROVIDE(IEL40 = DefaultHandler);
EXTERN(IEL41);
PROVIDE(IEL41 = DefaultHandler);
EXTERN(IEL42);
PROVIDE(IEL42 = DefaultHandler);
EXTERN(IEL43);
PROVIDE(IEL43 = DefaultHandler);
EXTERN(IEL44);
PROVIDE(IEL44 = DefaultHandler);
EXTERN(IEL45);
PROVIDE(IEL45 = DefaultHandler);
EXTERN(IEL46);
PROVIDE(IEL46 = DefaultHandler);
EXTERN(IEL47);
PROVIDE(IEL47 = DefaultHandler);
EXTERN(IEL48);
PROVIDE(IEL48 = DefaultHandler);
EXTERN(IEL49);
PROVIDE(IEL49 = DefaultHandler);
EXTERN(IEL50);
PROVIDE(IEL50 = DefaultHandler);
EXTERN(IEL51);
PROVIDE(IEL51 = DefaultHandler);
EXTERN(IEL52);
PROVIDE(IEL52 = DefaultHandler);
EXTERN(IEL53);
PROVIDE(IEL53 = DefaultHandler);
EXTERN(IEL54);
PROVIDE(IEL54 = DefaultHandler);
EXTERN(IEL55);
PROVIDE(IEL55 = DefaultHandler);
EXTERN(IEL56);
PROVIDE(IEL56 = DefaultHandler);
EXTERN(IEL57);
PROVIDE(IEL57 = DefaultHandler);
EXTERN(IEL58);
PROVIDE(IEL58 = DefaultHandler);
EXTERN(IEL59);
PROVIDE(IEL59 = DefaultHandler);
EXTERN(IEL60);
PROVIDE(IEL60 = DefaultHandler);
EXTERN(IEL61);
PROVIDE(IEL61 = DefaultHandler);
EXTERN(IEL62);
PROVIDE(IEL62 = DefaultHandler);
EXTERN(IEL63);
PROVIDE(IEL63 = DefaultHandler);
EXTERN(IEL64);
PROVIDE(IEL64 = DefaultHandler);
EXTERN(IEL65);
PROVIDE(IEL65 = DefaultHandler);
EXTERN(IEL66);
PROVIDE(IEL66 = DefaultHandler);
EXTERN(IEL67);
PROVIDE(IEL67 = DefaultHandler);
