// This file is autogenerated by ra-metapac-gen: do not edit by hand.
pub const NAME: &str = "R7FA4M3AE3CFB";
pub const FAMILY: &str = "R7FA4M3";
pub const CORE: &str = "Cortex-M33";
pub const MEMORY: &[MemoryRegion] = &[
    MemoryRegion {
        name: "RAM",
        kind: "RAM",
        address: 536870912,
        size: 131072,
    },
    MemoryRegion {
        name: "FLASH",
        kind: "ROM",
        address: 0,
        size: 786432,
    },
    MemoryRegion {
        name: "DATA_FLASH",
        kind: "ROM",
        address: 134217728,
        size: 8192,
    },
    MemoryRegion {
        name: "QSPI_FLASH",
        kind: "ROM",
        address: 1610612736,
        size: 67108864,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OFS0",
        kind: "ROM",
        address: 16818432,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OFS1",
        kind: "ROM",
        address: 16818560,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BANKSEL",
        kind: "ROM",
        address: 16818576,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BPS",
        kind: "ROM",
        address: 16818624,
        size: 8,
    },
    MemoryRegion {
        name: "OPTION_SETTING_PBPS",
        kind: "ROM",
        address: 16818656,
        size: 8,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OFS1_SEC",
        kind: "ROM",
        address: 16818688,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BANKSEL_SEC",
        kind: "ROM",
        address: 16818704,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BPS_SEC",
        kind: "ROM",
        address: 16818752,
        size: 8,
    },
    MemoryRegion {
        name: "OPTION_SETTING_PBPS_SEC",
        kind: "ROM",
        address: 16818784,
        size: 8,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OFS1_SEL",
        kind: "ROM",
        address: 16818816,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BANKSEL_SEL",
        kind: "ROM",
        address: 16818832,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BPS_SEL",
        kind: "ROM",
        address: 16818880,
        size: 8,
    },
];
pub const PERIPHERALS: &[Peripheral] = &[
    Peripheral {
        name: "GPT0",
        address: 1075220480,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT1",
        address: 1075220736,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT2",
        address: 1075220992,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT3",
        address: 1075221248,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT4",
        address: 1075221504,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT5",
        address: 1075221760,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT6",
        address: 1075222016,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT7",
        address: 1075222272,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "ICU",
        address: 1073766400,
        kind: "icu",
        version: "v3",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "MSTP",
        address: 1074282496,
        kind: "mstp",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT0",
        address: 1074266112,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT1",
        address: 1074266144,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT2",
        address: 1074266176,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT3",
        address: 1074266208,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT4",
        address: 1074266240,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT5",
        address: 1074266272,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT6",
        address: 1074266304,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT7",
        address: 1074266336,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT8",
        address: 1074266368,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "RTC",
        address: 1074278400,
        kind: "rtc",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "SYSTEM",
        address: 1073864704,
        kind: "system",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
];
pub const PACKAGES: &[Package] = &[Package {
    name: "144LQFP",
    pins: &[
        Pin {
            position: "1",
            signals: &["p400"],
        },
        Pin {
            position: "2",
            signals: &["p401"],
        },
        Pin {
            position: "3",
            signals: &["p402"],
        },
        Pin {
            position: "4",
            signals: &["p403"],
        },
        Pin {
            position: "5",
            signals: &["p404"],
        },
        Pin {
            position: "6",
            signals: &["p405"],
        },
        Pin {
            position: "7",
            signals: &["p406"],
        },
        Pin {
            position: "8",
            signals: &["p700"],
        },
        Pin {
            position: "9",
            signals: &["p701"],
        },
        Pin {
            position: "10",
            signals: &["p702"],
        },
        Pin {
            position: "11",
            signals: &["p703"],
        },
        Pin {
            position: "12",
            signals: &["p704"],
        },
        Pin {
            position: "13",
            signals: &["p705"],
        },
        Pin {
            position: "14",
            signals: &["vbatt"],
        },
        Pin {
            position: "15",
            signals: &["vcl0"],
        },
        Pin {
            position: "16",
            signals: &["xcin"],
        },
        Pin {
            position: "17",
            signals: &["xcout"],
        },
        Pin {
            position: "18",
            signals: &["vss"],
        },
        Pin {
            position: "19",
            signals: &["p213"],
        },
        Pin {
            position: "20",
            signals: &["p212"],
        },
        Pin {
            position: "21",
            signals: &["vcc"],
        },
        Pin {
            position: "22",
            signals: &["p713"],
        },
        Pin {
            position: "23",
            signals: &["p712"],
        },
        Pin {
            position: "24",
            signals: &["p711"],
        },
        Pin {
            position: "25",
            signals: &["p710"],
        },
        Pin {
            position: "26",
            signals: &["p709"],
        },
        Pin {
            position: "27",
            signals: &["p708"],
        },
        Pin {
            position: "28",
            signals: &["p415"],
        },
        Pin {
            position: "29",
            signals: &["p414"],
        },
        Pin {
            position: "30",
            signals: &["p413"],
        },
        Pin {
            position: "31",
            signals: &["p412"],
        },
        Pin {
            position: "32",
            signals: &["p411"],
        },
        Pin {
            position: "33",
            signals: &["p410"],
        },
        Pin {
            position: "34",
            signals: &["p409"],
        },
        Pin {
            position: "35",
            signals: &["p408"],
        },
        Pin {
            position: "36",
            signals: &["p407"],
        },
        Pin {
            position: "37",
            signals: &["vssusb"],
        },
        Pin {
            position: "38",
            signals: &["usbdm"],
        },
        Pin {
            position: "39",
            signals: &["usbdp"],
        },
        Pin {
            position: "40",
            signals: &["vccusb"],
        },
        Pin {
            position: "41",
            signals: &["p207"],
        },
        Pin {
            position: "42",
            signals: &["p206"],
        },
        Pin {
            position: "43",
            signals: &["p205"],
        },
        Pin {
            position: "44",
            signals: &["p204"],
        },
        Pin {
            position: "45",
            signals: &["p203"],
        },
        Pin {
            position: "46",
            signals: &["p202"],
        },
        Pin {
            position: "47",
            signals: &["p313"],
        },
        Pin {
            position: "48",
            signals: &["vss"],
        },
        Pin {
            position: "49",
            signals: &["vcc"],
        },
        Pin {
            position: "50",
            signals: &["p214"],
        },
        Pin {
            position: "51",
            signals: &["p211"],
        },
        Pin {
            position: "52",
            signals: &["p210"],
        },
        Pin {
            position: "53",
            signals: &["p209"],
        },
        Pin {
            position: "54",
            signals: &["p208"],
        },
        Pin {
            position: "55",
            signals: &["res"],
        },
        Pin {
            position: "56",
            signals: &["p201"],
        },
        Pin {
            position: "57",
            signals: &["p200"],
        },
        Pin {
            position: "58",
            signals: &["p312"],
        },
        Pin {
            position: "59",
            signals: &["p311"],
        },
        Pin {
            position: "60",
            signals: &["p310"],
        },
        Pin {
            position: "61",
            signals: &["p309"],
        },
        Pin {
            position: "62",
            signals: &["p308"],
        },
        Pin {
            position: "63",
            signals: &["p307"],
        },
        Pin {
            position: "64",
            signals: &["p306"],
        },
        Pin {
            position: "65",
            signals: &["p305"],
        },
        Pin {
            position: "66",
            signals: &["p304"],
        },
        Pin {
            position: "67",
            signals: &["vss"],
        },
        Pin {
            position: "68",
            signals: &["vcc"],
        },
        Pin {
            position: "69",
            signals: &["p303"],
        },
        Pin {
            position: "70",
            signals: &["p302"],
        },
        Pin {
            position: "71",
            signals: &["p301"],
        },
        Pin {
            position: "72",
            signals: &["p300"],
        },
        Pin {
            position: "73",
            signals: &["p108"],
        },
        Pin {
            position: "74",
            signals: &["p109"],
        },
        Pin {
            position: "75",
            signals: &["p110"],
        },
        Pin {
            position: "76",
            signals: &["p111"],
        },
        Pin {
            position: "77",
            signals: &["p112"],
        },
        Pin {
            position: "78",
            signals: &["p113"],
        },
        Pin {
            position: "79",
            signals: &["p114"],
        },
        Pin {
            position: "80",
            signals: &["p115"],
        },
        Pin {
            position: "81",
            signals: &["vcc"],
        },
        Pin {
            position: "82",
            signals: &["vss"],
        },
        Pin {
            position: "83",
            signals: &["p608"],
        },
        Pin {
            position: "84",
            signals: &["p609"],
        },
        Pin {
            position: "85",
            signals: &["p610"],
        },
        Pin {
            position: "86",
            signals: &["p611"],
        },
        Pin {
            position: "87",
            signals: &["p612"],
        },
        Pin {
            position: "88",
            signals: &["p613"],
        },
        Pin {
            position: "89",
            signals: &["p614"],
        },
        Pin {
            position: "90",
            signals: &["vcc"],
        },
        Pin {
            position: "91",
            signals: &["vss"],
        },
        Pin {
            position: "92",
            signals: &["vcl"],
        },
        Pin {
            position: "93",
            signals: &["p605"],
        },
        Pin {
            position: "94",
            signals: &["p604"],
        },
        Pin {
            position: "95",
            signals: &["p603"],
        },
        Pin {
            position: "96",
            signals: &["p602"],
        },
        Pin {
            position: "97",
            signals: &["p601"],
        },
        Pin {
            position: "98",
            signals: &["p600"],
        },
        Pin {
            position: "99",
            signals: &["vcc"],
        },
        Pin {
            position: "100",
            signals: &["vss"],
        },
        Pin {
            position: "101",
            signals: &["p107"],
        },
        Pin {
            position: "102",
            signals: &["p106"],
        },
        Pin {
            position: "103",
            signals: &["p105"],
        },
        Pin {
            position: "104",
            signals: &["p104"],
        },
        Pin {
            position: "105",
            signals: &["p103"],
        },
        Pin {
            position: "106",
            signals: &["p102"],
        },
        Pin {
            position: "107",
            signals: &["p101"],
        },
        Pin {
            position: "108",
            signals: &["p100"],
        },
        Pin {
            position: "109",
            signals: &["p800"],
        },
        Pin {
            position: "110",
            signals: &["p801"],
        },
        Pin {
            position: "111",
            signals: &["vcc"],
        },
        Pin {
            position: "112",
            signals: &["vss"],
        },
        Pin {
            position: "113",
            signals: &["p500"],
        },
        Pin {
            position: "114",
            signals: &["p501"],
        },
        Pin {
            position: "115",
            signals: &["p502"],
        },
        Pin {
            position: "116",
            signals: &["p503"],
        },
        Pin {
            position: "117",
            signals: &["p504"],
        },
        Pin {
            position: "118",
            signals: &["p505"],
        },
        Pin {
            position: "119",
            signals: &["p506"],
        },
        Pin {
            position: "120",
            signals: &["p507"],
        },
        Pin {
            position: "121",
            signals: &["vcc"],
        },
        Pin {
            position: "122",
            signals: &["vss"],
        },
        Pin {
            position: "123",
            signals: &["p015"],
        },
        Pin {
            position: "124",
            signals: &["p014"],
        },
        Pin {
            position: "125",
            signals: &["vrefl"],
        },
        Pin {
            position: "126",
            signals: &["vrefh"],
        },
        Pin {
            position: "127",
            signals: &["avcc0"],
        },
        Pin {
            position: "128",
            signals: &["avss0"],
        },
        Pin {
            position: "129",
            signals: &["vrefl0"],
        },
        Pin {
            position: "130",
            signals: &["vrefh0"],
        },
        Pin {
            position: "131",
            signals: &["p009"],
        },
        Pin {
            position: "132",
            signals: &["p008"],
        },
        Pin {
            position: "133",
            signals: &["p007"],
        },
        Pin {
            position: "134",
            signals: &["p006"],
        },
        Pin {
            position: "135",
            signals: &["p005"],
        },
        Pin {
            position: "136",
            signals: &["p004"],
        },
        Pin {
            position: "137",
            signals: &["p003"],
        },
        Pin {
            position: "138",
            signals: &["p002"],
        },
        Pin {
            position: "139",
            signals: &["p001"],
        },
        Pin {
            position: "140",
            signals: &["p000"],
        },
        Pin {
            position: "141",
            signals: &["vss"],
        },
        Pin {
            position: "142",
            signals: &["vcc"],
        },
        Pin {
            position: "143",
            signals: &["p512"],
        },
        Pin {
            position: "144",
            signals: &["p511"],
        },
    ],
}];
