// This file is autogenerated by ra-metapac-gen: do not edit by hand.
const FAMILY: &str = "ra6m5";
const CORE: &str = "Cortex-M33";
const INTERRUPT_COUNT: usize = 96;
const MEMORY: &[MemoryRegion] = &[
    MemoryRegion {
        name: "RAM",
        kind: "RAM",
        address: 536870912,
        size: 524288,
    },
    MemoryRegion {
        name: "FLASH",
        kind: "ROM",
        address: 0,
        size: 2097152,
    },
    MemoryRegion {
        name: "DATA_FLASH",
        kind: "ROM",
        address: 134217728,
        size: 8192,
    },
    MemoryRegion {
        name: "QSPI_FLASH",
        kind: "ROM",
        address: 1610612736,
        size: 67108864,
    },
    MemoryRegion {
        name: "OSPI0_CS0",
        kind: "RAM",
        address: 1744830464,
        size: 134217728,
    },
    MemoryRegion {
        name: "OSPI0_CS1",
        kind: "ROM",
        address: 1879048192,
        size: 268435456,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OFS0",
        kind: "ROM",
        address: 16818432,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_DUALSEL",
        kind: "ROM",
        address: 16818448,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OFS1",
        kind: "ROM",
        address: 16818560,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BANKSEL",
        kind: "ROM",
        address: 16818576,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BPS",
        kind: "ROM",
        address: 16818624,
        size: 16,
    },
    MemoryRegion {
        name: "OPTION_SETTING_PBPS",
        kind: "ROM",
        address: 16818656,
        size: 16,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OFS1_SEC",
        kind: "ROM",
        address: 16818688,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BANKSEL_SEC",
        kind: "ROM",
        address: 16818704,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BPS_SEC",
        kind: "ROM",
        address: 16818752,
        size: 16,
    },
    MemoryRegion {
        name: "OPTION_SETTING_PBPS_SEC",
        kind: "ROM",
        address: 16818784,
        size: 16,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OFS1_SEL",
        kind: "ROM",
        address: 16818816,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BANKSEL_SEL",
        kind: "ROM",
        address: 16818832,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BPS_SEL",
        kind: "ROM",
        address: 16818880,
        size: 16,
    },
];
const PERIPHERALS: &[Peripheral] = &[
    Peripheral {
        name: "AGT0",
        address: 1074692096,
        kind: "agt",
        version: "16bits",
        block: "AGT",
        mstp: Some(Mstp {
            register: "MSTPCRD",
            bit: 3,
        }),
        interrupts: &["COMPARE_A", "COMPARE_B", "INT"],
    },
    Peripheral {
        name: "AGT1",
        address: 1074692352,
        kind: "agt",
        version: "16bits",
        block: "AGT",
        mstp: Some(Mstp {
            register: "MSTPCRD",
            bit: 2,
        }),
        interrupts: &["COMPARE_A", "COMPARE_B", "INT"],
    },
    Peripheral {
        name: "AGT2",
        address: 1074692608,
        kind: "agt",
        version: "16bits",
        block: "AGT",
        mstp: Some(Mstp {
            register: "MSTPCRD",
            bit: 1,
        }),
        interrupts: &["COMPARE_A", "COMPARE_B", "INT"],
    },
    Peripheral {
        name: "AGT3",
        address: 1074692864,
        kind: "agt",
        version: "16bits",
        block: "AGT",
        mstp: Some(Mstp {
            register: "MSTPCRD",
            bit: 0,
        }),
        interrupts: &["COMPARE_A", "COMPARE_B", "INT"],
    },
    Peripheral {
        name: "AGT4",
        address: 1074693120,
        kind: "agt",
        version: "16bits",
        block: "AGT",
        mstp: Some(Mstp {
            register: "MSTPCRD",
            bit: 4294967295,
        }),
        interrupts: &["COMPARE_A", "COMPARE_B", "INT"],
    },
    Peripheral {
        name: "AGT5",
        address: 1074693376,
        kind: "agt",
        version: "16bits",
        block: "AGT",
        mstp: Some(Mstp {
            register: "MSTPCRD",
            bit: 4294967294,
        }),
        interrupts: &["COMPARE_A", "COMPARE_B", "INT"],
    },
    Peripheral {
        name: "GPT0",
        address: 1075220480,
        kind: "gpt",
        version: "v1",
        block: "GPT",
        mstp: Some(Mstp {
            register: "MSTPCRE",
            bit: 31,
        }),
        interrupts: &["CAPTURE_COMPARE_A", "CAPTURE_COMPARE_B", "COMPARE_C", "COMPARE_D", "COMPARE_E", "COMPARE_F", "COUNTER_OVERFLOW", "COUNTER_UNDERFLOW", "PC"],
    },
    Peripheral {
        name: "GPT1",
        address: 1075220736,
        kind: "gpt",
        version: "v1",
        block: "GPT",
        mstp: Some(Mstp {
            register: "MSTPCRE",
            bit: 30,
        }),
        interrupts: &["CAPTURE_COMPARE_A", "CAPTURE_COMPARE_B", "COMPARE_C", "COMPARE_D", "COMPARE_E", "COMPARE_F", "COUNTER_OVERFLOW", "COUNTER_UNDERFLOW", "PC"],
    },
    Peripheral {
        name: "GPT2",
        address: 1075220992,
        kind: "gpt",
        version: "v1",
        block: "GPT",
        mstp: Some(Mstp {
            register: "MSTPCRE",
            bit: 29,
        }),
        interrupts: &["CAPTURE_COMPARE_A", "CAPTURE_COMPARE_B", "COMPARE_C", "COMPARE_D", "COMPARE_E", "COMPARE_F", "COUNTER_OVERFLOW", "COUNTER_UNDERFLOW"],
    },
    Peripheral {
        name: "GPT3",
        address: 1075221248,
        kind: "gpt",
        version: "v1",
        block: "GPT",
        mstp: Some(Mstp {
            register: "MSTPCRE",
            bit: 28,
        }),
        interrupts: &["CAPTURE_COMPARE_A", "CAPTURE_COMPARE_B", "COMPARE_C", "COMPARE_D", "COMPARE_E", "COMPARE_F", "COUNTER_OVERFLOW", "COUNTER_UNDERFLOW"],
    },
    Peripheral {
        name: "GPT4",
        address: 1075221504,
        kind: "gpt",
        version: "v1",
        block: "GPT",
        mstp: Some(Mstp {
            register: "MSTPCRE",
            bit: 27,
        }),
        interrupts: &["CAPTURE_COMPARE_A", "CAPTURE_COMPARE_B", "COMPARE_C", "COMPARE_D", "COMPARE_E", "COMPARE_F", "COUNTER_OVERFLOW", "COUNTER_UNDERFLOW", "PC"],
    },
    Peripheral {
        name: "GPT5",
        address: 1075221760,
        kind: "gpt",
        version: "v1",
        block: "GPT",
        mstp: Some(Mstp {
            register: "MSTPCRE",
            bit: 26,
        }),
        interrupts: &["CAPTURE_COMPARE_A", "CAPTURE_COMPARE_B", "COMPARE_C", "COMPARE_D", "COMPARE_E", "COMPARE_F", "COUNTER_OVERFLOW", "COUNTER_UNDERFLOW", "PC"],
    },
    Peripheral {
        name: "GPT6",
        address: 1075222016,
        kind: "gpt",
        version: "v1",
        block: "GPT",
        mstp: Some(Mstp {
            register: "MSTPCRE",
            bit: 25,
        }),
        interrupts: &["CAPTURE_COMPARE_A", "CAPTURE_COMPARE_B", "COMPARE_C", "COMPARE_D", "COMPARE_E", "COMPARE_F", "COUNTER_OVERFLOW", "COUNTER_UNDERFLOW", "PC"],
    },
    Peripheral {
        name: "GPT7",
        address: 1075222272,
        kind: "gpt",
        version: "v1",
        block: "GPT",
        mstp: Some(Mstp {
            register: "MSTPCRE",
            bit: 24,
        }),
        interrupts: &["CAPTURE_COMPARE_A", "CAPTURE_COMPARE_B", "COMPARE_C", "COMPARE_D", "COMPARE_E", "COMPARE_F", "COUNTER_OVERFLOW", "COUNTER_UNDERFLOW"],
    },
    Peripheral {
        name: "GPT8",
        address: 1075222528,
        kind: "gpt",
        version: "v1",
        block: "GPT",
        mstp: Some(Mstp {
            register: "MSTPCRE",
            bit: 23,
        }),
        interrupts: &["CAPTURE_COMPARE_A", "CAPTURE_COMPARE_B", "COMPARE_C", "COMPARE_D", "COMPARE_E", "COMPARE_F", "COUNTER_OVERFLOW", "COUNTER_UNDERFLOW"],
    },
    Peripheral {
        name: "GPT9",
        address: 1075222784,
        kind: "gpt",
        version: "v1",
        block: "GPT",
        mstp: Some(Mstp {
            register: "MSTPCRE",
            bit: 22,
        }),
        interrupts: &["CAPTURE_COMPARE_A", "CAPTURE_COMPARE_B", "COMPARE_C", "COMPARE_D", "COMPARE_E", "COMPARE_F", "COUNTER_OVERFLOW", "COUNTER_UNDERFLOW"],
    },
    Peripheral {
        name: "ICU",
        address: 1073766400,
        kind: "icu",
        version: "ra6m5",
        block: "ICU",
        mstp: None,
        interrupts: &["SNOOZE_CANCEL"],
    },
    Peripheral {
        name: "MSTP",
        address: 1074282496,
        kind: "mstp",
        version: "v2",
        block: "MSTP",
        mstp: None,
        interrupts: &[],
    },
    Peripheral {
        name: "PFS",
        address: 1074268160,
        kind: "pfs",
        version: "v1",
        block: "PFS",
        mstp: None,
        interrupts: &[],
    },
    Peripheral {
        name: "PORT0",
        address: 1074266112,
        kind: "port",
        version: "v1",
        block: "PORT_extended",
        mstp: None,
        interrupts: &[],
    },
    Peripheral {
        name: "PORT1",
        address: 1074266144,
        kind: "port",
        version: "v1",
        block: "PORT_extended",
        mstp: None,
        interrupts: &[],
    },
    Peripheral {
        name: "PORT2",
        address: 1074266176,
        kind: "port",
        version: "v1",
        block: "PORT_extended",
        mstp: None,
        interrupts: &[],
    },
    Peripheral {
        name: "PORT3",
        address: 1074266208,
        kind: "port",
        version: "v1",
        block: "PORT_extended",
        mstp: None,
        interrupts: &[],
    },
    Peripheral {
        name: "PORT4",
        address: 1074266240,
        kind: "port",
        version: "v1",
        block: "PORT_extended",
        mstp: None,
        interrupts: &[],
    },
    Peripheral {
        name: "PORT5",
        address: 1074266272,
        kind: "port",
        version: "v1",
        block: "PORT_extended",
        mstp: None,
        interrupts: &[],
    },
    Peripheral {
        name: "PORT6",
        address: 1074266304,
        kind: "port",
        version: "v1",
        block: "PORT_extended",
        mstp: None,
        interrupts: &[],
    },
    Peripheral {
        name: "PORT7",
        address: 1074266336,
        kind: "port",
        version: "v1",
        block: "PORT_extended",
        mstp: None,
        interrupts: &[],
    },
    Peripheral {
        name: "PORT8",
        address: 1074266368,
        kind: "port",
        version: "v1",
        block: "PORT_extended",
        mstp: None,
        interrupts: &[],
    },
    Peripheral {
        name: "PORT9",
        address: 1074266400,
        kind: "port",
        version: "v1",
        block: "PORT_extended",
        mstp: None,
        interrupts: &[],
    },
    Peripheral {
        name: "SYSC",
        address: 1073864704,
        kind: "sysc",
        version: "v4",
        block: "SYSC",
        mstp: None,
        interrupts: &[],
    },
];
const EVENTS: &[Event] = &[
    Event {
        name: "ADC0_COMPARE_MATCH",
        id: 356,
        irq_slots: &[],
        peripheral: Some("ADC"),
        channel: Some(0),
        signal: Some("COMPARE_MATCH"),
    },
    Event {
        name: "ADC0_COMPARE_MISMATCH",
        id: 357,
        irq_slots: &[],
        peripheral: Some("ADC"),
        channel: Some(0),
        signal: Some("COMPARE_MISMATCH"),
    },
    Event {
        name: "ADC0_SCAN_END",
        id: 352,
        irq_slots: &[],
        peripheral: Some("ADC"),
        channel: Some(0),
        signal: Some("SCAN_END"),
    },
    Event {
        name: "ADC0_SCAN_END_B",
        id: 353,
        irq_slots: &[],
        peripheral: Some("ADC"),
        channel: Some(0),
        signal: Some("SCAN_END_B"),
    },
    Event {
        name: "ADC0_WINDOW_A",
        id: 354,
        irq_slots: &[],
        peripheral: Some("ADC"),
        channel: Some(0),
        signal: Some("WINDOW_A"),
    },
    Event {
        name: "ADC0_WINDOW_B",
        id: 355,
        irq_slots: &[],
        peripheral: Some("ADC"),
        channel: Some(0),
        signal: Some("WINDOW_B"),
    },
    Event {
        name: "ADC1_COMPARE_MATCH",
        id: 362,
        irq_slots: &[],
        peripheral: Some("ADC"),
        channel: Some(1),
        signal: Some("COMPARE_MATCH"),
    },
    Event {
        name: "ADC1_COMPARE_MISMATCH",
        id: 363,
        irq_slots: &[],
        peripheral: Some("ADC"),
        channel: Some(1),
        signal: Some("COMPARE_MISMATCH"),
    },
    Event {
        name: "ADC1_SCAN_END",
        id: 358,
        irq_slots: &[],
        peripheral: Some("ADC"),
        channel: Some(1),
        signal: Some("SCAN_END"),
    },
    Event {
        name: "ADC1_SCAN_END_B",
        id: 359,
        irq_slots: &[],
        peripheral: Some("ADC"),
        channel: Some(1),
        signal: Some("SCAN_END_B"),
    },
    Event {
        name: "ADC1_WINDOW_A",
        id: 360,
        irq_slots: &[],
        peripheral: Some("ADC"),
        channel: Some(1),
        signal: Some("WINDOW_A"),
    },
    Event {
        name: "ADC1_WINDOW_B",
        id: 361,
        irq_slots: &[],
        peripheral: Some("ADC"),
        channel: Some(1),
        signal: Some("WINDOW_B"),
    },
    Event {
        name: "AGT0_COMPARE_A",
        id: 65,
        irq_slots: &[],
        peripheral: Some("AGT"),
        channel: Some(0),
        signal: Some("COMPARE_A"),
    },
    Event {
        name: "AGT0_COMPARE_B",
        id: 66,
        irq_slots: &[],
        peripheral: Some("AGT"),
        channel: Some(0),
        signal: Some("COMPARE_B"),
    },
    Event {
        name: "AGT0_INT",
        id: 64,
        irq_slots: &[],
        peripheral: Some("AGT"),
        channel: Some(0),
        signal: Some("INT"),
    },
    Event {
        name: "AGT1_COMPARE_A",
        id: 68,
        irq_slots: &[],
        peripheral: Some("AGT"),
        channel: Some(1),
        signal: Some("COMPARE_A"),
    },
    Event {
        name: "AGT1_COMPARE_B",
        id: 69,
        irq_slots: &[],
        peripheral: Some("AGT"),
        channel: Some(1),
        signal: Some("COMPARE_B"),
    },
    Event {
        name: "AGT1_INT",
        id: 67,
        irq_slots: &[],
        peripheral: Some("AGT"),
        channel: Some(1),
        signal: Some("INT"),
    },
    Event {
        name: "AGT2_COMPARE_A",
        id: 71,
        irq_slots: &[],
        peripheral: Some("AGT"),
        channel: Some(2),
        signal: Some("COMPARE_A"),
    },
    Event {
        name: "AGT2_COMPARE_B",
        id: 72,
        irq_slots: &[],
        peripheral: Some("AGT"),
        channel: Some(2),
        signal: Some("COMPARE_B"),
    },
    Event {
        name: "AGT2_INT",
        id: 70,
        irq_slots: &[],
        peripheral: Some("AGT"),
        channel: Some(2),
        signal: Some("INT"),
    },
    Event {
        name: "AGT3_COMPARE_A",
        id: 74,
        irq_slots: &[],
        peripheral: Some("AGT"),
        channel: Some(3),
        signal: Some("COMPARE_A"),
    },
    Event {
        name: "AGT3_COMPARE_B",
        id: 75,
        irq_slots: &[],
        peripheral: Some("AGT"),
        channel: Some(3),
        signal: Some("COMPARE_B"),
    },
    Event {
        name: "AGT3_INT",
        id: 73,
        irq_slots: &[],
        peripheral: Some("AGT"),
        channel: Some(3),
        signal: Some("INT"),
    },
    Event {
        name: "AGT4_COMPARE_A",
        id: 77,
        irq_slots: &[],
        peripheral: Some("AGT"),
        channel: Some(4),
        signal: Some("COMPARE_A"),
    },
    Event {
        name: "AGT4_COMPARE_B",
        id: 78,
        irq_slots: &[],
        peripheral: Some("AGT"),
        channel: Some(4),
        signal: Some("COMPARE_B"),
    },
    Event {
        name: "AGT4_INT",
        id: 76,
        irq_slots: &[],
        peripheral: Some("AGT"),
        channel: Some(4),
        signal: Some("INT"),
    },
    Event {
        name: "AGT5_COMPARE_A",
        id: 80,
        irq_slots: &[],
        peripheral: Some("AGT"),
        channel: Some(5),
        signal: Some("COMPARE_A"),
    },
    Event {
        name: "AGT5_COMPARE_B",
        id: 81,
        irq_slots: &[],
        peripheral: Some("AGT"),
        channel: Some(5),
        signal: Some("COMPARE_B"),
    },
    Event {
        name: "AGT5_INT",
        id: 79,
        irq_slots: &[],
        peripheral: Some("AGT"),
        channel: Some(5),
        signal: Some("INT"),
    },
    Event {
        name: "CAC_FREQUENCY_ERROR",
        id: 158,
        irq_slots: &[],
        peripheral: Some("CAC"),
        channel: None,
        signal: Some("FREQUENCY_ERROR"),
    },
    Event {
        name: "CAC_MEASUREMENT_END",
        id: 159,
        irq_slots: &[],
        peripheral: Some("CAC"),
        channel: None,
        signal: Some("MEASUREMENT_END"),
    },
    Event {
        name: "CAC_OVERFLOW",
        id: 160,
        irq_slots: &[],
        peripheral: Some("CAC"),
        channel: None,
        signal: Some("OVERFLOW"),
    },
    Event {
        name: "CAN0_CF_DMAREQ",
        id: 102,
        irq_slots: &[],
        peripheral: Some("CAN"),
        channel: Some(0),
        signal: Some("CF_DMAREQ"),
    },
    Event {
        name: "CAN0_CHERR",
        id: 100,
        irq_slots: &[],
        peripheral: Some("CAN"),
        channel: Some(0),
        signal: Some("CHERR"),
    },
    Event {
        name: "CAN0_COMFRX",
        id: 101,
        irq_slots: &[],
        peripheral: Some("CAN"),
        channel: Some(0),
        signal: Some("COMFRX"),
    },
    Event {
        name: "CAN0_MRAM_ERI",
        id: 464,
        irq_slots: &[],
        peripheral: Some("CAN"),
        channel: Some(0),
        signal: Some("MRAM_ERI"),
    },
    Event {
        name: "CAN0_TX",
        id: 99,
        irq_slots: &[],
        peripheral: Some("CAN"),
        channel: Some(0),
        signal: Some("TX"),
    },
    Event {
        name: "CAN1_CF_DMAREQ",
        id: 106,
        irq_slots: &[],
        peripheral: Some("CAN"),
        channel: Some(1),
        signal: Some("CF_DMAREQ"),
    },
    Event {
        name: "CAN1_CHERR",
        id: 104,
        irq_slots: &[],
        peripheral: Some("CAN"),
        channel: Some(1),
        signal: Some("CHERR"),
    },
    Event {
        name: "CAN1_COMFRX",
        id: 105,
        irq_slots: &[],
        peripheral: Some("CAN"),
        channel: Some(1),
        signal: Some("COMFRX"),
    },
    Event {
        name: "CAN1_TX",
        id: 103,
        irq_slots: &[],
        peripheral: Some("CAN"),
        channel: Some(1),
        signal: Some("TX"),
    },
    Event {
        name: "CAN_AFLRAM0_ERI",
        id: 462,
        irq_slots: &[],
        peripheral: Some("CAN"),
        channel: None,
        signal: Some("AFLRAM0_ERI"),
    },
    Event {
        name: "CAN_AFLRAM1_ERI",
        id: 463,
        irq_slots: &[],
        peripheral: Some("CAN"),
        channel: None,
        signal: Some("AFLRAM1_ERI"),
    },
    Event {
        name: "CAN_DMAREQ0",
        id: 91,
        irq_slots: &[],
        peripheral: Some("CAN"),
        channel: Some(0),
        signal: Some("DMAREQ"),
    },
    Event {
        name: "CAN_DMAREQ1",
        id: 92,
        irq_slots: &[],
        peripheral: Some("CAN"),
        channel: Some(1),
        signal: Some("DMAREQ"),
    },
    Event {
        name: "CAN_DMAREQ2",
        id: 93,
        irq_slots: &[],
        peripheral: Some("CAN"),
        channel: Some(2),
        signal: Some("DMAREQ"),
    },
    Event {
        name: "CAN_DMAREQ3",
        id: 94,
        irq_slots: &[],
        peripheral: Some("CAN"),
        channel: Some(3),
        signal: Some("DMAREQ"),
    },
    Event {
        name: "CAN_DMAREQ4",
        id: 95,
        irq_slots: &[],
        peripheral: Some("CAN"),
        channel: Some(4),
        signal: Some("DMAREQ"),
    },
    Event {
        name: "CAN_DMAREQ5",
        id: 96,
        irq_slots: &[],
        peripheral: Some("CAN"),
        channel: Some(5),
        signal: Some("DMAREQ"),
    },
    Event {
        name: "CAN_DMAREQ6",
        id: 97,
        irq_slots: &[],
        peripheral: Some("CAN"),
        channel: Some(6),
        signal: Some("DMAREQ"),
    },
    Event {
        name: "CAN_DMAREQ7",
        id: 98,
        irq_slots: &[],
        peripheral: Some("CAN"),
        channel: Some(7),
        signal: Some("DMAREQ"),
    },
    Event {
        name: "CAN_GLERR",
        id: 90,
        irq_slots: &[],
        peripheral: Some("CAN"),
        channel: None,
        signal: Some("GLERR"),
    },
    Event {
        name: "CAN_RXF",
        id: 89,
        irq_slots: &[],
        peripheral: Some("CAN"),
        channel: None,
        signal: Some("RXF"),
    },
    Event {
        name: "CEC_INTCE",
        id: 172,
        irq_slots: &[],
        peripheral: Some("CEC"),
        channel: None,
        signal: Some("INTCE"),
    },
    Event {
        name: "CEC_INTDA",
        id: 171,
        irq_slots: &[],
        peripheral: Some("CEC"),
        channel: None,
        signal: Some("INTDA"),
    },
    Event {
        name: "CEC_INTERR",
        id: 173,
        irq_slots: &[],
        peripheral: Some("CEC"),
        channel: None,
        signal: Some("INTERR"),
    },
    Event {
        name: "CGC_MOSC_STOP",
        id: 59,
        irq_slots: &[],
        peripheral: Some("CGC"),
        channel: None,
        signal: Some("MOSC_STOP"),
    },
    Event {
        name: "CTSU_END",
        id: 156,
        irq_slots: &[],
        peripheral: Some("CTSU"),
        channel: None,
        signal: Some("END"),
    },
    Event {
        name: "CTSU_READ",
        id: 155,
        irq_slots: &[],
        peripheral: Some("CTSU"),
        channel: None,
        signal: Some("READ"),
    },
    Event {
        name: "CTSU_WRITE",
        id: 154,
        irq_slots: &[],
        peripheral: Some("CTSU"),
        channel: None,
        signal: Some("WRITE"),
    },
    Event {
        name: "DMAC0_INT",
        id: 32,
        irq_slots: &[],
        peripheral: Some("DMAC"),
        channel: Some(0),
        signal: Some("INT"),
    },
    Event {
        name: "DMAC1_INT",
        id: 33,
        irq_slots: &[],
        peripheral: Some("DMAC"),
        channel: Some(1),
        signal: Some("INT"),
    },
    Event {
        name: "DMAC2_INT",
        id: 34,
        irq_slots: &[],
        peripheral: Some("DMAC"),
        channel: Some(2),
        signal: Some("INT"),
    },
    Event {
        name: "DMAC3_INT",
        id: 35,
        irq_slots: &[],
        peripheral: Some("DMAC"),
        channel: Some(3),
        signal: Some("INT"),
    },
    Event {
        name: "DMAC4_INT",
        id: 36,
        irq_slots: &[],
        peripheral: Some("DMAC"),
        channel: Some(4),
        signal: Some("INT"),
    },
    Event {
        name: "DMAC5_INT",
        id: 37,
        irq_slots: &[],
        peripheral: Some("DMAC"),
        channel: Some(5),
        signal: Some("INT"),
    },
    Event {
        name: "DMAC6_INT",
        id: 38,
        irq_slots: &[],
        peripheral: Some("DMAC"),
        channel: Some(6),
        signal: Some("INT"),
    },
    Event {
        name: "DMAC7_INT",
        id: 39,
        irq_slots: &[],
        peripheral: Some("DMAC"),
        channel: Some(7),
        signal: Some("INT"),
    },
    Event {
        name: "DMA_TRANSERR",
        id: 43,
        irq_slots: &[],
        peripheral: Some("DMA"),
        channel: None,
        signal: Some("TRANSERR"),
    },
    Event {
        name: "DOC_INT",
        id: 475,
        irq_slots: &[],
        peripheral: Some("DOC"),
        channel: None,
        signal: Some("INT"),
    },
    Event {
        name: "DTC_COMPLETE",
        id: 41,
        irq_slots: &[],
        peripheral: Some("DTC"),
        channel: None,
        signal: Some("COMPLETE"),
    },
    Event {
        name: "DTC_END",
        id: 42,
        irq_slots: &[],
        peripheral: Some("DTC"),
        channel: None,
        signal: Some("END"),
    },
    Event {
        name: "EDMAC0_EINT",
        id: 367,
        irq_slots: &[],
        peripheral: Some("EDMAC"),
        channel: Some(0),
        signal: Some("EINT"),
    },
    Event {
        name: "ELC_SOFTWARE_EVENT_0",
        id: 181,
        irq_slots: &[],
        peripheral: Some("ELC"),
        channel: None,
        signal: Some("SOFTWARE_EVENT_0"),
    },
    Event {
        name: "ELC_SOFTWARE_EVENT_1",
        id: 182,
        irq_slots: &[],
        peripheral: Some("ELC"),
        channel: None,
        signal: Some("SOFTWARE_EVENT_1"),
    },
    Event {
        name: "FCU_FIFERR",
        id: 48,
        irq_slots: &[],
        peripheral: Some("FCU"),
        channel: None,
        signal: Some("FIFERR"),
    },
    Event {
        name: "FCU_FRDYI",
        id: 49,
        irq_slots: &[],
        peripheral: Some("FCU"),
        channel: None,
        signal: Some("FRDYI"),
    },
    Event {
        name: "GPT0_CAPTURE_COMPARE_A",
        id: 192,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(0),
        signal: Some("CAPTURE_COMPARE_A"),
    },
    Event {
        name: "GPT0_CAPTURE_COMPARE_B",
        id: 193,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(0),
        signal: Some("CAPTURE_COMPARE_B"),
    },
    Event {
        name: "GPT0_COMPARE_C",
        id: 194,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(0),
        signal: Some("COMPARE_C"),
    },
    Event {
        name: "GPT0_COMPARE_D",
        id: 195,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(0),
        signal: Some("COMPARE_D"),
    },
    Event {
        name: "GPT0_COMPARE_E",
        id: 196,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(0),
        signal: Some("COMPARE_E"),
    },
    Event {
        name: "GPT0_COMPARE_F",
        id: 197,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(0),
        signal: Some("COMPARE_F"),
    },
    Event {
        name: "GPT0_COUNTER_OVERFLOW",
        id: 198,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(0),
        signal: Some("COUNTER_OVERFLOW"),
    },
    Event {
        name: "GPT0_COUNTER_UNDERFLOW",
        id: 199,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(0),
        signal: Some("COUNTER_UNDERFLOW"),
    },
    Event {
        name: "GPT0_PC",
        id: 200,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(0),
        signal: Some("PC"),
    },
    Event {
        name: "GPT1_CAPTURE_COMPARE_A",
        id: 201,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(1),
        signal: Some("CAPTURE_COMPARE_A"),
    },
    Event {
        name: "GPT1_CAPTURE_COMPARE_B",
        id: 202,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(1),
        signal: Some("CAPTURE_COMPARE_B"),
    },
    Event {
        name: "GPT1_COMPARE_C",
        id: 203,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(1),
        signal: Some("COMPARE_C"),
    },
    Event {
        name: "GPT1_COMPARE_D",
        id: 204,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(1),
        signal: Some("COMPARE_D"),
    },
    Event {
        name: "GPT1_COMPARE_E",
        id: 205,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(1),
        signal: Some("COMPARE_E"),
    },
    Event {
        name: "GPT1_COMPARE_F",
        id: 206,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(1),
        signal: Some("COMPARE_F"),
    },
    Event {
        name: "GPT1_COUNTER_OVERFLOW",
        id: 207,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(1),
        signal: Some("COUNTER_OVERFLOW"),
    },
    Event {
        name: "GPT1_COUNTER_UNDERFLOW",
        id: 208,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(1),
        signal: Some("COUNTER_UNDERFLOW"),
    },
    Event {
        name: "GPT1_PC",
        id: 209,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(1),
        signal: Some("PC"),
    },
    Event {
        name: "GPT2_CAPTURE_COMPARE_A",
        id: 210,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(2),
        signal: Some("CAPTURE_COMPARE_A"),
    },
    Event {
        name: "GPT2_CAPTURE_COMPARE_B",
        id: 211,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(2),
        signal: Some("CAPTURE_COMPARE_B"),
    },
    Event {
        name: "GPT2_COMPARE_C",
        id: 212,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(2),
        signal: Some("COMPARE_C"),
    },
    Event {
        name: "GPT2_COMPARE_D",
        id: 213,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(2),
        signal: Some("COMPARE_D"),
    },
    Event {
        name: "GPT2_COMPARE_E",
        id: 214,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(2),
        signal: Some("COMPARE_E"),
    },
    Event {
        name: "GPT2_COMPARE_F",
        id: 215,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(2),
        signal: Some("COMPARE_F"),
    },
    Event {
        name: "GPT2_COUNTER_OVERFLOW",
        id: 216,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(2),
        signal: Some("COUNTER_OVERFLOW"),
    },
    Event {
        name: "GPT2_COUNTER_UNDERFLOW",
        id: 217,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(2),
        signal: Some("COUNTER_UNDERFLOW"),
    },
    Event {
        name: "GPT3_CAPTURE_COMPARE_A",
        id: 219,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(3),
        signal: Some("CAPTURE_COMPARE_A"),
    },
    Event {
        name: "GPT3_CAPTURE_COMPARE_B",
        id: 220,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(3),
        signal: Some("CAPTURE_COMPARE_B"),
    },
    Event {
        name: "GPT3_COMPARE_C",
        id: 221,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(3),
        signal: Some("COMPARE_C"),
    },
    Event {
        name: "GPT3_COMPARE_D",
        id: 222,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(3),
        signal: Some("COMPARE_D"),
    },
    Event {
        name: "GPT3_COMPARE_E",
        id: 223,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(3),
        signal: Some("COMPARE_E"),
    },
    Event {
        name: "GPT3_COMPARE_F",
        id: 224,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(3),
        signal: Some("COMPARE_F"),
    },
    Event {
        name: "GPT3_COUNTER_OVERFLOW",
        id: 225,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(3),
        signal: Some("COUNTER_OVERFLOW"),
    },
    Event {
        name: "GPT3_COUNTER_UNDERFLOW",
        id: 226,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(3),
        signal: Some("COUNTER_UNDERFLOW"),
    },
    Event {
        name: "GPT4_CAPTURE_COMPARE_A",
        id: 228,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(4),
        signal: Some("CAPTURE_COMPARE_A"),
    },
    Event {
        name: "GPT4_CAPTURE_COMPARE_B",
        id: 229,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(4),
        signal: Some("CAPTURE_COMPARE_B"),
    },
    Event {
        name: "GPT4_COMPARE_C",
        id: 230,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(4),
        signal: Some("COMPARE_C"),
    },
    Event {
        name: "GPT4_COMPARE_D",
        id: 231,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(4),
        signal: Some("COMPARE_D"),
    },
    Event {
        name: "GPT4_COMPARE_E",
        id: 232,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(4),
        signal: Some("COMPARE_E"),
    },
    Event {
        name: "GPT4_COMPARE_F",
        id: 233,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(4),
        signal: Some("COMPARE_F"),
    },
    Event {
        name: "GPT4_COUNTER_OVERFLOW",
        id: 234,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(4),
        signal: Some("COUNTER_OVERFLOW"),
    },
    Event {
        name: "GPT4_COUNTER_UNDERFLOW",
        id: 235,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(4),
        signal: Some("COUNTER_UNDERFLOW"),
    },
    Event {
        name: "GPT4_PC",
        id: 236,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(4),
        signal: Some("PC"),
    },
    Event {
        name: "GPT5_CAPTURE_COMPARE_A",
        id: 237,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(5),
        signal: Some("CAPTURE_COMPARE_A"),
    },
    Event {
        name: "GPT5_CAPTURE_COMPARE_B",
        id: 238,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(5),
        signal: Some("CAPTURE_COMPARE_B"),
    },
    Event {
        name: "GPT5_COMPARE_C",
        id: 239,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(5),
        signal: Some("COMPARE_C"),
    },
    Event {
        name: "GPT5_COMPARE_D",
        id: 240,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(5),
        signal: Some("COMPARE_D"),
    },
    Event {
        name: "GPT5_COMPARE_E",
        id: 241,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(5),
        signal: Some("COMPARE_E"),
    },
    Event {
        name: "GPT5_COMPARE_F",
        id: 242,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(5),
        signal: Some("COMPARE_F"),
    },
    Event {
        name: "GPT5_COUNTER_OVERFLOW",
        id: 243,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(5),
        signal: Some("COUNTER_OVERFLOW"),
    },
    Event {
        name: "GPT5_COUNTER_UNDERFLOW",
        id: 244,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(5),
        signal: Some("COUNTER_UNDERFLOW"),
    },
    Event {
        name: "GPT5_PC",
        id: 245,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(5),
        signal: Some("PC"),
    },
    Event {
        name: "GPT6_CAPTURE_COMPARE_A",
        id: 246,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(6),
        signal: Some("CAPTURE_COMPARE_A"),
    },
    Event {
        name: "GPT6_CAPTURE_COMPARE_B",
        id: 247,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(6),
        signal: Some("CAPTURE_COMPARE_B"),
    },
    Event {
        name: "GPT6_COMPARE_C",
        id: 248,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(6),
        signal: Some("COMPARE_C"),
    },
    Event {
        name: "GPT6_COMPARE_D",
        id: 249,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(6),
        signal: Some("COMPARE_D"),
    },
    Event {
        name: "GPT6_COMPARE_E",
        id: 250,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(6),
        signal: Some("COMPARE_E"),
    },
    Event {
        name: "GPT6_COMPARE_F",
        id: 251,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(6),
        signal: Some("COMPARE_F"),
    },
    Event {
        name: "GPT6_COUNTER_OVERFLOW",
        id: 252,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(6),
        signal: Some("COUNTER_OVERFLOW"),
    },
    Event {
        name: "GPT6_COUNTER_UNDERFLOW",
        id: 253,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(6),
        signal: Some("COUNTER_UNDERFLOW"),
    },
    Event {
        name: "GPT6_PC",
        id: 254,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(6),
        signal: Some("PC"),
    },
    Event {
        name: "GPT7_CAPTURE_COMPARE_A",
        id: 255,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(7),
        signal: Some("CAPTURE_COMPARE_A"),
    },
    Event {
        name: "GPT7_CAPTURE_COMPARE_B",
        id: 256,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(7),
        signal: Some("CAPTURE_COMPARE_B"),
    },
    Event {
        name: "GPT7_COMPARE_C",
        id: 257,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(7),
        signal: Some("COMPARE_C"),
    },
    Event {
        name: "GPT7_COMPARE_D",
        id: 258,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(7),
        signal: Some("COMPARE_D"),
    },
    Event {
        name: "GPT7_COMPARE_E",
        id: 259,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(7),
        signal: Some("COMPARE_E"),
    },
    Event {
        name: "GPT7_COMPARE_F",
        id: 260,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(7),
        signal: Some("COMPARE_F"),
    },
    Event {
        name: "GPT7_COUNTER_OVERFLOW",
        id: 261,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(7),
        signal: Some("COUNTER_OVERFLOW"),
    },
    Event {
        name: "GPT7_COUNTER_UNDERFLOW",
        id: 262,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(7),
        signal: Some("COUNTER_UNDERFLOW"),
    },
    Event {
        name: "GPT8_CAPTURE_COMPARE_A",
        id: 264,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(8),
        signal: Some("CAPTURE_COMPARE_A"),
    },
    Event {
        name: "GPT8_CAPTURE_COMPARE_B",
        id: 265,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(8),
        signal: Some("CAPTURE_COMPARE_B"),
    },
    Event {
        name: "GPT8_COMPARE_C",
        id: 266,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(8),
        signal: Some("COMPARE_C"),
    },
    Event {
        name: "GPT8_COMPARE_D",
        id: 267,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(8),
        signal: Some("COMPARE_D"),
    },
    Event {
        name: "GPT8_COMPARE_E",
        id: 268,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(8),
        signal: Some("COMPARE_E"),
    },
    Event {
        name: "GPT8_COMPARE_F",
        id: 269,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(8),
        signal: Some("COMPARE_F"),
    },
    Event {
        name: "GPT8_COUNTER_OVERFLOW",
        id: 270,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(8),
        signal: Some("COUNTER_OVERFLOW"),
    },
    Event {
        name: "GPT8_COUNTER_UNDERFLOW",
        id: 271,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(8),
        signal: Some("COUNTER_UNDERFLOW"),
    },
    Event {
        name: "GPT9_CAPTURE_COMPARE_A",
        id: 273,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(9),
        signal: Some("CAPTURE_COMPARE_A"),
    },
    Event {
        name: "GPT9_CAPTURE_COMPARE_B",
        id: 274,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(9),
        signal: Some("CAPTURE_COMPARE_B"),
    },
    Event {
        name: "GPT9_COMPARE_C",
        id: 275,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(9),
        signal: Some("COMPARE_C"),
    },
    Event {
        name: "GPT9_COMPARE_D",
        id: 276,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(9),
        signal: Some("COMPARE_D"),
    },
    Event {
        name: "GPT9_COMPARE_E",
        id: 277,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(9),
        signal: Some("COMPARE_E"),
    },
    Event {
        name: "GPT9_COMPARE_F",
        id: 278,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(9),
        signal: Some("COMPARE_F"),
    },
    Event {
        name: "GPT9_COUNTER_OVERFLOW",
        id: 279,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(9),
        signal: Some("COUNTER_OVERFLOW"),
    },
    Event {
        name: "GPT9_COUNTER_UNDERFLOW",
        id: 280,
        irq_slots: &[],
        peripheral: Some("GPT"),
        channel: Some(9),
        signal: Some("COUNTER_UNDERFLOW"),
    },
    Event {
        name: "ICU_IRQ0",
        id: 1,
        irq_slots: &[],
        peripheral: Some("ICU"),
        channel: Some(0),
        signal: Some("IRQ"),
    },
    Event {
        name: "ICU_IRQ1",
        id: 2,
        irq_slots: &[],
        peripheral: Some("ICU"),
        channel: Some(1),
        signal: Some("IRQ"),
    },
    Event {
        name: "ICU_IRQ10",
        id: 11,
        irq_slots: &[],
        peripheral: Some("ICU"),
        channel: Some(10),
        signal: Some("IRQ"),
    },
    Event {
        name: "ICU_IRQ11",
        id: 12,
        irq_slots: &[],
        peripheral: Some("ICU"),
        channel: Some(11),
        signal: Some("IRQ"),
    },
    Event {
        name: "ICU_IRQ12",
        id: 13,
        irq_slots: &[],
        peripheral: Some("ICU"),
        channel: Some(12),
        signal: Some("IRQ"),
    },
    Event {
        name: "ICU_IRQ13",
        id: 14,
        irq_slots: &[],
        peripheral: Some("ICU"),
        channel: Some(13),
        signal: Some("IRQ"),
    },
    Event {
        name: "ICU_IRQ14",
        id: 15,
        irq_slots: &[],
        peripheral: Some("ICU"),
        channel: Some(14),
        signal: Some("IRQ"),
    },
    Event {
        name: "ICU_IRQ15",
        id: 16,
        irq_slots: &[],
        peripheral: Some("ICU"),
        channel: Some(15),
        signal: Some("IRQ"),
    },
    Event {
        name: "ICU_IRQ2",
        id: 3,
        irq_slots: &[],
        peripheral: Some("ICU"),
        channel: Some(2),
        signal: Some("IRQ"),
    },
    Event {
        name: "ICU_IRQ3",
        id: 4,
        irq_slots: &[],
        peripheral: Some("ICU"),
        channel: Some(3),
        signal: Some("IRQ"),
    },
    Event {
        name: "ICU_IRQ4",
        id: 5,
        irq_slots: &[],
        peripheral: Some("ICU"),
        channel: Some(4),
        signal: Some("IRQ"),
    },
    Event {
        name: "ICU_IRQ5",
        id: 6,
        irq_slots: &[],
        peripheral: Some("ICU"),
        channel: Some(5),
        signal: Some("IRQ"),
    },
    Event {
        name: "ICU_IRQ6",
        id: 7,
        irq_slots: &[],
        peripheral: Some("ICU"),
        channel: Some(6),
        signal: Some("IRQ"),
    },
    Event {
        name: "ICU_IRQ7",
        id: 8,
        irq_slots: &[],
        peripheral: Some("ICU"),
        channel: Some(7),
        signal: Some("IRQ"),
    },
    Event {
        name: "ICU_IRQ8",
        id: 9,
        irq_slots: &[],
        peripheral: Some("ICU"),
        channel: Some(8),
        signal: Some("IRQ"),
    },
    Event {
        name: "ICU_IRQ9",
        id: 10,
        irq_slots: &[],
        peripheral: Some("ICU"),
        channel: Some(9),
        signal: Some("IRQ"),
    },
    Event {
        name: "ICU_SNOOZE_CANCEL",
        id: 45,
        irq_slots: &[],
        peripheral: Some("ICU"),
        channel: None,
        signal: Some("SNOOZE_CANCEL"),
    },
    Event {
        name: "IIC0_ERI",
        id: 118,
        irq_slots: &[],
        peripheral: Some("IIC"),
        channel: Some(0),
        signal: Some("ERI"),
    },
    Event {
        name: "IIC0_RXI",
        id: 115,
        irq_slots: &[],
        peripheral: Some("IIC"),
        channel: Some(0),
        signal: Some("RXI"),
    },
    Event {
        name: "IIC0_TEI",
        id: 117,
        irq_slots: &[],
        peripheral: Some("IIC"),
        channel: Some(0),
        signal: Some("TEI"),
    },
    Event {
        name: "IIC0_TXI",
        id: 116,
        irq_slots: &[],
        peripheral: Some("IIC"),
        channel: Some(0),
        signal: Some("TXI"),
    },
    Event {
        name: "IIC0_WUI",
        id: 119,
        irq_slots: &[],
        peripheral: Some("IIC"),
        channel: Some(0),
        signal: Some("WUI"),
    },
    Event {
        name: "IIC1_ERI",
        id: 123,
        irq_slots: &[],
        peripheral: Some("IIC"),
        channel: Some(1),
        signal: Some("ERI"),
    },
    Event {
        name: "IIC1_RXI",
        id: 120,
        irq_slots: &[],
        peripheral: Some("IIC"),
        channel: Some(1),
        signal: Some("RXI"),
    },
    Event {
        name: "IIC1_TEI",
        id: 122,
        irq_slots: &[],
        peripheral: Some("IIC"),
        channel: Some(1),
        signal: Some("TEI"),
    },
    Event {
        name: "IIC1_TXI",
        id: 121,
        irq_slots: &[],
        peripheral: Some("IIC"),
        channel: Some(1),
        signal: Some("TXI"),
    },
    Event {
        name: "IIC2_ERI",
        id: 128,
        irq_slots: &[],
        peripheral: Some("IIC"),
        channel: Some(2),
        signal: Some("ERI"),
    },
    Event {
        name: "IIC2_RXI",
        id: 125,
        irq_slots: &[],
        peripheral: Some("IIC"),
        channel: Some(2),
        signal: Some("RXI"),
    },
    Event {
        name: "IIC2_TEI",
        id: 127,
        irq_slots: &[],
        peripheral: Some("IIC"),
        channel: Some(2),
        signal: Some("TEI"),
    },
    Event {
        name: "IIC2_TXI",
        id: 126,
        irq_slots: &[],
        peripheral: Some("IIC"),
        channel: Some(2),
        signal: Some("TXI"),
    },
    Event {
        name: "IOPORT_EVENT_1",
        id: 177,
        irq_slots: &[],
        peripheral: Some("IOPORT"),
        channel: None,
        signal: Some("EVENT_1"),
    },
    Event {
        name: "IOPORT_EVENT_2",
        id: 178,
        irq_slots: &[],
        peripheral: Some("IOPORT"),
        channel: None,
        signal: Some("EVENT_2"),
    },
    Event {
        name: "IOPORT_EVENT_3",
        id: 179,
        irq_slots: &[],
        peripheral: Some("IOPORT"),
        channel: None,
        signal: Some("EVENT_3"),
    },
    Event {
        name: "IOPORT_EVENT_4",
        id: 180,
        irq_slots: &[],
        peripheral: Some("IOPORT"),
        channel: None,
        signal: Some("EVENT_4"),
    },
    Event {
        name: "IWDT_UNDERFLOW",
        id: 82,
        irq_slots: &[],
        peripheral: Some("IWDT"),
        channel: None,
        signal: Some("UNDERFLOW"),
    },
    Event {
        name: "LPM_SNOOZE_REQUEST",
        id: 60,
        irq_slots: &[],
        peripheral: Some("LPM"),
        channel: None,
        signal: Some("SNOOZE_REQUEST"),
    },
    Event {
        name: "LVD_LVD1",
        id: 56,
        irq_slots: &[],
        peripheral: Some("LVD"),
        channel: Some(1),
        signal: Some("LVD"),
    },
    Event {
        name: "LVD_LVD2",
        id: 57,
        irq_slots: &[],
        peripheral: Some("LVD"),
        channel: Some(2),
        signal: Some("LVD"),
    },
    Event {
        name: "OPS_UVW_EDGE",
        id: 336,
        irq_slots: &[],
        peripheral: Some("OPS"),
        channel: None,
        signal: Some("UVW_EDGE"),
    },
    Event {
        name: "OSPI_INT",
        id: 473,
        irq_slots: &[],
        peripheral: Some("OSPI"),
        channel: None,
        signal: Some("INT"),
    },
    Event {
        name: "POEG0_EVENT",
        id: 183,
        irq_slots: &[],
        peripheral: Some("POEG"),
        channel: Some(0),
        signal: Some("EVENT"),
    },
    Event {
        name: "POEG1_EVENT",
        id: 184,
        irq_slots: &[],
        peripheral: Some("POEG"),
        channel: Some(1),
        signal: Some("EVENT"),
    },
    Event {
        name: "POEG2_EVENT",
        id: 185,
        irq_slots: &[],
        peripheral: Some("POEG"),
        channel: Some(2),
        signal: Some("EVENT"),
    },
    Event {
        name: "POEG3_EVENT",
        id: 186,
        irq_slots: &[],
        peripheral: Some("POEG"),
        channel: Some(3),
        signal: Some("EVENT"),
    },
    Event {
        name: "QSPI_INT",
        id: 474,
        irq_slots: &[],
        peripheral: Some("QSPI"),
        channel: None,
        signal: Some("INT"),
    },
    Event {
        name: "RTC_ALARM",
        id: 84,
        irq_slots: &[],
        peripheral: Some("RTC"),
        channel: None,
        signal: Some("ALARM"),
    },
    Event {
        name: "RTC_CARRY",
        id: 86,
        irq_slots: &[],
        peripheral: Some("RTC"),
        channel: None,
        signal: Some("CARRY"),
    },
    Event {
        name: "RTC_PERIOD",
        id: 85,
        irq_slots: &[],
        peripheral: Some("RTC"),
        channel: None,
        signal: Some("PERIOD"),
    },
    Event {
        name: "SCE_TADI",
        id: 489,
        irq_slots: &[],
        peripheral: Some("SCE"),
        channel: None,
        signal: Some("TADI"),
    },
    Event {
        name: "SCI0_AM",
        id: 388,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(0),
        signal: Some("AM"),
    },
    Event {
        name: "SCI0_ERI",
        id: 387,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(0),
        signal: Some("ERI"),
    },
    Event {
        name: "SCI0_RXI",
        id: 384,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(0),
        signal: Some("RXI"),
    },
    Event {
        name: "SCI0_RXI_OR_ERI",
        id: 389,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(0),
        signal: Some("RXI_OR_ERI"),
    },
    Event {
        name: "SCI0_TEI",
        id: 386,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(0),
        signal: Some("TEI"),
    },
    Event {
        name: "SCI0_TXI",
        id: 385,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(0),
        signal: Some("TXI"),
    },
    Event {
        name: "SCI1_ERI",
        id: 393,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(1),
        signal: Some("ERI"),
    },
    Event {
        name: "SCI1_RXI",
        id: 390,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(1),
        signal: Some("RXI"),
    },
    Event {
        name: "SCI1_SCIX0",
        id: 444,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(1),
        signal: Some("SCIX0"),
    },
    Event {
        name: "SCI1_SCIX1",
        id: 445,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(1),
        signal: Some("SCIX1"),
    },
    Event {
        name: "SCI1_SCIX2",
        id: 446,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(1),
        signal: Some("SCIX2"),
    },
    Event {
        name: "SCI1_SCIX3",
        id: 447,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(1),
        signal: Some("SCIX3"),
    },
    Event {
        name: "SCI1_TEI",
        id: 392,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(1),
        signal: Some("TEI"),
    },
    Event {
        name: "SCI1_TXI",
        id: 391,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(1),
        signal: Some("TXI"),
    },
    Event {
        name: "SCI2_ERI",
        id: 399,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(2),
        signal: Some("ERI"),
    },
    Event {
        name: "SCI2_RXI",
        id: 396,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(2),
        signal: Some("RXI"),
    },
    Event {
        name: "SCI2_SCIX0",
        id: 448,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(2),
        signal: Some("SCIX0"),
    },
    Event {
        name: "SCI2_SCIX1",
        id: 449,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(2),
        signal: Some("SCIX1"),
    },
    Event {
        name: "SCI2_SCIX2",
        id: 450,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(2),
        signal: Some("SCIX2"),
    },
    Event {
        name: "SCI2_SCIX3",
        id: 451,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(2),
        signal: Some("SCIX3"),
    },
    Event {
        name: "SCI2_TEI",
        id: 398,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(2),
        signal: Some("TEI"),
    },
    Event {
        name: "SCI2_TXI",
        id: 397,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(2),
        signal: Some("TXI"),
    },
    Event {
        name: "SCI3_AM",
        id: 406,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(3),
        signal: Some("AM"),
    },
    Event {
        name: "SCI3_ERI",
        id: 405,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(3),
        signal: Some("ERI"),
    },
    Event {
        name: "SCI3_RXI",
        id: 402,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(3),
        signal: Some("RXI"),
    },
    Event {
        name: "SCI3_TEI",
        id: 404,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(3),
        signal: Some("TEI"),
    },
    Event {
        name: "SCI3_TXI",
        id: 403,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(3),
        signal: Some("TXI"),
    },
    Event {
        name: "SCI4_AM",
        id: 412,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(4),
        signal: Some("AM"),
    },
    Event {
        name: "SCI4_ERI",
        id: 411,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(4),
        signal: Some("ERI"),
    },
    Event {
        name: "SCI4_RXI",
        id: 408,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(4),
        signal: Some("RXI"),
    },
    Event {
        name: "SCI4_TEI",
        id: 410,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(4),
        signal: Some("TEI"),
    },
    Event {
        name: "SCI4_TXI",
        id: 409,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(4),
        signal: Some("TXI"),
    },
    Event {
        name: "SCI5_AM",
        id: 418,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(5),
        signal: Some("AM"),
    },
    Event {
        name: "SCI5_ERI",
        id: 417,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(5),
        signal: Some("ERI"),
    },
    Event {
        name: "SCI5_RXI",
        id: 414,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(5),
        signal: Some("RXI"),
    },
    Event {
        name: "SCI5_TEI",
        id: 416,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(5),
        signal: Some("TEI"),
    },
    Event {
        name: "SCI5_TXI",
        id: 415,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(5),
        signal: Some("TXI"),
    },
    Event {
        name: "SCI6_AM",
        id: 424,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(6),
        signal: Some("AM"),
    },
    Event {
        name: "SCI6_ERI",
        id: 423,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(6),
        signal: Some("ERI"),
    },
    Event {
        name: "SCI6_RXI",
        id: 420,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(6),
        signal: Some("RXI"),
    },
    Event {
        name: "SCI6_TEI",
        id: 422,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(6),
        signal: Some("TEI"),
    },
    Event {
        name: "SCI6_TXI",
        id: 421,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(6),
        signal: Some("TXI"),
    },
    Event {
        name: "SCI7_AM",
        id: 430,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(7),
        signal: Some("AM"),
    },
    Event {
        name: "SCI7_ERI",
        id: 429,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(7),
        signal: Some("ERI"),
    },
    Event {
        name: "SCI7_RXI",
        id: 426,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(7),
        signal: Some("RXI"),
    },
    Event {
        name: "SCI7_TEI",
        id: 428,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(7),
        signal: Some("TEI"),
    },
    Event {
        name: "SCI7_TXI",
        id: 427,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(7),
        signal: Some("TXI"),
    },
    Event {
        name: "SCI8_AM",
        id: 436,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(8),
        signal: Some("AM"),
    },
    Event {
        name: "SCI8_ERI",
        id: 435,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(8),
        signal: Some("ERI"),
    },
    Event {
        name: "SCI8_RXI",
        id: 432,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(8),
        signal: Some("RXI"),
    },
    Event {
        name: "SCI8_TEI",
        id: 434,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(8),
        signal: Some("TEI"),
    },
    Event {
        name: "SCI8_TXI",
        id: 433,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(8),
        signal: Some("TXI"),
    },
    Event {
        name: "SCI9_AM",
        id: 442,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(9),
        signal: Some("AM"),
    },
    Event {
        name: "SCI9_ERI",
        id: 441,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(9),
        signal: Some("ERI"),
    },
    Event {
        name: "SCI9_RXI",
        id: 438,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(9),
        signal: Some("RXI"),
    },
    Event {
        name: "SCI9_TEI",
        id: 440,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(9),
        signal: Some("TEI"),
    },
    Event {
        name: "SCI9_TXI",
        id: 439,
        irq_slots: &[],
        peripheral: Some("SCI"),
        channel: Some(9),
        signal: Some("TXI"),
    },
    Event {
        name: "SCIX0_SCIX0",
        id: 444,
        irq_slots: &[],
        peripheral: Some("SCIX"),
        channel: Some(0),
        signal: Some("SCIX0"),
    },
    Event {
        name: "SCIX0_SCIX1",
        id: 445,
        irq_slots: &[],
        peripheral: Some("SCIX"),
        channel: Some(0),
        signal: Some("SCIX1"),
    },
    Event {
        name: "SCIX0_SCIX2",
        id: 446,
        irq_slots: &[],
        peripheral: Some("SCIX"),
        channel: Some(0),
        signal: Some("SCIX2"),
    },
    Event {
        name: "SCIX0_SCIX3",
        id: 447,
        irq_slots: &[],
        peripheral: Some("SCIX"),
        channel: Some(0),
        signal: Some("SCIX3"),
    },
    Event {
        name: "SCIX1_SCIX0",
        id: 448,
        irq_slots: &[],
        peripheral: Some("SCIX"),
        channel: Some(1),
        signal: Some("SCIX0"),
    },
    Event {
        name: "SCIX1_SCIX1",
        id: 449,
        irq_slots: &[],
        peripheral: Some("SCIX"),
        channel: Some(1),
        signal: Some("SCIX1"),
    },
    Event {
        name: "SCIX1_SCIX2",
        id: 450,
        irq_slots: &[],
        peripheral: Some("SCIX"),
        channel: Some(1),
        signal: Some("SCIX2"),
    },
    Event {
        name: "SCIX1_SCIX3",
        id: 451,
        irq_slots: &[],
        peripheral: Some("SCIX"),
        channel: Some(1),
        signal: Some("SCIX3"),
    },
    Event {
        name: "SDHIMMC0_ACCS",
        id: 130,
        irq_slots: &[],
        peripheral: Some("SDHIMMC"),
        channel: Some(0),
        signal: Some("ACCS"),
    },
    Event {
        name: "SDHIMMC0_CARD",
        id: 132,
        irq_slots: &[],
        peripheral: Some("SDHIMMC"),
        channel: Some(0),
        signal: Some("CARD"),
    },
    Event {
        name: "SDHIMMC0_DMA_REQ",
        id: 133,
        irq_slots: &[],
        peripheral: Some("SDHIMMC"),
        channel: Some(0),
        signal: Some("DMA_REQ"),
    },
    Event {
        name: "SDHIMMC0_SDIO",
        id: 131,
        irq_slots: &[],
        peripheral: Some("SDHIMMC"),
        channel: Some(0),
        signal: Some("SDIO"),
    },
    Event {
        name: "SPI0_ERI",
        id: 455,
        irq_slots: &[],
        peripheral: Some("SPI"),
        channel: Some(0),
        signal: Some("ERI"),
    },
    Event {
        name: "SPI0_IDLE",
        id: 454,
        irq_slots: &[],
        peripheral: Some("SPI"),
        channel: Some(0),
        signal: Some("IDLE"),
    },
    Event {
        name: "SPI0_RXI",
        id: 452,
        irq_slots: &[],
        peripheral: Some("SPI"),
        channel: Some(0),
        signal: Some("RXI"),
    },
    Event {
        name: "SPI0_TEI",
        id: 456,
        irq_slots: &[],
        peripheral: Some("SPI"),
        channel: Some(0),
        signal: Some("TEI"),
    },
    Event {
        name: "SPI0_TXI",
        id: 453,
        irq_slots: &[],
        peripheral: Some("SPI"),
        channel: Some(0),
        signal: Some("TXI"),
    },
    Event {
        name: "SPI1_ERI",
        id: 460,
        irq_slots: &[],
        peripheral: Some("SPI"),
        channel: Some(1),
        signal: Some("ERI"),
    },
    Event {
        name: "SPI1_IDLE",
        id: 459,
        irq_slots: &[],
        peripheral: Some("SPI"),
        channel: Some(1),
        signal: Some("IDLE"),
    },
    Event {
        name: "SPI1_RXI",
        id: 457,
        irq_slots: &[],
        peripheral: Some("SPI"),
        channel: Some(1),
        signal: Some("RXI"),
    },
    Event {
        name: "SPI1_TEI",
        id: 461,
        irq_slots: &[],
        peripheral: Some("SPI"),
        channel: Some(1),
        signal: Some("TEI"),
    },
    Event {
        name: "SPI1_TXI",
        id: 458,
        irq_slots: &[],
        peripheral: Some("SPI"),
        channel: Some(1),
        signal: Some("TXI"),
    },
    Event {
        name: "SSI0_INT",
        id: 141,
        irq_slots: &[],
        peripheral: Some("SSI"),
        channel: Some(0),
        signal: Some("INT"),
    },
    Event {
        name: "SSI0_RXI",
        id: 139,
        irq_slots: &[],
        peripheral: Some("SSI"),
        channel: Some(0),
        signal: Some("RXI"),
    },
    Event {
        name: "SSI0_TXI",
        id: 138,
        irq_slots: &[],
        peripheral: Some("SSI"),
        channel: Some(0),
        signal: Some("TXI"),
    },
    Event {
        name: "USBFS_FIFO_0",
        id: 107,
        irq_slots: &[],
        peripheral: Some("USBFS"),
        channel: None,
        signal: Some("FIFO_0"),
    },
    Event {
        name: "USBFS_FIFO_1",
        id: 108,
        irq_slots: &[],
        peripheral: Some("USBFS"),
        channel: None,
        signal: Some("FIFO_1"),
    },
    Event {
        name: "USBFS_INT",
        id: 109,
        irq_slots: &[],
        peripheral: Some("USBFS"),
        channel: None,
        signal: Some("INT"),
    },
    Event {
        name: "USBFS_RESUME",
        id: 110,
        irq_slots: &[],
        peripheral: Some("USBFS"),
        channel: None,
        signal: Some("RESUME"),
    },
    Event {
        name: "USBHS_FIFO_0",
        id: 381,
        irq_slots: &[],
        peripheral: Some("USBHS"),
        channel: None,
        signal: Some("FIFO_0"),
    },
    Event {
        name: "USBHS_FIFO_1",
        id: 382,
        irq_slots: &[],
        peripheral: Some("USBHS"),
        channel: None,
        signal: Some("FIFO_1"),
    },
    Event {
        name: "USBHS_USB_INT_RESUME",
        id: 383,
        irq_slots: &[],
        peripheral: Some("USBHS"),
        channel: None,
        signal: Some("USB_INT_RESUME"),
    },
    Event {
        name: "WDT_UNDERFLOW",
        id: 83,
        irq_slots: &[],
        peripheral: Some("WDT"),
        channel: None,
        signal: Some("UNDERFLOW"),
    },
];
const PACKAGES: &[Package] = &[
    Package {
        name: "176BGA",
        pins: &[
            Pin {
                position: "A1",
                signals: &[
                    "p109",
                ],
            },
            Pin {
                position: "A10",
                signals: &[
                    "p214",
                ],
            },
            Pin {
                position: "A11",
                signals: &[
                    "p900",
                ],
            },
            Pin {
                position: "A12",
                signals: &[
                    "p313",
                ],
            },
            Pin {
                position: "A13",
                signals: &[
                    "p204",
                ],
            },
            Pin {
                position: "A14",
                signals: &[
                    "usbdp",
                ],
            },
            Pin {
                position: "A15",
                signals: &[
                    "p407",
                ],
            },
            Pin {
                position: "A2",
                signals: &[
                    "p301",
                ],
            },
            Pin {
                position: "A3",
                signals: &[
                    "p303",
                ],
            },
            Pin {
                position: "A4",
                signals: &[
                    "p306",
                ],
            },
            Pin {
                position: "A5",
                signals: &[
                    "p308",
                ],
            },
            Pin {
                position: "A6",
                signals: &[
                    "p310",
                ],
            },
            Pin {
                position: "A7",
                signals: &[
                    "p906",
                ],
            },
            Pin {
                position: "A8",
                signals: &[
                    "p208",
                ],
            },
            Pin {
                position: "A9",
                signals: &[
                    "p210",
                ],
            },
            Pin {
                position: "B1",
                signals: &[
                    "p113",
                ],
            },
            Pin {
                position: "B10",
                signals: &[
                    "p211",
                ],
            },
            Pin {
                position: "B11",
                signals: &[
                    "p315",
                ],
            },
            Pin {
                position: "B12",
                signals: &[
                    "p202",
                ],
            },
            Pin {
                position: "B13",
                signals: &[
                    "vccusb",
                ],
            },
            Pin {
                position: "B14",
                signals: &[
                    "usbdm",
                ],
            },
            Pin {
                position: "B15",
                signals: &[
                    "p409",
                ],
            },
            Pin {
                position: "B2",
                signals: &[
                    "p112",
                ],
            },
            Pin {
                position: "B3",
                signals: &[
                    "p302",
                ],
            },
            Pin {
                position: "B4",
                signals: &[
                    "p304",
                ],
            },
            Pin {
                position: "B5",
                signals: &[
                    "p305",
                ],
            },
            Pin {
                position: "B6",
                signals: &[
                    "p309",
                ],
            },
            Pin {
                position: "B7",
                signals: &[
                    "p905",
                ],
            },
            Pin {
                position: "B8",
                signals: &[
                    "p201",
                ],
            },
            Pin {
                position: "B9",
                signals: &[
                    "p209",
                ],
            },
            Pin {
                position: "C1",
                signals: &[
                    "p115",
                ],
            },
            Pin {
                position: "C10",
                signals: &[
                    "p901",
                ],
            },
            Pin {
                position: "C11",
                signals: &[
                    "p314",
                ],
            },
            Pin {
                position: "C12",
                signals: &[
                    "p207",
                ],
            },
            Pin {
                position: "C13",
                signals: &[
                    "vssusb",
                ],
            },
            Pin {
                position: "C14",
                signals: &[
                    "p410",
                ],
            },
            Pin {
                position: "C15",
                signals: &[
                    "p411",
                ],
            },
            Pin {
                position: "C2",
                signals: &[
                    "p114",
                ],
            },
            Pin {
                position: "C3",
                signals: &[
                    "p108",
                ],
            },
            Pin {
                position: "C4",
                signals: &[
                    "p300",
                ],
            },
            Pin {
                position: "C5",
                signals: &[
                    "vss",
                ],
            },
            Pin {
                position: "C6",
                signals: &[
                    "p307",
                ],
            },
            Pin {
                position: "C7",
                signals: &[
                    "p312",
                ],
            },
            Pin {
                position: "C8",
                signals: &[
                    "p200",
                ],
            },
            Pin {
                position: "C9",
                signals: &[
                    "res",
                ],
            },
            Pin {
                position: "D1",
                signals: &[
                    "p609",
                ],
            },
            Pin {
                position: "D10",
                signals: &[
                    "vss",
                ],
            },
            Pin {
                position: "D11",
                signals: &[
                    "p203",
                ],
            },
            Pin {
                position: "D12",
                signals: &[
                    "p206",
                ],
            },
            Pin {
                position: "D13",
                signals: &[
                    "p408",
                ],
            },
            Pin {
                position: "D14",
                signals: &[
                    "p412",
                ],
            },
            Pin {
                position: "D15",
                signals: &[
                    "p414",
                ],
            },
            Pin {
                position: "D2",
                signals: &[
                    "p608",
                ],
            },
            Pin {
                position: "D3",
                signals: &[
                    "p110",
                ],
            },
            Pin {
                position: "D4",
                signals: &[
                    "p111",
                ],
            },
            Pin {
                position: "D5",
                signals: &[
                    "vcc",
                ],
            },
            Pin {
                position: "D6",
                signals: &[
                    "p311",
                ],
            },
            Pin {
                position: "D7",
                signals: &[
                    "p907",
                ],
            },
            Pin {
                position: "D8",
                signals: &[
                    "p908",
                ],
            },
            Pin {
                position: "D9",
                signals: &[
                    "vcc",
                ],
            },
            Pin {
                position: "E1",
                signals: &[
                    "p612",
                ],
            },
            Pin {
                position: "E12",
                signals: &[
                    "p205",
                ],
            },
            Pin {
                position: "E13",
                signals: &[
                    "p413",
                ],
            },
            Pin {
                position: "E14",
                signals: &[
                    "p415",
                ],
            },
            Pin {
                position: "E15",
                signals: &[
                    "p708",
                ],
            },
            Pin {
                position: "E2",
                signals: &[
                    "p611",
                ],
            },
            Pin {
                position: "E3",
                signals: &[
                    "vcc",
                ],
            },
            Pin {
                position: "E4",
                signals: &[
                    "vss",
                ],
            },
            Pin {
                position: "F1",
                signals: &[
                    "p615",
                ],
            },
            Pin {
                position: "F12",
                signals: &[
                    "vss1usbhs",
                ],
            },
            Pin {
                position: "F13",
                signals: &[
                    "vccusbhs",
                ],
            },
            Pin {
                position: "F14",
                signals: &[
                    "usbhsdp",
                ],
            },
            Pin {
                position: "F15",
                signals: &[
                    "usbhsdm",
                ],
            },
            Pin {
                position: "F2",
                signals: &[
                    "p614",
                ],
            },
            Pin {
                position: "F3",
                signals: &[
                    "p610",
                ],
            },
            Pin {
                position: "F4",
                signals: &[
                    "p613",
                ],
            },
            Pin {
                position: "G1",
                signals: &[
                    "pa08",
                ],
            },
            Pin {
                position: "G12",
                signals: &[
                    "vss2usbhs",
                ],
            },
            Pin {
                position: "G13",
                signals: &[
                    "usbhsrref",
                ],
            },
            Pin {
                position: "G14",
                signals: &[
                    "avssusbhs",
                ],
            },
            Pin {
                position: "G15",
                signals: &[
                    "pvssusbhs",
                ],
            },
            Pin {
                position: "G2",
                signals: &[
                    "pa10",
                ],
            },
            Pin {
                position: "G3",
                signals: &[
                    "vcc",
                ],
            },
            Pin {
                position: "G4",
                signals: &[
                    "pa09",
                ],
            },
            Pin {
                position: "H1",
                signals: &[
                    "vcl",
                ],
            },
            Pin {
                position: "H12",
                signals: &[
                    "vcc",
                ],
            },
            Pin {
                position: "H13",
                signals: &[
                    "avccusbhs",
                ],
            },
            Pin {
                position: "H14",
                signals: &[
                    "p213",
                ],
            },
            Pin {
                position: "H15",
                signals: &[
                    "p212",
                ],
            },
            Pin {
                position: "H2",
                signals: &[
                    "pa01",
                ],
            },
            Pin {
                position: "H3",
                signals: &[
                    "vss",
                ],
            },
            Pin {
                position: "H4",
                signals: &[
                    "pa00",
                ],
            },
            Pin {
                position: "J1",
                signals: &[
                    "p606",
                ],
            },
            Pin {
                position: "J12",
                signals: &[
                    "pb00",
                ],
            },
            Pin {
                position: "J13",
                signals: &[
                    "vss",
                ],
            },
            Pin {
                position: "J14",
                signals: &[
                    "xcout",
                ],
            },
            Pin {
                position: "J15",
                signals: &[
                    "xcin",
                ],
            },
            Pin {
                position: "J2",
                signals: &[
                    "p605",
                ],
            },
            Pin {
                position: "J3",
                signals: &[
                    "p604",
                ],
            },
            Pin {
                position: "J4",
                signals: &[
                    "p607",
                ],
            },
            Pin {
                position: "K1",
                signals: &[
                    "p602",
                ],
            },
            Pin {
                position: "K12",
                signals: &[
                    "p705",
                ],
            },
            Pin {
                position: "K13",
                signals: &[
                    "pb01",
                ],
            },
            Pin {
                position: "K14",
                signals: &[
                    "vbatt",
                ],
            },
            Pin {
                position: "K15",
                signals: &[
                    "vcl0",
                ],
            },
            Pin {
                position: "K2",
                signals: &[
                    "p601",
                ],
            },
            Pin {
                position: "K3",
                signals: &[
                    "p603",
                ],
            },
            Pin {
                position: "K4",
                signals: &[
                    "vcc",
                ],
            },
            Pin {
                position: "L1",
                signals: &[
                    "p600",
                ],
            },
            Pin {
                position: "L12",
                signals: &[
                    "p702",
                ],
            },
            Pin {
                position: "L13",
                signals: &[
                    "p704",
                ],
            },
            Pin {
                position: "L14",
                signals: &[
                    "p706",
                ],
            },
            Pin {
                position: "L15",
                signals: &[
                    "p707",
                ],
            },
            Pin {
                position: "L2",
                signals: &[
                    "p107",
                ],
            },
            Pin {
                position: "L3",
                signals: &[
                    "p105",
                ],
            },
            Pin {
                position: "L4",
                signals: &[
                    "vss",
                ],
            },
            Pin {
                position: "M1",
                signals: &[
                    "p106",
                ],
            },
            Pin {
                position: "M10",
                signals: &[
                    "vss",
                ],
            },
            Pin {
                position: "M11",
                signals: &[
                    "vcc",
                ],
            },
            Pin {
                position: "M12",
                signals: &[
                    "p403",
                ],
            },
            Pin {
                position: "M13",
                signals: &[
                    "p404",
                ],
            },
            Pin {
                position: "M14",
                signals: &[
                    "p701",
                ],
            },
            Pin {
                position: "M15",
                signals: &[
                    "p703",
                ],
            },
            Pin {
                position: "M2",
                signals: &[
                    "p104",
                ],
            },
            Pin {
                position: "M3",
                signals: &[
                    "p102",
                ],
            },
            Pin {
                position: "M4",
                signals: &[
                    "vss",
                ],
            },
            Pin {
                position: "M5",
                signals: &[
                    "p003",
                ],
            },
            Pin {
                position: "M6",
                signals: &[
                    "p007",
                ],
            },
            Pin {
                position: "M7",
                signals: &[
                    "vcc",
                ],
            },
            Pin {
                position: "M8",
                signals: &[
                    "p010",
                ],
            },
            Pin {
                position: "M9",
                signals: &[
                    "p009",
                ],
            },
            Pin {
                position: "N1",
                signals: &[
                    "p103",
                ],
            },
            Pin {
                position: "N10",
                signals: &[
                    "p006",
                ],
            },
            Pin {
                position: "N11",
                signals: &[
                    "p001",
                ],
            },
            Pin {
                position: "N12",
                signals: &[
                    "p513",
                ],
            },
            Pin {
                position: "N13",
                signals: &[
                    "p400",
                ],
            },
            Pin {
                position: "N14",
                signals: &[
                    "p406",
                ],
            },
            Pin {
                position: "N15",
                signals: &[
                    "p700",
                ],
            },
            Pin {
                position: "N2",
                signals: &[
                    "p101",
                ],
            },
            Pin {
                position: "N3",
                signals: &[
                    "p800",
                ],
            },
            Pin {
                position: "N4",
                signals: &[
                    "vcc",
                ],
            },
            Pin {
                position: "N5",
                signals: &[
                    "p503",
                ],
            },
            Pin {
                position: "N6",
                signals: &[
                    "p507",
                ],
            },
            Pin {
                position: "N7",
                signals: &[
                    "vss",
                ],
            },
            Pin {
                position: "N8",
                signals: &[
                    "avcc0",
                ],
            },
            Pin {
                position: "N9",
                signals: &[
                    "avss0",
                ],
            },
            Pin {
                position: "P1",
                signals: &[
                    "p100",
                ],
            },
            Pin {
                position: "P10",
                signals: &[
                    "p008",
                ],
            },
            Pin {
                position: "P11",
                signals: &[
                    "p004",
                ],
            },
            Pin {
                position: "P12",
                signals: &[
                    "p806",
                ],
            },
            Pin {
                position: "P13",
                signals: &[
                    "p511",
                ],
            },
            Pin {
                position: "P14",
                signals: &[
                    "p402",
                ],
            },
            Pin {
                position: "P15",
                signals: &[
                    "p405",
                ],
            },
            Pin {
                position: "P2",
                signals: &[
                    "p802",
                ],
            },
            Pin {
                position: "P3",
                signals: &[
                    "p804",
                ],
            },
            Pin {
                position: "P4",
                signals: &[
                    "p501",
                ],
            },
            Pin {
                position: "P5",
                signals: &[
                    "p504",
                ],
            },
            Pin {
                position: "P6",
                signals: &[
                    "p505",
                ],
            },
            Pin {
                position: "P7",
                signals: &[
                    "p015",
                ],
            },
            Pin {
                position: "P8",
                signals: &[
                    "vrefl",
                ],
            },
            Pin {
                position: "P9",
                signals: &[
                    "vrefl0",
                ],
            },
            Pin {
                position: "R1",
                signals: &[
                    "p801",
                ],
            },
            Pin {
                position: "R10",
                signals: &[
                    "p005",
                ],
            },
            Pin {
                position: "R11",
                signals: &[
                    "p002",
                ],
            },
            Pin {
                position: "R12",
                signals: &[
                    "p000",
                ],
            },
            Pin {
                position: "R13",
                signals: &[
                    "p805",
                ],
            },
            Pin {
                position: "R14",
                signals: &[
                    "p512",
                ],
            },
            Pin {
                position: "R15",
                signals: &[
                    "p401",
                ],
            },
            Pin {
                position: "R2",
                signals: &[
                    "p803",
                ],
            },
            Pin {
                position: "R3",
                signals: &[
                    "p500",
                ],
            },
            Pin {
                position: "R4",
                signals: &[
                    "p502",
                ],
            },
            Pin {
                position: "R5",
                signals: &[
                    "p506",
                ],
            },
            Pin {
                position: "R6",
                signals: &[
                    "p508",
                ],
            },
            Pin {
                position: "R7",
                signals: &[
                    "p014",
                ],
            },
            Pin {
                position: "R8",
                signals: &[
                    "vrefh",
                ],
            },
            Pin {
                position: "R9",
                signals: &[
                    "vrefh0",
                ],
            },
        ],
    },
];
const PINS: &[ChipPin] = &[
    ChipPin {
        name: "P000",
    },
    ChipPin {
        name: "P001",
    },
    ChipPin {
        name: "P002",
    },
    ChipPin {
        name: "P003",
    },
    ChipPin {
        name: "P004",
    },
    ChipPin {
        name: "P005",
    },
    ChipPin {
        name: "P006",
    },
    ChipPin {
        name: "P007",
    },
    ChipPin {
        name: "P008",
    },
    ChipPin {
        name: "P009",
    },
    ChipPin {
        name: "P010",
    },
    ChipPin {
        name: "P014",
    },
    ChipPin {
        name: "P015",
    },
    ChipPin {
        name: "P100",
    },
    ChipPin {
        name: "P101",
    },
    ChipPin {
        name: "P102",
    },
    ChipPin {
        name: "P103",
    },
    ChipPin {
        name: "P104",
    },
    ChipPin {
        name: "P105",
    },
    ChipPin {
        name: "P106",
    },
    ChipPin {
        name: "P107",
    },
    ChipPin {
        name: "P108",
    },
    ChipPin {
        name: "P109",
    },
    ChipPin {
        name: "P110",
    },
    ChipPin {
        name: "P111",
    },
    ChipPin {
        name: "P112",
    },
    ChipPin {
        name: "P113",
    },
    ChipPin {
        name: "P114",
    },
    ChipPin {
        name: "P115",
    },
    ChipPin {
        name: "P200",
    },
    ChipPin {
        name: "P201",
    },
    ChipPin {
        name: "P202",
    },
    ChipPin {
        name: "P203",
    },
    ChipPin {
        name: "P204",
    },
    ChipPin {
        name: "P205",
    },
    ChipPin {
        name: "P206",
    },
    ChipPin {
        name: "P207",
    },
    ChipPin {
        name: "P208",
    },
    ChipPin {
        name: "P209",
    },
    ChipPin {
        name: "P210",
    },
    ChipPin {
        name: "P211",
    },
    ChipPin {
        name: "P212",
    },
    ChipPin {
        name: "P213",
    },
    ChipPin {
        name: "P214",
    },
    ChipPin {
        name: "P300",
    },
    ChipPin {
        name: "P301",
    },
    ChipPin {
        name: "P302",
    },
    ChipPin {
        name: "P303",
    },
    ChipPin {
        name: "P304",
    },
    ChipPin {
        name: "P305",
    },
    ChipPin {
        name: "P306",
    },
    ChipPin {
        name: "P307",
    },
    ChipPin {
        name: "P308",
    },
    ChipPin {
        name: "P309",
    },
    ChipPin {
        name: "P310",
    },
    ChipPin {
        name: "P311",
    },
    ChipPin {
        name: "P312",
    },
    ChipPin {
        name: "P313",
    },
    ChipPin {
        name: "P314",
    },
    ChipPin {
        name: "P315",
    },
    ChipPin {
        name: "P400",
    },
    ChipPin {
        name: "P401",
    },
    ChipPin {
        name: "P402",
    },
    ChipPin {
        name: "P403",
    },
    ChipPin {
        name: "P404",
    },
    ChipPin {
        name: "P405",
    },
    ChipPin {
        name: "P406",
    },
    ChipPin {
        name: "P407",
    },
    ChipPin {
        name: "P408",
    },
    ChipPin {
        name: "P409",
    },
    ChipPin {
        name: "P410",
    },
    ChipPin {
        name: "P411",
    },
    ChipPin {
        name: "P412",
    },
    ChipPin {
        name: "P413",
    },
    ChipPin {
        name: "P414",
    },
    ChipPin {
        name: "P415",
    },
    ChipPin {
        name: "P500",
    },
    ChipPin {
        name: "P501",
    },
    ChipPin {
        name: "P502",
    },
    ChipPin {
        name: "P503",
    },
    ChipPin {
        name: "P504",
    },
    ChipPin {
        name: "P505",
    },
    ChipPin {
        name: "P506",
    },
    ChipPin {
        name: "P507",
    },
    ChipPin {
        name: "P508",
    },
    ChipPin {
        name: "P511",
    },
    ChipPin {
        name: "P512",
    },
    ChipPin {
        name: "P513",
    },
    ChipPin {
        name: "P600",
    },
    ChipPin {
        name: "P601",
    },
    ChipPin {
        name: "P602",
    },
    ChipPin {
        name: "P603",
    },
    ChipPin {
        name: "P604",
    },
    ChipPin {
        name: "P605",
    },
    ChipPin {
        name: "P606",
    },
    ChipPin {
        name: "P607",
    },
    ChipPin {
        name: "P608",
    },
    ChipPin {
        name: "P609",
    },
    ChipPin {
        name: "P610",
    },
    ChipPin {
        name: "P611",
    },
    ChipPin {
        name: "P612",
    },
    ChipPin {
        name: "P613",
    },
    ChipPin {
        name: "P614",
    },
    ChipPin {
        name: "P615",
    },
    ChipPin {
        name: "P700",
    },
    ChipPin {
        name: "P701",
    },
    ChipPin {
        name: "P702",
    },
    ChipPin {
        name: "P703",
    },
    ChipPin {
        name: "P704",
    },
    ChipPin {
        name: "P705",
    },
    ChipPin {
        name: "P706",
    },
    ChipPin {
        name: "P707",
    },
    ChipPin {
        name: "P708",
    },
    ChipPin {
        name: "P800",
    },
    ChipPin {
        name: "P801",
    },
    ChipPin {
        name: "P802",
    },
    ChipPin {
        name: "P803",
    },
    ChipPin {
        name: "P804",
    },
    ChipPin {
        name: "P805",
    },
    ChipPin {
        name: "P806",
    },
    ChipPin {
        name: "P900",
    },
    ChipPin {
        name: "P901",
    },
    ChipPin {
        name: "P905",
    },
    ChipPin {
        name: "P906",
    },
    ChipPin {
        name: "P907",
    },
    ChipPin {
        name: "P908",
    },
];
