// This file is autogenerated by ra-metapac-gen: do not edit by hand.
include!("../metadata_0031.rs");

pub static METADATA: Metadata = Metadata {
    name: "R7FA0E1053CNK",
    family: FAMILY,
    core: CORE,
    memory: MEMORY,
    peripherals: PERIPHERALS,
    events: EVENTS,
    packages: PACKAGES,
    pins: PINS,
    interrupt_count: INTERRUPT_COUNT,
};
