// This file is autogenerated by ra-metapac-gen: do not edit by hand.
pub const NAME: &str = "R7FA4M3AE3CBM";
pub const FAMILY: &str = "R7FA4M3";
pub const CORE: &str = "Cortex-M33";
pub const MEMORY: &[MemoryRegion] = &[
    MemoryRegion {
        name: "RAM",
        kind: "RAM",
        address: 536870912,
        size: 131072,
    },
    MemoryRegion {
        name: "FLASH",
        kind: "ROM",
        address: 0,
        size: 786432,
    },
    MemoryRegion {
        name: "DATA_FLASH",
        kind: "ROM",
        address: 134217728,
        size: 8192,
    },
    MemoryRegion {
        name: "QSPI_FLASH",
        kind: "ROM",
        address: 1610612736,
        size: 67108864,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OFS0",
        kind: "ROM",
        address: 16818432,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OFS1",
        kind: "ROM",
        address: 16818560,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BANKSEL",
        kind: "ROM",
        address: 16818576,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BPS",
        kind: "ROM",
        address: 16818624,
        size: 8,
    },
    MemoryRegion {
        name: "OPTION_SETTING_PBPS",
        kind: "ROM",
        address: 16818656,
        size: 8,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OFS1_SEC",
        kind: "ROM",
        address: 16818688,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BANKSEL_SEC",
        kind: "ROM",
        address: 16818704,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BPS_SEC",
        kind: "ROM",
        address: 16818752,
        size: 8,
    },
    MemoryRegion {
        name: "OPTION_SETTING_PBPS_SEC",
        kind: "ROM",
        address: 16818784,
        size: 8,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OFS1_SEL",
        kind: "ROM",
        address: 16818816,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BANKSEL_SEL",
        kind: "ROM",
        address: 16818832,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_BPS_SEL",
        kind: "ROM",
        address: 16818880,
        size: 8,
    },
];
pub const PERIPHERALS: &[Peripheral] = &[
    Peripheral {
        name: "GPT0",
        address: 1075220480,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT1",
        address: 1075220736,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT2",
        address: 1075220992,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT3",
        address: 1075221248,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT4",
        address: 1075221504,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT5",
        address: 1075221760,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT6",
        address: 1075222016,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT7",
        address: 1075222272,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "ICU",
        address: 1073766400,
        kind: "icu",
        version: "v3",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "MSTP",
        address: 1074282496,
        kind: "mstp",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT0",
        address: 1074266112,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT1",
        address: 1074266144,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT2",
        address: 1074266176,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT3",
        address: 1074266208,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT4",
        address: 1074266240,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT5",
        address: 1074266272,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT6",
        address: 1074266304,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT7",
        address: 1074266336,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT8",
        address: 1074266368,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "RTC",
        address: 1074278400,
        kind: "rtc",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "SYSTEM",
        address: 1073864704,
        kind: "system",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
];
pub const PACKAGES: &[Package] = &[Package {
    name: "144BGA",
    pins: &[
        Pin {
            position: "A1",
            signals: &["p302"],
        },
        Pin {
            position: "A10",
            signals: &["p206"],
        },
        Pin {
            position: "A11",
            signals: &["usbdp"],
        },
        Pin {
            position: "A12",
            signals: &["usbdm"],
        },
        Pin {
            position: "A13",
            signals: &["p408"],
        },
        Pin {
            position: "A2",
            signals: &["p303"],
        },
        Pin {
            position: "A3",
            signals: &["p304"],
        },
        Pin {
            position: "A4",
            signals: &["p305"],
        },
        Pin {
            position: "A5",
            signals: &["p309"],
        },
        Pin {
            position: "A6",
            signals: &["p200"],
        },
        Pin {
            position: "A7",
            signals: &["p208"],
        },
        Pin {
            position: "A8",
            signals: &["p211"],
        },
        Pin {
            position: "A9",
            signals: &["p202"],
        },
        Pin {
            position: "B1",
            signals: &["p300"],
        },
        Pin {
            position: "B10",
            signals: &["p207"],
        },
        Pin {
            position: "B11",
            signals: &["p409"],
        },
        Pin {
            position: "B12",
            signals: &["p407"],
        },
        Pin {
            position: "B13",
            signals: &["p410"],
        },
        Pin {
            position: "B2",
            signals: &["p301"],
        },
        Pin {
            position: "B3",
            signals: &["p307"],
        },
        Pin {
            position: "B4",
            signals: &["p306"],
        },
        Pin {
            position: "B5",
            signals: &["p311"],
        },
        Pin {
            position: "B6",
            signals: &["p201"],
        },
        Pin {
            position: "B7",
            signals: &["p210"],
        },
        Pin {
            position: "B8",
            signals: &["p214"],
        },
        Pin {
            position: "B9",
            signals: &["p204"],
        },
        Pin {
            position: "C1",
            signals: &["p111"],
        },
        Pin {
            position: "C10",
            signals: &["p205"],
        },
        Pin {
            position: "C11",
            signals: &["p411"],
        },
        Pin {
            position: "C12",
            signals: &["p413"],
        },
        Pin {
            position: "C13",
            signals: &["p412"],
        },
        Pin {
            position: "C2",
            signals: &["p108"],
        },
        Pin {
            position: "C3",
            signals: &["p308"],
        },
        Pin {
            position: "C4",
            signals: &["p312"],
        },
        Pin {
            position: "C5",
            signals: &["p310"],
        },
        Pin {
            position: "C6",
            signals: &["res"],
        },
        Pin {
            position: "C7",
            signals: &["p209"],
        },
        Pin {
            position: "C8",
            signals: &["p313"],
        },
        Pin {
            position: "C9",
            signals: &["p203"],
        },
        Pin {
            position: "D1",
            signals: &["p113"],
        },
        Pin {
            position: "D10",
            signals: &["vccusb"],
        },
        Pin {
            position: "D11",
            signals: &["p415"],
        },
        Pin {
            position: "D12",
            signals: &["p414"],
        },
        Pin {
            position: "D13",
            signals: &["p212"],
        },
        Pin {
            position: "D2",
            signals: &["p109"],
        },
        Pin {
            position: "D3",
            signals: &["p110"],
        },
        Pin {
            position: "D4",
            signals: &["vss"],
        },
        Pin {
            position: "D5",
            signals: &["vss"],
        },
        Pin {
            position: "D6",
            signals: &["vcc"],
        },
        Pin {
            position: "D7",
            signals: &["vss"],
        },
        Pin {
            position: "D8",
            signals: &["vcc"],
        },
        Pin {
            position: "D9",
            signals: &["vss"],
        },
        Pin {
            position: "E1",
            signals: &["p115"],
        },
        Pin {
            position: "E10",
            signals: &["vssusb"],
        },
        Pin {
            position: "E11",
            signals: &["p710"],
        },
        Pin {
            position: "E12",
            signals: &["p708"],
        },
        Pin {
            position: "E13",
            signals: &["p213"],
        },
        Pin {
            position: "E2",
            signals: &["p112"],
        },
        Pin {
            position: "E3",
            signals: &["p114"],
        },
        Pin {
            position: "E4",
            signals: &["vcc"],
        },
        Pin {
            position: "F1",
            signals: &["p609"],
        },
        Pin {
            position: "F10",
            signals: &["vcc"],
        },
        Pin {
            position: "F11",
            signals: &["p712"],
        },
        Pin {
            position: "F12",
            signals: &["p711"],
        },
        Pin {
            position: "F13",
            signals: &["xcout"],
        },
        Pin {
            position: "F2",
            signals: &["p612"],
        },
        Pin {
            position: "F3",
            signals: &["p608"],
        },
        Pin {
            position: "F4",
            signals: &["vcc"],
        },
        Pin {
            position: "G1",
            signals: &["p611"],
        },
        Pin {
            position: "G10",
            signals: &["vss"],
        },
        Pin {
            position: "G11",
            signals: &["p709"],
        },
        Pin {
            position: "G12",
            signals: &["p713"],
        },
        Pin {
            position: "G13",
            signals: &["xcin"],
        },
        Pin {
            position: "G2",
            signals: &["p614"],
        },
        Pin {
            position: "G3",
            signals: &["p610"],
        },
        Pin {
            position: "G4",
            signals: &["vss"],
        },
        Pin {
            position: "H1",
            signals: &["p613"],
        },
        Pin {
            position: "H10",
            signals: &["vcl0"],
        },
        Pin {
            position: "H11",
            signals: &["p704"],
        },
        Pin {
            position: "H12",
            signals: &["p703"],
        },
        Pin {
            position: "H13",
            signals: &["p705"],
        },
        Pin {
            position: "H2",
            signals: &["p604"],
        },
        Pin {
            position: "H3",
            signals: &["p605"],
        },
        Pin {
            position: "H4",
            signals: &["vcl"],
        },
        Pin {
            position: "J1",
            signals: &["p602"],
        },
        Pin {
            position: "J10",
            signals: &["vbatt"],
        },
        Pin {
            position: "J11",
            signals: &["p701"],
        },
        Pin {
            position: "J12",
            signals: &["p702"],
        },
        Pin {
            position: "J13",
            signals: &["p700"],
        },
        Pin {
            position: "J2",
            signals: &["p601"],
        },
        Pin {
            position: "J3",
            signals: &["p603"],
        },
        Pin {
            position: "J4",
            signals: &["vcc"],
        },
        Pin {
            position: "K1",
            signals: &["p600"],
        },
        Pin {
            position: "K10",
            signals: &["vcc"],
        },
        Pin {
            position: "K11",
            signals: &["p406"],
        },
        Pin {
            position: "K12",
            signals: &["p404"],
        },
        Pin {
            position: "K13",
            signals: &["p405"],
        },
        Pin {
            position: "K2",
            signals: &["p107"],
        },
        Pin {
            position: "K3",
            signals: &["p105"],
        },
        Pin {
            position: "K4",
            signals: &["vcc"],
        },
        Pin {
            position: "K5",
            signals: &["vss"],
        },
        Pin {
            position: "K6",
            signals: &["vcc"],
        },
        Pin {
            position: "K7",
            signals: &["vss"],
        },
        Pin {
            position: "K8",
            signals: &["p008"],
        },
        Pin {
            position: "K9",
            signals: &["vss"],
        },
        Pin {
            position: "L1",
            signals: &["p106"],
        },
        Pin {
            position: "L10",
            signals: &["p005"],
        },
        Pin {
            position: "L11",
            signals: &["p001"],
        },
        Pin {
            position: "L12",
            signals: &["p402"],
        },
        Pin {
            position: "L13",
            signals: &["p403"],
        },
        Pin {
            position: "L2",
            signals: &["p104"],
        },
        Pin {
            position: "L3",
            signals: &["p102"],
        },
        Pin {
            position: "L4",
            signals: &["p502"],
        },
        Pin {
            position: "L5",
            signals: &["p505"],
        },
        Pin {
            position: "L6",
            signals: &["p503"],
        },
        Pin {
            position: "L7",
            signals: &["avcc0"],
        },
        Pin {
            position: "L8",
            signals: &["avss0"],
        },
        Pin {
            position: "L9",
            signals: &["p007"],
        },
        Pin {
            position: "M1",
            signals: &["p103"],
        },
        Pin {
            position: "M10",
            signals: &["p004"],
        },
        Pin {
            position: "M11",
            signals: &["p002"],
        },
        Pin {
            position: "M12",
            signals: &["p511"],
        },
        Pin {
            position: "M13",
            signals: &["p400"],
        },
        Pin {
            position: "M2",
            signals: &["p101"],
        },
        Pin {
            position: "M3",
            signals: &["p500"],
        },
        Pin {
            position: "M4",
            signals: &["p501"],
        },
        Pin {
            position: "M5",
            signals: &["p507"],
        },
        Pin {
            position: "M6",
            signals: &["p014"],
        },
        Pin {
            position: "M7",
            signals: &["vrefl"],
        },
        Pin {
            position: "M8",
            signals: &["vrefl0"],
        },
        Pin {
            position: "M9",
            signals: &["p009"],
        },
        Pin {
            position: "N1",
            signals: &["p100"],
        },
        Pin {
            position: "N10",
            signals: &["p003"],
        },
        Pin {
            position: "N11",
            signals: &["p000"],
        },
        Pin {
            position: "N12",
            signals: &["p512"],
        },
        Pin {
            position: "N13",
            signals: &["p401"],
        },
        Pin {
            position: "N2",
            signals: &["p800"],
        },
        Pin {
            position: "N3",
            signals: &["p801"],
        },
        Pin {
            position: "N4",
            signals: &["p504"],
        },
        Pin {
            position: "N5",
            signals: &["p506"],
        },
        Pin {
            position: "N6",
            signals: &["p015"],
        },
        Pin {
            position: "N7",
            signals: &["vrefh"],
        },
        Pin {
            position: "N8",
            signals: &["vrefh0"],
        },
        Pin {
            position: "N9",
            signals: &["p006"],
        },
    ],
}];
