// This file is autogenerated by ra-metapac-gen: do not edit by hand.
pub const NAME: &str = "R7FA6M3AH3CFP";
pub const FAMILY: &str = "R7FA6M3";
pub const CORE: &str = "Cortex-M4";
pub const MEMORY: &[MemoryRegion] = &[
    MemoryRegion {
        name: "RAM",
        kind: "RAM",
        address: 536739840,
        size: 655360,
    },
    MemoryRegion {
        name: "FLASH",
        kind: "ROM",
        address: 0,
        size: 2097152,
    },
    MemoryRegion {
        name: "DATA_FLASH",
        kind: "ROM",
        address: 1074790400,
        size: 65536,
    },
    MemoryRegion {
        name: "QSPI_FLASH",
        kind: "ROM",
        address: 1610612736,
        size: 67108864,
    },
    MemoryRegion {
        name: "SDRAM",
        kind: "RAM",
        address: 2415919104,
        size: 134217728,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OFS0",
        kind: "ROM",
        address: 1024,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OFS1",
        kind: "ROM",
        address: 1028,
        size: 4,
    },
    MemoryRegion {
        name: "OPTION_SETTING_SECMPU",
        kind: "ROM",
        address: 1032,
        size: 52,
    },
    MemoryRegion {
        name: "OPTION_SETTING_OSIS",
        kind: "ROM",
        address: 16818512,
        size: 16,
    },
];
pub const PERIPHERALS: &[Peripheral] = &[
    Peripheral {
        name: "GPT0",
        address: 1074233344,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT1",
        address: 1074233600,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT2",
        address: 1074233856,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT3",
        address: 1074234112,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "GPT4",
        address: 1074234368,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT5",
        address: 1074234624,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT6",
        address: 1074234880,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT7",
        address: 1074235136,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT8",
        address: 1074235392,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT9",
        address: 1074235648,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT10",
        address: 1074235904,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT11",
        address: 1074236160,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT12",
        address: 1074236416,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "GPT13",
        address: 1074236672,
        kind: "timer",
        version: "v1",
        mstp: None,
        bit_width: Some(32),
    },
    Peripheral {
        name: "ICU",
        address: 1073766400,
        kind: "icu",
        version: "v3",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "MSTP",
        address: 1074032640,
        kind: "mstp",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT0",
        address: 1074003968,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT1",
        address: 1074004000,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT2",
        address: 1074004032,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT3",
        address: 1074004064,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT4",
        address: 1074004096,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT5",
        address: 1074004128,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT6",
        address: 1074004160,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "PORT7",
        address: 1074004192,
        kind: "gpio",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "RTC",
        address: 1074020352,
        kind: "rtc",
        version: "v1",
        mstp: None,
        bit_width: None,
    },
    Peripheral {
        name: "SYSTEM",
        address: 1073864704,
        kind: "system",
        version: "v2",
        mstp: None,
        bit_width: None,
    },
];
pub const PACKAGES: &[Package] = &[Package {
    name: "100LQFP",
    pins: &[
        Pin {
            position: "1",
            signals: &["p400"],
        },
        Pin {
            position: "2",
            signals: &["p401"],
        },
        Pin {
            position: "3",
            signals: &["p402"],
        },
        Pin {
            position: "4",
            signals: &["p403"],
        },
        Pin {
            position: "5",
            signals: &["p404"],
        },
        Pin {
            position: "6",
            signals: &["p405"],
        },
        Pin {
            position: "7",
            signals: &["p406"],
        },
        Pin {
            position: "8",
            signals: &["vbat"],
        },
        Pin {
            position: "9",
            signals: &["vcl"],
        },
        Pin {
            position: "10",
            signals: &["xcin"],
        },
        Pin {
            position: "11",
            signals: &["xcout"],
        },
        Pin {
            position: "12",
            signals: &["vss"],
        },
        Pin {
            position: "13",
            signals: &["p213"],
        },
        Pin {
            position: "14",
            signals: &["p212"],
        },
        Pin {
            position: "15",
            signals: &["vcc"],
        },
        Pin {
            position: "16",
            signals: &["p708"],
        },
        Pin {
            position: "17",
            signals: &["p415"],
        },
        Pin {
            position: "18",
            signals: &["p414"],
        },
        Pin {
            position: "19",
            signals: &["p413"],
        },
        Pin {
            position: "20",
            signals: &["p412"],
        },
        Pin {
            position: "21",
            signals: &["p411"],
        },
        Pin {
            position: "22",
            signals: &["p410"],
        },
        Pin {
            position: "23",
            signals: &["p409"],
        },
        Pin {
            position: "24",
            signals: &["p408"],
        },
        Pin {
            position: "25",
            signals: &["p407"],
        },
        Pin {
            position: "26",
            signals: &["vssusb"],
        },
        Pin {
            position: "27",
            signals: &["usbdm"],
        },
        Pin {
            position: "28",
            signals: &["usbdp"],
        },
        Pin {
            position: "29",
            signals: &["vccusb"],
        },
        Pin {
            position: "30",
            signals: &["p207"],
        },
        Pin {
            position: "31",
            signals: &["p206"],
        },
        Pin {
            position: "32",
            signals: &["p205"],
        },
        Pin {
            position: "33",
            signals: &["p214"],
        },
        Pin {
            position: "34",
            signals: &["p211"],
        },
        Pin {
            position: "35",
            signals: &["p210"],
        },
        Pin {
            position: "36",
            signals: &["p209"],
        },
        Pin {
            position: "37",
            signals: &["p208"],
        },
        Pin {
            position: "38",
            signals: &["res"],
        },
        Pin {
            position: "39",
            signals: &["p201"],
        },
        Pin {
            position: "40",
            signals: &["p200"],
        },
        Pin {
            position: "41",
            signals: &["p307"],
        },
        Pin {
            position: "42",
            signals: &["p306"],
        },
        Pin {
            position: "43",
            signals: &["p305"],
        },
        Pin {
            position: "44",
            signals: &["p304"],
        },
        Pin {
            position: "45",
            signals: &["vss"],
        },
        Pin {
            position: "46",
            signals: &["vcc"],
        },
        Pin {
            position: "47",
            signals: &["p303"],
        },
        Pin {
            position: "48",
            signals: &["p302"],
        },
        Pin {
            position: "49",
            signals: &["p301"],
        },
        Pin {
            position: "50",
            signals: &["p300"],
        },
        Pin {
            position: "51",
            signals: &["p108"],
        },
        Pin {
            position: "52",
            signals: &["p109"],
        },
        Pin {
            position: "53",
            signals: &["p110"],
        },
        Pin {
            position: "54",
            signals: &["p111"],
        },
        Pin {
            position: "55",
            signals: &["p112"],
        },
        Pin {
            position: "56",
            signals: &["p113"],
        },
        Pin {
            position: "57",
            signals: &["p114"],
        },
        Pin {
            position: "58",
            signals: &["p115"],
        },
        Pin {
            position: "59",
            signals: &["p608"],
        },
        Pin {
            position: "60",
            signals: &["p609"],
        },
        Pin {
            position: "61",
            signals: &["p610"],
        },
        Pin {
            position: "62",
            signals: &["vcc"],
        },
        Pin {
            position: "63",
            signals: &["vss"],
        },
        Pin {
            position: "64",
            signals: &["vcl1"],
        },
        Pin {
            position: "65",
            signals: &["p602"],
        },
        Pin {
            position: "66",
            signals: &["p601"],
        },
        Pin {
            position: "67",
            signals: &["p600"],
        },
        Pin {
            position: "68",
            signals: &["p107"],
        },
        Pin {
            position: "69",
            signals: &["p106"],
        },
        Pin {
            position: "70",
            signals: &["p105"],
        },
        Pin {
            position: "71",
            signals: &["p104"],
        },
        Pin {
            position: "72",
            signals: &["p103"],
        },
        Pin {
            position: "73",
            signals: &["p102"],
        },
        Pin {
            position: "74",
            signals: &["p101"],
        },
        Pin {
            position: "75",
            signals: &["p100"],
        },
        Pin {
            position: "76",
            signals: &["p500"],
        },
        Pin {
            position: "77",
            signals: &["p501"],
        },
        Pin {
            position: "78",
            signals: &["p502"],
        },
        Pin {
            position: "79",
            signals: &["p503"],
        },
        Pin {
            position: "80",
            signals: &["p504"],
        },
        Pin {
            position: "81",
            signals: &["p508"],
        },
        Pin {
            position: "82",
            signals: &["vcc"],
        },
        Pin {
            position: "83",
            signals: &["vss"],
        },
        Pin {
            position: "84",
            signals: &["p015"],
        },
        Pin {
            position: "85",
            signals: &["p014"],
        },
        Pin {
            position: "86",
            signals: &["vrefl"],
        },
        Pin {
            position: "87",
            signals: &["vrefh"],
        },
        Pin {
            position: "88",
            signals: &["avcc0"],
        },
        Pin {
            position: "89",
            signals: &["avss0"],
        },
        Pin {
            position: "90",
            signals: &["vrefl0"],
        },
        Pin {
            position: "91",
            signals: &["vrefh0"],
        },
        Pin {
            position: "92",
            signals: &["p008"],
        },
        Pin {
            position: "93",
            signals: &["p007"],
        },
        Pin {
            position: "94",
            signals: &["p006"],
        },
        Pin {
            position: "95",
            signals: &["p005"],
        },
        Pin {
            position: "96",
            signals: &["p004"],
        },
        Pin {
            position: "97",
            signals: &["p003"],
        },
        Pin {
            position: "98",
            signals: &["p002"],
        },
        Pin {
            position: "99",
            signals: &["p001"],
        },
        Pin {
            position: "100",
            signals: &["p000"],
        },
    ],
}];
